### ISSUE TITLE
Fix unsafe lex_string() implementation

### ISSUE THREAD

**Issue by SimplyTheOther** [Rust-GCC/gccrs#1000]
As per comments committed in #988, the `lex_string`() function has memory safety issues due to its use of a reference to a C++ string, which can lead to problems if the string's lifetime is shorter than the lexer's.

As the lexer was originally designed only to work with files, the implementation of tokenising from a string currently works by using `fmemopen` to open the string as a file. This is then wrapped in a RAIIFile as required by the lexer's constructor. 

The comments suggest one potential fix - allocating a new buffer with fmemopen and copying the string's data into it. 
However, they also seem to suggest that the current implementation of RAIIFile is not capable of doing so. The exact comment is:
```
// But sadly our RAIIFile does not support moving really well... And the
// destructor, which calls fclose(), gets called, triggering a lack of a
// buffer to parse :)
```
I don’t believe that this should occur. The move constructor of RAIIFile copies the fields and then sets the original’s FILE pointer to nullptr in the constructor body, so when the original is set to be destructed (which would be after the move constructor is called), the `fclose(`) is not called on the stream's actual FILE pointer. The move assignment operator does the same - the only potential issue arising if an RAIIFile is assigned to itself (which should not be able to occur).

An alternative solution that I believe would address the problem better conceptually would be to make the lexer into a template class that takes an “InputSource” type argument. 
`InputSource` is currently an internal wrapper inside the lexer that abstracts sourcing characters (`fgetc` for a FILE).
Instead of wrapping a string to look like a file, there could simply be an alternative `StringInputSource` class that sources characters from a string in addition to the previous `FileInputSource` class. 

The advantage of the template solution is that it is conceptually simple, robust and open to further extension, and would be easy to reason about in terms of lifetime, etc. The disadvantage is that it complicates the lexer somewhat and would require all lexer methods to be put in headers, potentially slowing compilation.

**Comment by CohenArthur** [comment]
Hi!

> I don’t believe that this should occur. The move constructor of RAIIFile copies the fields and then sets the original’s FILE pointer to nullptr in the constructor body, so when the original is set to be destructed (which would be after the move constructor is called), the `fclose(`) is not called on the stream's actual FILE pointer. The move assignment operator does the same - the only potential issue arising if an RAIIFile is assigned to itself (which should not be able to occur).

I'm not a C++ expert, but this is simply what I observed. I had originally tried to implement the solution you mention by copying the string's internal buffer, and found myself with nothing to parse. I set a breakpoint on `RAIIFile::close()`, the inner close function called by the destructor, and watched it get called when std::moving the file into the lexer. I didn't look much more into it at the time and simply added a big comment to explain the idea I had.
 
> An alternative solution that I believe would address the problem better conceptually would be to make the lexer into a template class that takes an “InputSource” type argument. `InputSource` is currently an internal wrapper inside the lexer that abstracts sourcing characters (`fgetc` for a FILE). Instead of wrapping a string to look like a file, there could simply be an alternative `StringInputSource` class that sources characters from a string in addition to the previous `FileInputSource` class.

This is exactly what I had tried before! I had even called the template parameter `InputSource` haha. I think I might have gone about it in a ham-fisted way however. It was more complex to work with and the errors were a bit too cryptic for me, so I gave up and scraped my work. I think it would be the cleanest solution but it would definitely hurt compilation time. Modifying the parser, which is also entirely templated, is currently really painful in that regard.
