### ISSUE TITLE
ICE when lowering macro definition in block

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1001]
I tried this code:

```rust
fn main() {
    macro_rules! create_type {
        ($s:ident) => {
            struct $s;
        };
    }
}
```

I expected to see this happen: compilation succeeds

Instead, this happened: ICE when lowering block statements

Since the block contains a macro definition, it tries lowering it using the `ASTLoweringStmt` visitor. And since macro definitions currently do not lower to anything, this fails.

The temporary fix is to move the macro definition outside of the block, so it becomes a crate item. I'm unsure if this is a trail for fixing this

gccrs sha: 865b6090a8f8981cdfc050ea2ee44abbe92de141

**Comment by CohenArthur** [comment]
> Moving the macro definition outside of the block would make it visible outside of it.

Yes sorry I wasn't clear. This "fix" does change the semantics of the macro. I'm not talking about what the compiler should do, simply about how to avoid this while writing test cases for now. But it's not a good solution at all obviously

**Comment by philberty** [comment]
Another fix would be that we add support for

stmt == StmtType::MACRO_DEFINITION

then we ignore it. We should probably stat to add more item and expression types to our AST we already have some of this in the HIR.
