### ISSUE TITLE
Create Rust CONTRIBUTORS file

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#102]
We need to create a contributors file for Rust within the gcc/rust directory. We can allow small contributions without the full copyright assignment papers but for larger pieces of code we will need make sure people are happy with this. This does not mean we should forget any contributors no matter how small.

**Comment by SimplyTheOther** [comment]
How would one actually acquire a copyright assignment form for gccrs? It is probably best to get this question resolved somewhere (maybe not here, but it seemed like it was somewhat relevant). 

Would one use the gcc mailing list (as the [gcc contributor page](https://gcc.gnu.org/contribute.html) suggests)? Technically gccrs has not been merged upstream yet so does this fall under the jurisdiction of gcc yet? Or is a different way preferred?

**Comment by philberty** [comment]
Yes gccrs does not require the full copyright assignment yet but when it comes to merging upstream i think it would nice to maintain a proper file naming all contributors. As the commits will need to be squashed for the initial upstream.

I have been given advice to make sure people know that down the line when we upstream that copyright assignment is a thing and if people  are not happy with that it stops potential problems down the line.

**Comment by NalaGinrut** [comment]
Let me send a mail to gcc mailing list to ask. 
I've signed other copyright assignment for other GNU project, usually, it'll mention project name in the paper, I don't know if our situation is ready for that, since we haven't mentioned the upstream about our project.
But anyway, it's not bad to ask in the mailing list.

**Comment by NalaGinrut** [comment]
I've sent the mail to GCC community and CC to you, let's wait for the reply. Anyway, it's time to let GCC community recognize our work. @philberty @SimplyTheOther

**Comment by NalaGinrut** [comment]
I got a reply here
https://gcc.gnu.org/pipermail/gcc/2021-January/234609.html
It suggests we assign ASAP and the project name should be `gcc`. I think we have to tell each submitter to assign it to help FSF against GPL-violation, that's the reason why assignment paper exists.
https://www.gnu.org/prep/maintain/html_node/Copyright-Papers.html

When do we start?

**Comment by philberty** [comment]
Thanks for that. I already have mine in place as part of Embecosm. It think this only really applies to us @NalaGinrut @SimplyTheOther. When we accept PRs from others if its 10 lines or less i think its ok to not require the copyright assignment.

I have done the process for GCC before when i was working on my python front-end, its fairly quick and simple.

**Comment by bjorn3** [comment]
> When we accept PRs from others if its 10 lines or less i think its ok to not require the copyright assignment.

I think I read on the FSF website that separate contributions of 10 lines or less can combined still be copyrightable.

**Comment by philberty** [comment]
> > When we accept PRs from others if its 10 lines or less i think its ok to not require the copyright assignment.
> 
> I think I read on the FSF website that separate contributions of 10 lines or less can combined still be copyrightable.

I've heard both been mentioned from different people. I will create an automation for the PR if its their first time to remind about copyright assignment.
