### ISSUE TITLE
Allow identifiers other than "priv" to follow a `:vis`

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1060]
When checking for follow-set restrictions, we must allow all identifiers other than "priv" to follow a `:vis` fragment.

The code to change is in `gcc/rust/parse/rust-parse.cc`. Follow-up tokens are checked in `peculiar_fragment_match_compatible`. We currently allow all identifiers after a `:vis`, but that needs to be restricted to all identifiers except "priv".

> FOLLOW(vis) = {`,` any keyword or identifier except a non-raw priv; any token that can begin a type; ident, ty, and path nonterminals}.

From: https://doc.rust-lang.org/reference/macro-ambiguity.html

**Comment by tage64** [comment]
Hello,
If someone hasn't began to work on this, I would like to tacle this as my first issue in preparation for GSoC 2023.
(Just writing this here so that we don't work in parallel.)
