### ISSUE TITLE
gccrs crashes when trying to allocate extremely large array

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1068]
Two test cases expose the issue:

- https://github.com/rust-lang/rust/blob/0e4524e5b4a9c5656fef69f532f96eb9959a1803/src/test/ui/consts/issue-66342.rs
- https://github.com/rust-lang/rust/blob/0e4524e5b4a9c5656fef69f532f96eb9959a1803/src/test/ui/consts/issue-66397.rs

The tests make sure that rustc does not actually try to allocate 4 terabytes of memory during compilation and crashes

**Comment by philberty** [comment]
Nice find @dafaust that looks like the correct solution for correctness. There is one caveat but maybe GCC will handle it for us.

```rust
const A:[u8; 4 * 1024 * 1024 * 1024 * 1024] = [0; 4 * 1024 * 1024 * 1024 * 1024];
```

Rustc also fails to handle this case https://godbolt.org/z/TWznxnfon

I think in a const and possibly even in the static context, a memset may not be possible. Though we could probably figure something out but if rustc fails on a const context then we can fail too lol.

**Comment by bjorn3** [comment]
`std::ptr::write_bytes` which lowers to memset for u8/i8 is const unstable.
