### ISSUE TITLE
Add `-frust-edition=` flag

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1072]
When trying to understand visibility attributes better, I came across this example case:
```rust
mod a {
    type A1 = b::B;
    type A2 = c::C;

    mod b {
        pub(in a) struct B;
        // only works in the 2015 edition
    }

    mod c {
        pub(in crate::a) struct C;
        // compiles on 2015 and 2018
    }
}
```
Passing `--edition=2018` to the rustc invocation causes a compiler error, prompting to use `pub(in crate::a)` instead. We should think about adding a flag to allow specifying the rust edition, which will also be used by cargo-gccrs.

On a second note, we should also think about whether or not we want to support the 2015 edition of rust! The default rust edition is currently 2021, with 2018 still being used a lot.

**Comment by bjorn3** [comment]
The 2015 edition is still used by the libc crate. Likely for compat with very old rustc versions.
