### ISSUE TITLE
macros: Built-in macros do not get expanded recursively

### ISSUE THREAD

**Issue by liushuyu** [Rust-GCC/gccrs#1085]
I tried this code:

```rust
macro_rules! include_str {
    () => {{}};
}

fn main() -> i32 {
    let _ = include_str!(file!());

    0
}
```

I expected to see this happen: The program compiles successfully.
Instead, this happened: Rust GCC reported:

```
rust1: note: SUCCESSFULLY FINISHED INJECTION 
rust1: note: started expansion
macro11.rs:6:13: error: argument must be a string literal
    6 |     let _ = include_str!(file!());
      |             ^
rust1: note: finished expansion
rust1: note: SUCCESSFULLY FINISHED EXPANSION
```

### Meta

- Rust GCC version: 9011184f38a04f81ba3194b826bec3f30a11c07b

**Comment by CohenArthur** [comment]
Thanks :D I think this is basically the same issue as #1084. Having macros as return values is not an issue, but having macro invocations as macro arguments does not work.

**Comment by liushuyu** [comment]
> Thanks :D I think this is basically the same issue as #1084. Having macros as return values is not an issue, but having macro invocations as macro arguments does not work.

Oh, I see. I thought this was due to the way `MacroInvocData` was passed to the built-in macros. Because I tried expanding the following code and it did work:

```rust
macro_rules! add {
    ($e:expr, $($es:expr),*) => {
        $e + add!($($es),*)
    };
    ($e:expr) => {
        $e
    };
}

fn main() -> i32 {
    let b = add!(add!(15, 20), add!(3,4));

    0
}
```

So I guess two different parsing logic were used in these two cases? The `MacroExpander::expand_invoc_semi` and `MacroExpander::expand_invoc` are a bit confusing when I was trying to understand what the actual issue was.

**Comment by CohenArthur** [comment]
Ah, that's really interesting. I'm investigating right now, thank you for the precisions :)

**Comment by liamnaddell** [comment]
This example code doesn't seem to compile with rustc: https://godbolt.org/z/ehvh69WrG

**Comment by liamnaddell** [comment]
```
liam@gentoo ~/expand $ rustc main.rs
error: no rules expected the token `file`
 --> main.rs:6:26
  |
1 | macro_rules! include_str {
  | ------------------------ when calling this macro
...
6 |     let _ = include_str!(file!());
  |                          ^^^^ no rules expected this token in macro call
  |
  = note: while trying to match end of macro

error: aborting due to 1 previous error

liam@gentoo ~/expand $ rustc --version
rustc 1.81.0-nightly (524d806c6 2024-07-05)
```

**Comment by liamnaddell** [comment]
This code (I believe the corrected version?) compiles for both rustc and gccrs (as of 5f001bab74ab079b03694191aaf342edf1c18b86)
```
#![feature(rustc_attrs)]

#[rustc_builtin_macro]
macro_rules! include_str {
    () => {{}};
}

// Make sure this file is named main.rs
macro_rules! file1 {
    () => {
        "main.rs"
    };
}


fn main() {
    let _ = include_str!(file1!());
}
```
So I think this issue can be closed

**Comment by CohenArthur** [comment]
@liamnaddell the `include_str` and `file` macros are defined in Rust's standard library, which is included by `rustc` by default but not by `gccrs`. so the `gccrs` version of the code looks like this:

```rust
#![feature(rustc_attrs)]

#[rustc_builtin_macro]
macro_rules! include_str {
    () => {{}};
}

#[rustc_builtin_macro]
macro_rules! file {
    () => {{}};
}

fn main() {
    let _ = include_str!(file!());
}
```

https://godbolt.org/z/froPeMcsr

and the `rustc` version looks like this:

```rust
fn main() {
    let _ = include_str!(file!());
}
```

but you are right that the first version works with `gccrs`, so we can close the issue. just putting that comment for more context :) 

also note, the code does not work on godbolt for some reason but I expect this is due to a difference in how the `file!()` macro is expanded between `rustc` and `gccrs`. so that needs to be a different issue. the code works when trying it out locally

**Comment by liamnaddell** [comment]
Sounds good, thank you for taking a look
