### ISSUE TITLE
Implement PhantomData

### ISSUE THREAD

**Issue by bjorn3** [Rust-GCC/gccrs#1127]
This is the full definition:

```rust
#[lang = "phantom_data"]
pub struct PhantomData<T: ?Sized>;
```

`PhantomData` is a ZST, but in all other aspects it behaves as if it contains a value of type `T`. For example wrt to variance. It also counts as a use of a generic parameter and thus allows disabling the error that generic parameters need to be used.

**Comment by liushuyu** [comment]
I think this issue could be tagged `good-first-pr` since a naive implementation (which does not actually check whether the annotated type is really a ZST) is pretty straightforward.

**Hints for new contributors:** Check this pull request: https://github.com/Rust-GCC/gccrs/pull/1100.

**Comment by tamaroning** [comment]
Hi, I want to take a shot at this issue.
