### ISSUE TITLE
Incorrect "error: expected [[u8]] got [[u8:CAPACITY]]"

### ISSUE THREAD

**Issue by bjorn3** [Rust-GCC/gccrs#1129]
I tried this code:

```rust
pub trait Hasher {
    fn finish(&self) -> u64;
    fn write(&mut self, bytes: &[u8]);
    fn write_u8(&mut self, i: u8) {
        self.write(&[i])
    }
}

struct SipHasher;

impl Hasher for SipHasher {
    #[inline]
    fn write(&mut self, msg: &[u8]) {
        loop {}
    }

    #[inline]
    fn finish(&self) -> u64 {
        0
    }
}
```

I expected to see this happen: It compiles.

Instead, this happened:

```
<source>:5:21: error: expected [[u8]] got [[u8:CAPACITY]]
    3 |     fn write(&mut self, bytes: &[u8]);
      |                                 ~
    4 |     fn write_u8(&mut self, i: u8) {
    5 |         self.write(&[i])
      |                     ^
<source>:5:20: error: expected [& [u8]] got [& [u8:CAPACITY]]
    3 |     fn write(&mut self, bytes: &[u8]);
      |                                ~
    4 |     fn write_u8(&mut self, i: u8) {
    5 |         self.write(&[i])
      |                    ^
<source>:5:20: error: Type Resolution failure on parameter
<source>:5:9: error: failed to lookup type to MethodCallExpr
    5 |         self.write(&[i])
      |         ^
<source>:5:9: error: failed to type resolve expression
<source>:4:35: error: expected [()] got [<tyty::error>]
    4 |     fn write_u8(&mut self, i: u8) {
      |                            ~      ^
Compiler returned: 1
```

Note that the `Hasher` trait needs to be used to get this error. Rustc checks default method bodies even when a trait is not used.

### Meta

- What version of Rust GCC were you using, git sha if possible.

**Comment by liushuyu** [comment]
Reduced testcase:

```rust
fn write_u8(i: u8) {
    let x: &[u8] = &[i];
}
```

**Comment by philberty** [comment]
I have a fix for this, we are missing the coercion rule for an array to a slice. There is one other part that needs fixed which is slightly related to this which is how he handles coercion_sites in general the code-generation pass doesn't really handle any complex case but we have all the building blocks to make this robust by reusing the adjustment classes we already use for method resolution so there is a refactor needed to take advantage of that.

**Comment by philberty** [comment]
I will Raise the PR for the missing coercion rule and fix the other part in a separate issue
