### ISSUE TITLE
array: incorrect capacity handling

### ISSUE THREAD

**Issue by liushuyu** [Rust-GCC/gccrs#1152]
I tried this code:

```rust
fn main() {
    let f = [0; -4_isize];
    // { dg-error "...." "" { target *-*-* } .-1 }
    // ^ rustc error: mismatched types
    //~| expected `usize`, found `isize`
    let f = [0_usize; -1_isize];
    // { dg-error "...." "" { target *-*-* } .-1 }
    // ^ rustc error: mismatched types
    //~| expected `usize`, found `isize`
}
```

I expected to see this happen: It **does not** compile due to type resolution errors.

Instead, this happened: GCC encountered an error in the GIMPLE lowering phase: 

```
In function ‘repeat_count_1::main’:
rust1: error: size of variable ‘RUSTTMP.3’ is too large
rust1: error: size of variable ‘RUSTTMP.0’ is too large
```

### Meta

- 243ef0dfe713a9fc8d4d80feb488a58b2639f39f

---

Note: The test case was reduced from https://github.com/rust-lang/rust/blob/master/src/test/ui/repeat_count.rs.

**Comment by philberty** [comment]
This is a good find the issue here is in our type resolution of literals, we are missing handling for the type hinds of isize and usize. So the type check for array capacity is:

```
rust1: note: [0x4600120] Usize:usize:(Ref: 14 TyRef: 14[]):bounds:[]
rust1: note: [0x4607080] Infer:<integer>:(Ref: 23 TyRef: 22[22,]):bounds:[]
```

The integer inference variable is because we are missing the isize and usize hints in the switch statement and defaulting to an integer inference variable.

**Comment by philberty** [comment]
Adding label for good first pr we need to add two missing switch cases here: https://github.com/Rust-GCC/gccrs/blob/243ef0dfe713a9fc8d4d80feb488a58b2639f39f/gcc/rust/typecheck/rust-hir-type-check-base.cc#L93-L134
