### ISSUE TITLE
Raw Pointer Support

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#124]
https://doc.rust-lang.org/book/raw-pointers.html

**Comment by bjorn3** [comment]
Does gcc allow disabling struct aliasing and things like that for specific pointers?

**Comment by philberty** [comment]
I think it does -fstrict-aliasing is an option we can tweak in the front-end as far as I am aware. For example we need to always turn on -Warray-bounds to get the index bounds checking on arrays in gcc but this can be handled within the compiler driver.
