### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#130]
This is an issue to track whether we should create a landing page or Jekyll blog etc for this project.

I think it would be nice to have a small blog post to explain the why of the project and links to respective blogs of contributors. What do you think?

**Comment by SimplyTheOther** [comment]
I think this is probably a good idea. I have seen some people confused over some implementation choices (e.g. not reusing rustc frontend), so a page to show our reasoning is probably useful for the project.

**Comment by philberty** [comment]
http://rust-gcc.github.io/gccrs/

There is no content yet but we can raise PRs for it now.

**Comment by bjorn3** [comment]
Why did you add it to the gccrs repo as gh-pages branch instead of a standalone github.com/Rust-GCC/Rust-GCC.github.io repo? That would remove the `/gccrs` part of the url.

**Comment by philberty** [comment]
Ah i didn't know you could do that

**Comment by philberty** [comment]
Its over on https://rust-gcc.github.io/ https://github.com/Rust-GCC/Rust-GCC.github.io
