### ISSUE TITLE
Cannot use type defined later as function return type

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1361]
I tried this code:

```rust
fn foo() -> S {
    S { a: 15 }
}

struct S {
    a: i32,
}

```

I expected to see this happen: No errors

Instead, this happened:
```rust
test.rs:13:16: error: failed to lookup HIR 20 for node 'S'
   13 | fn bidule() -> S {
      |                ^
test.rs:13:1: error: failed to resolve return type
   13 | fn bidule() -> S {
      | ^
```
This might be due to the fact that the return type gets resolved in the top-level resolver and not the item's one.

**Comment by bjorn3** [comment]
Similar to https://github.com/Rust-GCC/gccrs/issues/1006. Even the top-level resolver needs to support looking up names defined after the current location. Rust's name resolution is a fixpoint algorithm interleaved with macro expansion: https://rust-lang.github.io/rfcs/1560-name-resolution.html (I believe the actual implementation first does a "early" name resolution that only resolves macros interleaved with macro expansion and after that it does the full name resolution.)

**Comment by philberty** [comment]
I might take this issue, our name resolution step does resolve this stuff as we can see from the horrible error message that we know the hir id of the item but the type-resolution pass doesn't support it. We have all the bits and pieces now in place to actually fix this.

**Comment by philberty** [comment]
seems to work now too will add a test case
