### ISSUE TITLE
Allow keywords to be regular identifiers for proc macro server

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1398]
In rustc itself keywords are lexed as regular identifiers AFAIK. Only the parser distinguishes between them. Even if you make the lexer distinguish between them in the lexer of gccrs, for proc macro support you will need to emulate the rustc behavior as there is no separate keyword token type in the proc macro api.

_Originally posted by @bjorn3 in https://github.com/Rust-GCC/gccrs/pull/1397#issuecomment-1188934444_

**Comment by P-E-P** [comment]
This issue should have been closed by #2170 but the manual rebase prevented it @CohenArthur.
