### ISSUE TITLE
Infinite loop/hang when expanding recursive statement macros

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1403]
@liushuyu I think this is similar to the issue you fix in #1401, if you're interested

```rust
macro_rules! stmt {
    ($s:stmt) => {
        $s
    };
    ($s:stmt, $($ss:stmt),*) => {
        $s;
        stmt!($($ss),*);
    };
}

fn main() {
    stmt!(
        struct S;
    );
    stmt!(
        struct A;,
        struct B;,
        struct C;,
        struct D;,
        struct E;
    );
}

```

I expected to see this happen: Proper expansion and a bunch of unused warnings

Instead, this happened: Infinite hang/loop

**Comment by liushuyu** [comment]
After some preliminary investigation, I found that this issue is very similar to #1048.

In the sense that an `Stmt` was incorrectly parsed as `Item`, causing a parser stuck.
