### ISSUE TITLE
GCC Git Branch

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#143]
I am going to be mirroring our code over on GCC Git server as a branch this week but we get this error at the moment:

```
Enumerating objects: 4706, done.
Counting objects: 100% (4706/4706), done.
Delta compression using up to 8 threads
Compressing objects: 100% (1699/1699), done.
Writing objects: 100% (4412/4412), 3.33 MiB | 948.00 KiB/s, done.
Total 4412 (delta 3058), reused 3869 (delta 2683)
remote: Resolving deltas: 100% (3058/3058), completed with 271 local objects.
remote: *** Invalid revision history for commit c7c6f785c8e893ec7bcacd1a2319ce309d2450f2:
remote: *** The first line should be the subject of the commit,
remote: *** followed by an empty line.
remote: *** 
remote: *** Below are the first few lines of the revision history:
remote: *** | Adding Rust target hook documentation
remote: *** | Added powerpc target hook and improved aarch64 feature handling
remote: *** | Added DEC Alpha target hook
remote: *** | Added ARC target hook
remote: *** | Created ARM target hook (at least preliminary support)
remote: *** 
remote: *** Please amend the commit's revision history and try again.
remote: error: hook declined to update refs/heads/gccrs
To ssh://gcc.gnu.org/git/gcc.git
 ! [remote rejected]         gcc-mirror -> gccrs (hook declined)
```

**Comment by NalaGinrut** [comment]
@philberty It's necessary to add a subject and line feed before `Adding Rust target hook documentation`. For example:
```
Add target hooks for Rust

Adding Rust target hook documentation
Added powerpc target hook and improved aarch64 feature handling
Added DEC Alpha target hook
Added ARC target hook
Created ARM target hook (at least preliminary support)
```

This can be done with `git rebase -i c7c6f785c8e893ec7bcac^`, and edit the first commit.
I assume you're familiar with `git rebase`, please don't hesitate to ask.

**Comment by dkm** [comment]
Looks like we should have the GCC hook checked before merging if you don't want to have to clean (and rebase) whenever something incorrect gets merged ?

**Comment by philberty** [comment]
Do you mean bring the GCC hook over here too? I am unsure what to do about this issue but I have started a thread over on the gcc mailing list about it. https://gcc.gnu.org/pipermail/gcc/2021-May/236118.html

**Comment by dkm** [comment]
Yes, I've seen your message. I guess the easiest way would be to make sure that commits are valid wrt the GCC's hook, if that's not too hard to do... Or maybe it's possible to disable the hook for some specific branch ? We'll see the answers...

**Comment by tschwinge** [comment]
I've just now confirmed what we already knew:

```
$ git push upstream github/Rust-GCC/gccrs/master:refs/heads/devel/rust/master
Enumerating objects: 15639, done.
Counting objects: 100% (15463/15463), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4018/4018), done.
Writing objects: 100% (14746/14746), 5.61 MiB | 1.64 MiB/s, done.
Total 14746 (delta 11411), reused 13802 (delta 10622)
remote: Resolving deltas: 100% (11411/11411), completed with 395 local objects.
remote: *** Invalid revision history for commit c7c6f785c8e893ec7bcacd1a2319ce309d2450f2:
remote: *** The first line should be the subject of the commit,
remote: *** followed by an empty line.
remote: *** 
remote: *** Below are the first few lines of the revision history:
remote: *** | Adding Rust target hook documentation
remote: *** | Added powerpc target hook and improved aarch64 feature handling
remote: *** | Added DEC Alpha target hook
remote: *** | Added ARC target hook
remote: *** | Created ARM target hook (at least preliminary support)
remote: *** 
remote: *** Please amend the commit's revision history and try again.
remote: error: hook declined to update refs/heads/devel/rust/master
To git+ssh://gcc.gnu.org/git/gcc.git
 ! [remote rejected]         github/Rust-GCC/gccrs/master -> devel/rust/master (hook declined)
error: failed to push some refs to 'git+ssh://gcc.gnu.org/git/gcc.git'
```

For the usual reasons, I'm assuming that we don't intend to rewrite the GCC/Rust Git history (to fix up the commit logs).  So, we'd need to configure the GCC Git hooks to relax the checking, as Joseph had already explained in <http://mid.mail-archive.com/alpine.DEB.2.22.394.2105241618020.247381@digraph.polyomino.org.uk>.

**Comment by tschwinge** [comment]
By the way, instead of just *devel/gccrs*, I'm suggesting to use branch names such as *devel/rust/master*, *devel/rust/gcc-12*, etc., matching the usual GCC branch structure.  (For ongoing maintenance of GCC/Rust on GCC release branches, etc. -- once that is relevant.)

**Comment by tschwinge** [comment]
Per @jsm28's instructions in <http://mid.mail-archive.com/alpine.DEB.2.22.394.2105241618020.247381@digraph.polyomino.org.uk>, and essentially <https://github.com/AdaCore/git-hooks#managing-external-baselines>, I've done:

```
$ git fetch upstream refs/meta/config
[...]
From git+ssh://gcc.gnu.org/git/gcc
 * branch                    refs/meta/config -> FETCH_HEAD
$ git checkout -f FETCH_HEAD
$ $EDITOR project.config
$ git commit -v -- project.config
[...]
[detached HEAD 15e03be6fc6] Enable 'no-precommit-check' for GCC/Rust development branches, 'devel/rust/*'
 1 file changed, 6 insertions(+)
$ git push upstream HEAD:refs/meta/config
[...]
To git+ssh://gcc.gnu.org/git/gcc.git
   f03579097c2..15e03be6fc6  HEAD -> refs/meta/config
```

With that in place, we're then able to synchronize:

```
$ git push upstream github/Rust-GCC/gccrs/master:refs/heads/devel/rust/master
[...]
To git+ssh://gcc.gnu.org/git/gcc.git
 * [new branch]              github/Rust-GCC/gccrs/master -> devel/rust/master
```

See branch _devel/rust/master_ on <https://gcc.gnu.org/git/?p=gcc.git;a=heads>.

I'll take care of updating this, manually, for the time being.  (Thus keeping this issue open.)

---

I've also set up GCC Bugzilla:

  - Add new component _rust_: <https://gcc.gnu.org/bugzilla/editcomponents.cgi?action=edit&product=gcc&component=rust>.
  - Add new version _rust/master_: <https://gcc.gnu.org/bugzilla/editversions.cgi?action=edit&product=gcc&version=rust%2Fmaster>.

**Comment by philberty** [comment]
Thanks to @tschwinge we now have a branch online and this looks to be fixed.
