### ISSUE TITLE
Remove `IdentifierExpr`

### ISSUE THREAD

**Issue by dafaust** [Rust-GCC/gccrs#1456]
`IdentifierExpr`s are our hack, and it would be good to remove eventually in favor of just using Path expressions. 

https://github.com/Rust-GCC/gccrs/blob/eca2ac2c23e0c8b438fd696d4f85e35c9210d8dd/gcc/rust/hir/tree/rust-hir.h#L370-L374

https://github.com/Rust-GCC/gccrs/blob/eca2ac2c23e0c8b438fd696d4f85e35c9210d8dd/gcc/rust/parse/rust-parse-impl.h#L12525-L12533

According to [the reference](https://doc.rust-lang.org/reference/expressions/path-expr.html), references to local variables etc. are just Path Expressions; there is no dedicated Identifier Expression.

The use of both in our codebase is sometimes confusing, for example in the following:
```rust
let x = (Foo::A, 5u8);
match x {
   ...
}
```
the use of `x` in the match scrutinee is not an `IdentifierExpr` but rather a Path expression.

As philbert noted on IRC, it will take some work to remove them and fix regressions which pop up, because `IdentifierExpr`s don't infer generic arguments currently while Paths do.

**Comment by philberty** [comment]
So i have done some testing today and desugared the HIR::IdentifierExpr into a PathInExpression. Its looking not too bad:

```
# of expected passes            6378
# of unexpected failures        163
# of expected failures          51
# of unresolved testcases       84
```

Alot fewer regressions than I thought there would be

**Comment by philberty** [comment]
If i can fix the HIR piece here to fix these regressions we can leave this open as a cleanup step to possibly remove this from the AST down the line.
