### ISSUE TITLE
Unions support

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#157]
https://doc.rust-lang.org/reference/items/unions.html

**Comment by bjorn3** [comment]
Important note: In Rust it is allowed to write an union as one variant and read it again as another variant. You only have to ensure that the layout of the read variant is compatible with the written variant.

**Comment by philberty** [comment]
That is interesting I didn't know that, I am thinking about moving unions and enums to the 2nd milestone for data structures https://github.com/Rust-GCC/gccrs/milestone/3
