### ISSUE TITLE
Enhancement: Optimization issue with tuple return types

### ISSUE THREAD

**Issue by liushuyu** [Rust-GCC/gccrs#1575]
In `rustc`, the compiler may opportunistically optimize the tuple in the function return position to only occupy one register (32-bit, 64-bit or even 128-bit in width).

Example: https://godbolt.org/z/6r7aM5o5r

**Comment by powerboat9** [comment]
Glancing at the example link, this appears to have been fixed at some point. Reducing the example a bit produces https://godbolt.org/z/3fGonMM5v which seems to confirm.

**Comment by powerboat9** [comment]
@philberty I think we can close this.

**Comment by powerboat9** [comment]
@philberty
