### ISSUE TITLE
Name resolution

### ISSUE THREAD

**Issue by NalaGinrut** [Rust-GCC/gccrs#16]
The resolution rules are not well documented in Rust doc, the rustc relies on [librustc_resolve](https://github.com/rust-lang/rust/tree/master/src/librustc_resolve). 

I'm going to list all the rules here (or wiki) for the reference.

**Comment by NalaGinrut** [comment]
- Traverse AST top-down and resolve every encountered name.
- The situation that new scope should be added:
  - A block enclosing with curly braces
  - Let binding
  - Hygiene macro

**Comment by bjorn3** [comment]
The RFC for the current name resolution is: https://github.com/rust-lang/rfcs/blob/master/text/1560-name-resolution.md

**Comment by NalaGinrut** [comment]
Oh nice! That's what we need, I googled an obsoleted result. Thanks!

**Comment by NalaGinrut** [comment]
I think we should also add an option to dump the AST after resolution later, for the debug.

**Comment by philberty** [comment]
I agree we can reuse the same command line option and i think dumping to file would be really helpful aswell lets makea new issue to dump to file instead of console

**Comment by bjorn3** [comment]
Rustc has several versions of this: `rustc -Zunpretty=help`

**Comment by NalaGinrut** [comment]
@bjorn3 nice to know it, however, `-Z` seems only for nightly.

@philberty If you just want to output the current result to a file with an option, I think it's just a few lines code. It's possible to refactor the current dump framework to support multiple dump format, and even for a different stage of the pipeline, but I don't think it's our current work. But it's a good idea to add TODO.

**Comment by NalaGinrut** [comment]
The resolution relies on macro expansion, so I'm starting to work on macros parallelly. #17

**Comment by philberty** [comment]
Sorry for the closed issues i wanted to see if tagging commits linked them to issues but it seems to just close them instead

**Comment by philberty** [comment]
Closing this as there is documentation available over on the wiki for name resolution

**Comment by bjorn3** [comment]
Did you forget to close this?

**Comment by philberty** [comment]
Thanks, Again we are following rustc more documentation will be added to the wiki over time. See -frust-dump-all for debug outputs and this diagram. 

![image](https://user-images.githubusercontent.com/84585/111179583-1f3aa580-85a4-11eb-83f3-fc8acbd62057.png)
