### ISSUE TITLE
Rename spec language `@rs` -> `@rust`

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1603]
> I've just noticed that you named the spec language "rs", I think you
mean to name it "@rust" instead.

Originally posted by @ibuclaw

**Comment by ibuclaw** [comment]
For clarification for the _why_ `@rust`. The spec language is exposed to the command line via `-x language` option.

The expectation was that to invoke rust would be `-x rust` rather than `-x rs`.
