### ISSUE TITLE
Remove cut & paste from tree.def in `CompileExpr::visit(MatchExpr)`

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1640]

**Comment by powerboat9** [comment]
The commented out lines?

**Comment by CohenArthur** [comment]
@powerboat9 yes, I believe that's what I referred to :) sorry this was a long time ago haha

**Comment by powerboat9** [comment]
I think this can be closed after #1826 @CohenArthur

**Comment by CohenArthur** [comment]
Thanks @powerboat9 :)
