### ISSUE TITLE
gcc-patch-dev: ChangeLog entries

### ISSUE THREAD

**Issue by tschwinge** [Rust-GCC/gccrs#1691]
Most of the current gcc-patch-dev commits don't have ChangeLog entries, which is necessary for `git push` to upstream GCC.

Most of them will be a long list of: `[file]: New.` or similar, but it still needs to be done.

You can verify that with `contrib/gcc-changelog/git_check_commit.py --print-changelog [commit]`.

**Comment by marxin** [comment]
And you can use `contrib/mklog.py` to generate a scaffolding of ChangeLog entries:

```
git show HEAD~ | ~/Programming/gcc/contrib/mklog.py
gcc/ChangeLog:

	* config/i386/i386-builtins.cc (fold_builtin_cpu):
	* doc/extend.texi:

gcc/testsuite/ChangeLog:

	* gcc.target/i386/builtin_target.c:
```

where you might be interested in `-s` option and you might need to create empty `ChangeLog` files at new locations.
Just ping me if you need a help.

**Comment by marxin** [comment]
Looking at the patchset, I think you will only need one new changelog file at `gcc/rust/ChangeLog`, am I correct?

**Comment by marxin** [comment]
There are 2 issues that reject 2 patches in the series, so you need to work around it somehow:
https://github.com/matiasb/python-unidiff/issues/104
https://github.com/matiasb/python-unidiff/issues/105

**Comment by tschwinge** [comment]
@marxin, I'm confused: are these "2 unidiff issues that reject 2 patches in the series" relevant also for GCC's automated `ChangeLog` processing, or relevant only for `contrib/mklog.py`?  The latter I can easily work around by simply not using it.  ;-)

**Comment by marxin** [comment]
Unfortunately, it affects both as they use `python-unidiff` library. Anyway, I'm going to work on that early next week.

**Comment by marxin** [comment]
@tschwinge: Do you have any estimation of when you'll be ready to commit the changes?

**Comment by marxin** [comment]
Ok, the problems are not so limiting, I'm going to fix them on Monday.

**Comment by CohenArthur** [comment]
We can also easily work around this issue by not pushing these two tests for the time being, but later on when updating upstream with our dev branch. This would give more time to fix the unidiff issues

**Comment by tschwinge** [comment]
OK, I guess I'm confused why GCC's automated `ChangeLog` processing has to look into the changes instead of just the Git commit log, but if @marxin says that's what it does, then oh well.  :-)

> [matiasb/python-unidiff#104](https://github.com/matiasb/python-unidiff/issues/104)

As I understand, already resolved: <https://inbox.sourceware.org/gcc-patches/e3670826-b9cf-a1a4-4f74-373c356f0994@suse.cz> "unidiff: use newline='\n' argument", thanks!

> [matiasb/python-unidiff#105](https://github.com/matiasb/python-unidiff/issues/105)

Either to be resolved via <https://github.com/matiasb/python-unidiff/pull/106> "support binary patch format" -- or, if that takes longer, we can easily back out the `gcc/rust/logo.png`, as Arthur said, too.

**Comment by marxin** [comment]
> OK, I guess I'm confused why GCC's automated `ChangeLog` processing has to look into the changes instead of just the Git commit log, but if @marxin says that's what it does, then oh well. :-)

You are right, I was too pessimistic and it's correct that the server hook uses only git statistics from `GitPython` package.

> 
> > [matiasb/python-unidiff#104](https://github.com/matiasb/python-unidiff/issues/104)
> 
> As I understand, already resolved: https://inbox.sourceware.org/gcc-patches/e3670826-b9cf-a1a4-4f74-373c356f0994@suse.cz "unidiff: use newline='\n' argument", thanks!

Yes, apparently, this only limited `mklog.py` script. The server hook is fine again.

> 
> > [matiasb/python-unidiff#105](https://github.com/matiasb/python-unidiff/issues/105)
> 
> Either to be resolved via [matiasb/python-unidiff#106](https://github.com/matiasb/python-unidiff/pull/106) "support binary patch format" -- or, if that takes longer, we can easily back out the `gcc/rust/logo.png`, as Arthur said, too.

Here where it only fails is if you use:

```
./contrib/mklog.py 0050-gccrs-Add-README-CONTRIBUTING-and-compiler-logo.patch
Traceback (most recent call last):
  File "/home/marxin/Programming/gcc/./contrib/mklog.py", line 368, in <module>
    output = generate_changelog(data, args.no_functions,
  File "/home/marxin/Programming/gcc/./contrib/mklog.py", line 165, in generate_changelog
    diff = PatchSet(data)
  File "/usr/lib/python3.10/site-packages/unidiff/patch.py", line 461, in __init__
    self._parse(data, encoding=encoding, metadata_only=metadata_only)
  File "/usr/lib/python3.10/site-packages/unidiff/patch.py", line 562, in _parse
    current_file._append_trailing_empty_line()
  File "/usr/lib/python3.10/site-packages/unidiff/patch.py", line 381, in _append_trailing_empty_line
    raise UnidiffParseError('Unexpected trailing newline character')
unidiff.errors.UnidiffParseError: Unexpected trailing newline character
```

while:
```
$ git show me/rust | ./contrib/mklog.py
gcc/rust/ChangeLog:

	* CONTRIBUTING.md: New file.
	* README.md: New file.
	* logo.png: New file.
```

works fine.

So overall, there's nothing that would block you from pushing the commits to the GCC master branch!

**Comment by tschwinge** [comment]
I've force-updated gcc-patch-dev: Add `ChangeLog` snippets to Git commit logs.

Loosely based on `git rev-list --reverse upstream/master..github/Rust-GCC/gccrs/gcc-patch-dev | while read r; do git log --oneline -1 "$r" && git show "$r" | contrib/mklog.py 2>&1; done > ~/tmp/tmp`.
Manually needed to do "gccrs: Add general compilation test cases"; `git show | contrib/mklog.py` failed with `IndexError: list index out of range` in `generate_changelog`, `for line in list(file)[0][0:10]:`.  ;-)

Verified with `git rev-list --reverse upstream/master.. | while read r; do git log --oneline -1 "$r" && contrib/gcc-changelog/git_check_commit.py --print-changelog "$r"; done > ~/tmp/tmp`

No change to the content of the gcc-patch-dev commits.

**Comment by marxin** [comment]
> Manually needed to do "gccrs: Add general compilation test cases"; `git show | contrib/mklog.py` failed with `IndexError: list index out of range` in `generate_changelog`, `for line in list(file)[0][0:10]:`. ;-)

I've just pushed a fix for this typo of issue.

> 
> Verified with `git rev-list --reverse upstream/master.. | while read r; do git log --oneline -1 "$r" && contrib/gcc-changelog/git_check_commit.py --print-changelog "$r"; done > ~/tmp/tmp`

Great! Note you can use a simpler syntax:
`contrib/gcc-changelog/git_check_commit.py upstream/master..`

> 
> No change to the content of the gcc-patch-dev commits.

Cool!

**Comment by tschwinge** [comment]
The `ChangeLog` entries and other technical issues discussed here have been resolved.
