### ISSUE TITLE
How y'all create fedora rpm package

### ISSUE THREAD

**Issue by bryant-the-coder** [Rust-GCC/gccrs#1696]
Can you show me the docs how you all do it?

**Comment by CohenArthur** [comment]
Hi there :) we don't currently release or maintain dnf packages, if that's what you mean. For compiling gccrs you should be able to follow the README, and if you get any errors or missing dependencies feel free to ask. If you're asking about our buildbot that runs on Fedora, then I can ask around, but it should all be pretty standard. You can get more info by looking at the logs for one of our builds, like [this one](https://builder.sourceware.org/buildbot/#/builders/16/builds/543)
