### ISSUE TITLE
DCO Sign-off

### ISSUE THREAD

**Issue by SimplyTheOther** [Rust-GCC/gccrs#1697]
As my previous GCC copyright assignment was not processed for some reason, this DCO sign-off shall apply to all my GCC/Rust contributions:

`Signed-off-by: Joel Phillips <simplytheother@gmail.com>`

Please let me know if I need to do anything else as part of the DCO sign-off process.

**Comment by CohenArthur** [comment]
Thank you @SimplyTheOther ! I've amended the commits where we've marked you as author. For reference, these are the commits concerned:

```
680252fa050 gccrs: Add Parser for Rust front-end pt.2
7fa0247e273 gccrs: Add Parser for Rust front-end pt.1
ea93ec3070f gccrs: Add Lexer for Rust front-end
9beeac5a027 gccrs: Add Rust AST visitors
7885748749f gccrs: Add full definitions of Rust AST data structures
82e6b2589eb gccrs: Add definitions of Rust Items in AST data structures
7a8c2353517 gccrs: Add Rust front-end base AST data structures
```

**Comment by tschwinge** [comment]
And, please also add `Signed-off-by` to `gccrs: Add expansion pass for the Rust front-end`, next to its `Co-authored-by: The Other ***@***.***>`, and adjust the name of the latter.

**Comment by CohenArthur** [comment]
@tschwinge right :) thanks for checking. Fixed

**Comment by tschwinge** [comment]
> And, please also add `Signed-off-by` to `gccrs: Add expansion pass for the Rust front-end`, next to its `Co-authored-by: [...] <simplytheother@gmail.com>`

Now just that is missing -- then we're good, in my opinion, to integrate gcc-patch-dev into GCC upstream!  :open_mouth:

**Comment by CohenArthur** [comment]
Ah, right :) Silly me. Fixed! I'll now give everything a last build, check-rust and bootstrap check juuuuuust in case
