### ISSUE TITLE
Revert invalid testsuite timeout

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1747]
Introduced in 997894f6372d057e22cd54cc7b9fefdfdc77520a

**Comment by DrMahad** [comment]
- @CohenArthur could you assign me this issue & mentor me. 😄

**Comment by Parthib314** [comment]
Hey @CohenArthur,  can I work on this issue?

**Comment by CohenArthur** [comment]
Yup go ahead @Parthib314 ! Thanks :)

**Comment by philberty** [comment]
Added context: https://github.com/Rust-GCC/gccrs/pull/1759#issuecomment-1406357309

**Comment by CohenArthur** [comment]
Closed by #1759
