### ISSUE TITLE
Rename rust-hir-full-test.cc

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#1764]
We should rename rust-hir-full-test.cc its not a very good name as it is the implementation code for the HIR so we should simply cally this rust-hir.cc

**Comment by SainiAditya1** [comment]
@philberty please assign this to me

**Comment by CohenArthur** [comment]
@SainiAditya1 thanks :) feel free to work on this

**Comment by CohenArthur** [comment]
Fixed by #1780
