### ISSUE TITLE
rename rust-ast-full-test.cc

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#1765]
rename rust-ast-full-test.cc to be rust-ast.cc is a bettername

**Comment by Parthib314** [comment]
Hey, @philberty  Can I work on it??

**Comment by Parthib314** [comment]
@philberty  Does I only need to rename the `rust-ast-full-ast.cc` or I have to update it in [gccrs/gcc/rust/Make-lang.in](https://github.com/Rust-GCC/gccrs/blob/9c21f45e4534afaa41456f342ceff9db52814053/gcc/rust/Make-lang.in#L76) too?

**Comment by powerboat9** [comment]
I think this can be closed.
