### ISSUE TITLE
Implement eager expansion for `column!()`

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1800]

**Comment by mvvsmk** [comment]
@CohenArthur could you assign this to me so I can start working on it?

**Comment by CohenArthur** [comment]
Uh, good catch @mvvsmk I don't know why these macros should be expanded eagerly. I was thinking this was to allow empty macro expansions (https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8dfe3c4c59bd9595acd0bce60ac59589), but it seems that this is caught even earlier and isn't allowed. So we can probably close these three issues. I'll have a more detailed check and report back
