### ISSUE TITLE
Refactor rust-hir-trait-reference.h to put the implementation into a cc file

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#1835]
all of the implementations of the classes in https://github.com/Rust-GCC/gccrs/blob/master/gcc/rust/typecheck/rust-hir-trait-reference.h are implemented in the header. We should create an associated rust-hir-trait-reference.cc file and move the implementation code in here to make the header smaller.

**Comment by CohenArthur** [comment]
@P-E-P is working on it

**Comment by P-E-P** [comment]
I'd like to work on this!
