### ISSUE TITLE
Invalid parsing of empty tuple as pattern

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1848]
I tried this code:

```rust
fn main() {
    let () = ();
}
```

I expected to see this happen: no error

Instead, this happened:
```rust
test.rs:2:10: error: unexpected token ‘)’ in pattern
    2 |     let () = ();
      |          ^
test.rs:2:10: error: failed to parse pattern in grouped or tuple pattern
test.rs:2:10: error: failed to parse pattern in let statement
test.rs:2:5: error: failed to parse statement or expression without block in block expression
    2 |     let () = ();
      |     ^~~
test.rs:3:1: error: unrecognised token ‘}’ for start of item
    3 | }
      | ^
test.rs:3:1: error: failed to parse item in crate
```

### Meta

- What version of Rust GCC were you using: 3a8c8d0d41b57fbb49ab39715b70495d5d1e8dd1

**Comment by powerboat9** [comment]
How would ```Signed-off-by``` work for the test?

**Comment by CohenArthur** [comment]
> How would `Signed-off-by` work for the test?

What do you mean? The test should be added in a commit or its own commit, which will simply be signed. If you take on the issue you can simply take the test and commit it using your name :) no worries about that

**Comment by powerboat9** [comment]
Ok, thanks
