### ISSUE TITLE
Upstream GCC broken for --target=pdp11-aout

### ISSUE THREAD

**Issue by jbglaw** [Rust-GCC/gccrs#1864]
Hi!

Testing revealed that a rust-enabled upstream GCC build (at g:06ca0c9abb260266b688e2c2154c72214bb47076) for --target=pdp11-aout breaks:
```
../gcc/configure '--with-pkgversion=basepoints/gcc-13-5954-g06ca0c9abb2, built at 1676413490' --prefix=/var/lib/laminar/run/gcc-pdp11-aout/57/toolchain-install --enable-werror-always --enable-languages=all --disable-gcov --disable-shared --disable-threads --target=pdp11-aout --without-headers
[...]
make V=1 all-gcc
[...]
[all 2023-02-15 01:32:13] /usr/lib/gcc-snapshot/bin/g++  -fno-PIE -c  -DIN_GCC_FRONTEND -g -O2   -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Wconditionally-supported -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings -Werror -Wno-unused-parameter -fno-common  -DHAVE_CONFIG_H -I. -Irust -I../../gcc/gcc -I../../gcc/gcc/rust -I../../gcc/gcc/../include  -I../../gcc/gcc/../libcpp/include -I../../gcc/gcc/../libcody  -I../../gcc/gcc/../libdecnumber -I../../gcc/gcc/../libdecnumber/dpd -I../libdecnumber -I../../gcc/gcc/../libbacktrace   -o rust/rust-tree.o -MT rust/rust-tree.o -MMD -MP -MF rust/
.deps/rust-tree.TPo -g -O2   -I ../../gcc/gcc/rust -I ../../gcc/gcc/rust/lex -I ../../gcc/gcc/rust/parse -I ../../gcc/gcc/rust/ast -I ../../gcc/gcc/rust/analysis -I ../../gcc/gcc/rust/backend -I ../../gcc/gcc/rust/expand -I ../../gcc/gcc/rust/hir/tree -I ../../gcc/gcc/rust/hir -I ../../gcc/gcc/rust/resolve -I ../../gcc/gcc/rust/util -I ../../gcc/gcc/rust/typecheck -I ../../gcc/gcc/rust/checks/lints -I ../../gcc/gcc/rust/checks/errors -I ../../gcc/gcc/rust/checks/errors/privacy -I ../../gcc/gcc/rust/util -I../../gcc/gcc/rust/metadata ../../gcc/gcc/rust/backend/rust-tree.cc
[all 2023-02-15 01:32:16] In file included from ./tm.h:18,
[all 2023-02-15 01:32:16]                  from ../../gcc/gcc/target.h:52,
[all 2023-02-15 01:32:16]                  from ../../gcc/gcc/rust/backend/rust-tree.cc:34:
[all 2023-02-15 01:32:16] ../../gcc/gcc/rust/backend/rust-tree.cc: In function 'void Rust::mark_exp_read(tree)':
[all 2023-02-15 01:32:16] ../../gcc/gcc/config/pdp11/pdp11.h:572:3: error: 'pdp11_gen_int_label' was not declared in this scope
[all 2023-02-15 01:32:16]   572 |   pdp11_gen_int_label ((LABEL), (PREFIX), (NUM))
[all 2023-02-15 01:32:16]       |   ^~~~~~~~~~~~~~~~~~~
[all 2023-02-15 01:32:16] ../../gcc/gcc/rust/backend/rust-tree.cc:53:3: note: in expansion of macro 'ASM_GENERATE_INTERNAL_LABEL'
[all 2023-02-15 01:32:16]    53 |   ASM_GENERATE_INTERNAL_LABEL (tmp_name, "Lsrc_loc", 1);
[all 2023-02-15 01:32:16]       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[all 2023-02-15 01:32:17] ../../gcc/gcc/rust/backend/rust-tree.cc: In function 'tree_node* Rust::fold_builtin_source_location(location_t)':
[all 2023-02-15 01:32:17] ../../gcc/gcc/config/pdp11/pdp11.h:572:3: error: 'pdp11_gen_int_label' was not declared in this scope
[all 2023-02-15 01:32:17]   572 |   pdp11_gen_int_label ((LABEL), (PREFIX), (NUM))
[all 2023-02-15 01:32:17]       |   ^~~~~~~~~~~~~~~~~~~
[all 2023-02-15 01:32:17] ../../gcc/gcc/rust/backend/rust-tree.cc:4799:7: note: in expansion of macro 'ASM_GENERATE_INTERNAL_LABEL'
[all 2023-02-15 01:32:17]  4799 |       ASM_GENERATE_INTERNAL_LABEL (tmp_name, "Lsrc_loc", source_location_id++);
[all 2023-02-15 01:32:17]       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[all 2023-02-15 01:32:17] make[1]: *** [../../gcc/gcc/rust/Make-lang.in:367: rust/rust-tree.o] Error 1
[all 2023-02-15 01:32:17] rm m2/gm2-compiler-boot/P2Build.mod m2/gm2-compiler-boot/P0SyntaxCheck.mod m2/gm2-compiler-boot/PCBuild.mod m2/gm2-compiler-boot/PHBuild.mod m2/gm2-compiler-boot/P1Build.mod m2/gm2-compiler-boot/P3Build.mod
[all 2023-02-15 01:32:17] make[1]: Leaving directory '/var/lib/laminar/run/gcc-pdp11-aout/57/toolchain-build/gcc'
[all 2023-02-15 01:32:18] make: *** [Makefile:4618: all-gcc] Error 2
```
(Full build log at http://toolchain.lug-owl.de/laminar/log/gcc-pdp11-aout/57)

I'll bisect from the previous successful build, will take a second or two. ;-)

**Comment by CohenArthur** [comment]
Uh! Same error as #1819. That's weird. Thanks for the report :)

**Comment by jbglaw** [comment]
Yeah, that's odd. Especially, since (I'm quite sure, but didn't check) pdp11-aout did build at the time the ppc-aix stuff got broken.

**Comment by powerboat9** [comment]
This could be very helpful for tracking down whatever hidden dependency(s) in ```rust-tree.cc``` are causing the issue, as some discrete change on the gcc end must have removed an implicit dependency after we pushed our changes.

**Comment by CohenArthur** [comment]
I think it's fine to keep both issues up and maybe close them both at the same time when we eventually resolve the problem. @jbglaw, would you mind testing the commit with this master branch instead of upstream's? You can fetch the remote at `https://github.com/rust-gcc/gccrs`. If it's too much of a pain no worries :) But I'd be interested in knowing if we already have this fixed magically here thanks to the target changes and so on.

**Comment by jbglaw** [comment]
So along with master of git://gcc.gnu.org/git/gcc.git, additionally also build master of https://github.com/rust-gcc/gccrs ?  Technically, that's really quite easy. I'll prepare a run or two. ;-)  Might be useful to run that more often, but I'd really search for sponsors there. It's all running on a DL360e Gen8 (2x Xeon E5-2450L, 64 GB RAM) which isn't (by today's standards) the fastest thing around. But ... I'll integrate the Rust GCC tree as well.

**Comment by CohenArthur** [comment]
> So along with master of git://gcc.gnu.org/git/gcc.git, additionally also build master of https://github.com/rust-gcc/gccrs ? Technically, that's really quite easy. I'll prepare a run or two. ;-) Might be useful to run that more often, but I'd really search for sponsors there. It's all running on a DL360e Gen8 (2x Xeon E5-2450L, 64 GB RAM) which isn't (by today's standards) the fastest thing around. But ... I'll integrate the Rust GCC tree as well.

The goal is for `git://ggcc.gnu.org/git/gcc.git` and this repository to not be out of sync too much. But at least for this GCC 13 release we are out of sync on some patches (#1744) and are still figuring out a proper "upstream schedule". So GCC upstream is quite far behind at the moment, but that's a temporary situation :)

**Comment by jbglaw** [comment]
It's generating the Docker image for the new `gccrs` build series right now. After that, I'll queue in some first test builds. (I usually forget something along the path. ^^)  If you want to follow the outcome, please read http://toolchain.lug-owl.de/ and probably specifically the Telegram group link. I usually just queue in the (now about 1850) jobs and react on those that changed.

**Comment by jbglaw** [comment]
See here for the very first (successful!) build from the gcc-rust repo: http://toolchain.lug-owl.de/laminar/jobs/gccrs-alpha-linux

Currently, a bunch of Linux kernels are building (all defconfigs.) When that queue is done, I'll queue in all gccrs targets (the same as for upstream gcc.)

**Comment by jbglaw** [comment]
Sorry to inform you, but `--target=pdp11-aout` is also broken in Rust's GIT tree: http://toolchain.lug-owl.de/laminar/jobs/gccrs-pdp11-aout/1

**Comment by powerboat9** [comment]
https://gcc.gnu.org/onlinedocs/gccint/Target-Macros.html

Since we have ```tm.h``` according to the build log, everything *should* be working.

**Comment by powerboat9** [comment]
Are we missing ```config.h```?

**Comment by jbglaw** [comment]
Here's the current build status diff for my `gcc` jobs (that's gcc upstream) compared to the `gccrs` jobs (your tree). That's always `<jobname>:<gcc-result>:<gccrs-result>`, with 4 == failed and 5 == success:

```
$ cat most-recent-comparison-of-gcc-vs-gccrs-diffs.txt 
gcc-bpf-unknown-none:5:4
gcc-nvptx-none:4:5
gcc-pdp11-aout:5:4
gcc-powerpc-ibm-aix7.1:5:4
gcc-powerpc-ibm-aix7.2:5:4
```
* `gcc-bpf-unknown-none` has a (local) fix for a warning (that's not applied to the gccrs build) where I've not yet decided whether or not that's actually a correct warning, so that's a non-issue.
* `gcc-nvptx-none`: ditto.
* `gcc-pdp11-aout`, `gcc-powerpc-ibm-aix7.1` and `gcc-powerpc-ibm-aix7.2`: As mentioned above, upstream GCC gained a commit to fix these issues that's not yet (been?) in your tree.

So as a general rule, there's no Rust-related differences that lead to significant build status differences.

**Comment by jbglaw** [comment]
Just got confirmation in the Telegram group "Toolchain Build Results" that for `gccrs-pdp11-aout`, the build changed to `success`.

**Comment by CohenArthur** [comment]
Ah, thanks @jbglaw :DD I meant to ping you about these later. Glad to know it's resolved!
