### ISSUE TITLE
Add is_equal to TyTy types

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#187]
Currently to check if types are equal or can be unified we call combine. This is inefficient for many cases like FnTypes we want a strict is_equal check.

We can add this as an abstract method to the TyTy::TyBase, it might be worth renaming this class at the same time as the name bugs me.

**Comment by RuchiGitHu** [comment]
Good Evening,
I want to fix the issue but this is my first step towards contributing in open source project. Please let me know about this issue.
Thanks in advance..

**Comment by philberty** [comment]
Hi @RuchiGitHu thanks for your interest. Please be aware in this project we require contributors to follow the copyright assignment process https://gcc.gnu.org/contribute.html 

There are 2 parts to this issue.

1. Where inside https://github.com/Rust-GCC/gccrs/blob/master/gcc/rust/typecheck/rust-tyty.h we rename and refactor the usage of TyBase I think the name is bad at the moment, maybe call it BaseType. It represents the abstract base class for all potential types within the rust language. Such as ADTType which is the algebraic data type to represent structs for example. The purpose here is a cleanup effort on naming.
2. The next piece is we need to add a new virtual method to this BaseType class in the same file called: virtual bool is_equal(TypeBase&other) const {} For now this can be implemented within the base class like this {  return get_type() == other.get_type(); }

Some more thought is needed once this block of work is in as to where we use this instead of calling combine to unify types.

Hope this helps.

**Comment by RuchiGitHu** [comment]
Thanks @philberty for the information you provided to me. I will try to fix it.

**Comment by philberty** [comment]
Fixed in #238
