### ISSUE TITLE
Add location info when opening a file fails in `include_{,str,bytes}!()`

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1872]
We are missing proper location info when emitting errors for these three "include" macros. We should error out using the invocation's location, so that the user knows which macro invocation is invalid.

**Comment by nikos-alexandris** [comment]
Hi, I would like to try resolving this issue as my first issue on GCC :)

**Comment by nikos-alexandris** [comment]
Shouldn't this issue be marked as closed? The `include_str` and `include_bytes` macros were fixed with the commits referenced above, and the `include` macro already reports the invocation's location in the error message.

**Comment by CohenArthur** [comment]
Correct! We forgot to add a `Fixes #1872` to https://github.com/Rust-GCC/gccrs/pull/1955 :) thank you @nikos-alexandris
