### ISSUE TITLE
Add helpers for Rust -> C++ in libproc_macro interactions

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1890]

**Comment by P-E-P** [comment]
@CohenArthur could you provide additional details for this issue? I don't remember any detail about it. We already have some helpers in C++ `libproc_macro` but I feel this is not what this issue is about.

**Comment by CohenArthur** [comment]
Since that was at the beginning of the internship, I think we can safely close it now - it was probably some helpers about FFI in general but you did good on that front
