### ISSUE TITLE
unknown lang item i32

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#1896]
I tried this code:

```rust
#[lang = "i32"]
impl i32 {}
```

I expected to see this happen: compile without error

Instead, this happened: 

```
test.rs:12:3: error: unknown lang item
   12 | #[lang = "i32"]
      |   ^~~~

```

### Meta

- What version of Rust GCC were you using, git sha if possible. 87e7c9dedacd4d12636e6c626aab14bcecf686f2

**Comment by philberty** [comment]
The fix here should add the list of i32, i16 etc

**Comment by SainiAditya1** [comment]
@CohenArthur  I want to work on this issue..

**Comment by powerboat9** [comment]
https://github.com/rust-lang/rust/commit/afbecc0f68c4dcfc4878ba5bcb1ac942544a1bdc

It looks like rustc stopped handling this a while ago, but "a while ago" would be after ```libcore 1.49```.

**Comment by powerboat9** [comment]
#1494
