### ISSUE TITLE
Bad cast error when behind generics

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#1897]
I tried this code: https://godbolt.org/z/MWbn8587K

```rust
fn test<T>(a:T) -> T {
    a
}

fn main() {
    let a:i32 = test(123 as i32) as i32;
}
```

I expected to see this happen: compile without error

Instead, this happened:

```
<source>:6:17: error: invalid cast 'i32' to 'i32' [E0054]
    6 |     let a:i32 = test(123 as i32) as i32;
      |                 ^~~~                ~~~
```

### Meta

- What version of Rust GCC were you using, git sha if possible.

**Comment by philberty** [comment]
There is a missing call to destructure going on here

**Comment by goar5670** [comment]
Hello, I want to take on this issue but I need some guidance.
