### ISSUE TITLE
CI step `build-and-check-gcc-48` gets cancelled instantly

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1900]
Either github actions need a moment, or maybe the Ubuntu 18.04 image has been deprecated and removed for good. In which case we can just run this step in a Ubuntu 18.04 docker container

**Comment by bjorn3** [comment]
> This is a scheduled Ubuntu-18.04 brownout. The Ubuntu-18.04 environment is deprecated and will be removed on April 1st, 2023. For more details, see https://github.com/actions/runner-images/issues/6002

**Comment by CohenArthur** [comment]
Nice! Thanks @bjorn3 :) I hadn't seen the message. I guess we'll need to either make a Docker image with gcc 4.8 built from source or just run the action in an Ubuntu 18.04 container (which is bad... but easier)
