### ISSUE TITLE
Diagnostics and option help texts: GCC PR108890 "Translation mistakes 2023"

### ISSUE THREAD

**Issue by tschwinge** [Rust-GCC/gccrs#1916]
There are translations into many languages for GCC diagnostics (for example, `gcc -x gust /dev/null`: `gcc: Fehler: Sprache gust nicht erkannt`) and option help texts (for example, `gcc --help`: `--version  Compilerversionsinformation anzeigen.`), see <https://translationproject.org/domain/gcc.html>.  In <https://gcc.gnu.org/PR108890> "Translation mistakes 2023" @rillig lists several issues with GCC/Rust diagnostics and option help texts (but also a few non-GCC/Rust ones).  Resolving these should make a *good-first-pr*.

The task here is not to work on the translations, but to fix the English-language "template" messages, like in `[source-gcc]/gcc/rust/lang.opt`, for example.

**Comment by TieWay59** [comment]
Hi, @tschwinge @rillig @CohenArthur I'd love to pick up this issue. Here is what I learned from the investigation and please help anwser my confusions and correct me if I'm wrong:

> https://github.com/Rust-GCC/gccrs/blob/ae80bcdd9b3bb8ace429804dd0f493d9f31b7c29/gcc/config/xtensa/xtensa-dynconfig.c#L114
> 
> That string is marked as 'format-c' but should be 'format-gcc-internal'.

Q1: This is a c file and according to the discussion I'm not so sure how to correct it.

> https://github.com/Rust-GCC/gccrs/blob/ae80bcdd9b3bb8ace429804dd0f493d9f31b7c29/gcc/m2/lang-specs.h#L48
> 
> Trailing whitespace, wrong quotes.

Q2: What are the right quotes? Should it be `%eto generate dependencies you must specify -fcpp}} \ ` 

> https://github.com/Rust-GCC/gccrs/blob/ae80bcdd9b3bb8ace429804dd0f493d9f31b7c29/gcc/rust/lang.opt#L59
> https://github.com/Rust-GCC/gccrs/blob/ae80bcdd9b3bb8ace429804dd0f493d9f31b7c29/gcc/rust/lang.opt#L67
> The upper is indented using spaces, the lower using a single tab. That's inconsistent.

Q3: I see most of the text is using spaces, so how many spaces are appropriate in this case? 4 or just align to the upper one?

> https://github.com/Rust-GCC/gccrs/blob/ae80bcdd9b3bb8ace429804dd0f493d9f31b7c29/gcc/rust/lang.opt#L75
> Placeholders should be enclosed in <>.

I got it, it should be `-frust-max-recursion-depth=<integer>`

> https://github.com/Rust-GCC/gccrs/blob/ae80bcdd9b3bb8ace429804dd0f493d9f31b7c29/gcc/rust/lang.opt#L79
> The word 'Choose' is redundant and should be removed.
> This word occurs in other messages as well. (This one? ⬇️ )
> 
> https://github.com/Rust-GCC/gccrs/blob/ae80bcdd9b3bb8ace429804dd0f493d9f31b7c29/gcc/rust/lang.opt#L96

Q4: Do you prefer `Which version to use for name mangling` or `Version to use for name mangling` ? Please tell me which pattern is better. 

> https://github.com/Rust-GCC/gccrs/blob/ae80bcdd9b3bb8ace429804dd0f493d9f31b7c29/gcc/rust/lang.opt#L112
> The word 'Flag' is redundant. Typo in 'embeding'.

`Enable embedding metadata directly into object files` 

> https://github.com/Rust-GCC/gccrs/blob/ae80bcdd9b3bb8ace429804dd0f493d9f31b7c29/gcc/rust/lang.opt#L124
> The word 'until' sounds inclusive, the phrase 'When to stop' sounds exclusive.
> Typo in 'copimlation'.

Q5: let me make sure is it literally a `compilation`? And is `The pipeline works until this stage when compiling Rust code` better?

> https://github.com/Rust-GCC/gccrs/blob/ae80bcdd9b3bb8ace429804dd0f493d9f31b7c29/gcc/c-family/c.opt#L985
> Typo in 'inproper'.

`Warn about improper usages of flexible array members `

> Enable certain features present drafts of C++ Contracts.

Not found in this codebase.

**Comment by CohenArthur** [comment]
> Q3: I see most of the text is using spaces, so how many spaces are appropriate in this case? 4 or just align to the upper one?
Align to the upper one is fine imo. Maybe @tschwinge and @dkm have a more developed opinion :)

> Q4: Do you prefer Which version to use for name mangling or Version to use for name mangling ? Please tell me which pattern is better.
"Version to use for name mangling" IMO :)

> Q5: let me make sure is it literally a compilation? 
Yes!
> And is The pipeline works until this stage when compiling Rust code better?
I'm not sure about that one. `Until` didn't sound inclusive to me but I might be wrong
