### ISSUE TITLE
Add feature gating behind `#![feature(extern_types)]`

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1925]
The `ExternalTypeItem` node added by #1924 should only be allowed if `#![feature(extern_types)]` is present

@TuringKi maybe this is something you'd like to work on?

**Comment by TuringKi** [comment]
Thanks, good to know, i will check it, maybe in 1-2 days :)

**Comment by CohenArthur** [comment]
Fixed in #1929, closing
