### ISSUE TITLE
ICE with #1929 commit 9c46a853be4b5a9c2e1b965fa0dcd44beed71924 "Add feature gate definition for `extern_types`"

### ISSUE THREAD

**Issue by tschwinge** [Rust-GCC/gccrs#1952]
In <https://inbox.sourceware.org/gcc-rust/20230301155932.B1C953858D33@sourceware.org> "☠ Buildbot (Sourceware): gccrust - failed 'grep unexpected ...' (failure) (master)" an ICE has been reported for #1929 commit 9c46a853be4b5a9c2e1b965fa0dcd44beed71924 "Add feature gate definition for `extern_types`" (@TuringKi) for 32-bit x86:

```
rust1: internal compiler error: Segmentation fault
0x8d425ca crash_signal
	../../gccrs/gcc/toplev.cc:314
0xb76dc3d6 ???
	../sysdeps/i386/i586/strlen.S:64
0xb769f416 __vfprintf_internal
	./stdio-common/vfprintf-internal.c:1688
0xb76b0592 __vasprintf_internal
	./libio/vasprintf.c:57
0xb76b0695 __vasprintf
	./libio/vasprintf.c:90
0x859702a expand_message
	../../gccrs/gcc/rust/rust-diagnostics.cc:118
0x85975d8 rust_error_at(Location, char const*, ...)
	../../gccrs/gcc/rust/rust-diagnostics.cc:192
0x8803081 Rust::FeatureGate::gate(Rust::Feature::Name, Location, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
	../../gccrs/gcc/rust/checks/errors/rust-feature-gate.cc:82
0x8803224 Rust::FeatureGate::visit(Rust::AST::ExternalTypeItem&)
	../../gccrs/gcc/rust/checks/errors/rust-feature-gate.cc:167
0x88030be Rust::FeatureGate::visit(Rust::AST::ExternBlock&)
	../../gccrs/gcc/rust/checks/errors/rust-feature-gate.cc:108
0x8803426 Rust::FeatureGate::check(Rust::AST::Crate&)
	../../gccrs/gcc/rust/checks/errors/rust-feature-gate.cc:63
0x8643043 Rust::Session::compile_crate(char const*)
	../../gccrs/gcc/rust/rust-session-manager.cc:569
0x8591b08 grs_langhook_parse_file
	../../gccrs/gcc/rust/rust-lang.cc:185
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
compiler exited with status 1
FAIL: rust/compile/feature_extern_types.rs (internal compiler error: Segmentation fault)
FAIL: rust/compile/feature_extern_types.rs  (test for errors, line 2)
FAIL: rust/compile/feature_extern_types.rs (test for excess errors)
```

**Comment by philberty** [comment]
@mxlol233 can you have a look?

**Comment by TuringKi** [comment]
> @TuringKi can you have a look?

sure, i will check it.

**Comment by TuringKi** [comment]
```c++

const char *fmt_str
	    = "%s. see issue %ld "
	      "<https://github.com/rust-lang/rust/issues/%ld> for more "
	      "information. add `#![feature(%s)]` to the crate attributes to "
	      "enable.";
 rust_error_at (loc, fmt_str, error_msg.c_str (), issue, issue,
			 feature.as_string ().c_str ());
```
Maybe the cause root is `%ld` ? 
The type of `issue` is `uint64_t`.  @philberty , how about your idea?

**Comment by TuringKi** [comment]
```c++

const char *fmt_str
	    = "%s. see issue %ld "
	      "<https://github.com/rust-lang/rust/issues/%ld> for more "
	      "information. add `#![feature(%s)]` to the crate attributes to "
	      "enable.";
 rust_error_at (loc, fmt_str, error_msg.c_str (), issue, issue,
			 feature.as_string ().c_str ());
```
Maybe the cause root is `%ld` ? 
The type of `issue` is `uint64_t`.  @philberty , how about your idea?

**Comment by tschwinge** [comment]
Aha, so #1929 commit 9c46a853be4b5a9c2e1b965fa0dcd44beed71924 'Add feature gate definition for `extern_types`' just exposed this, but the underlying issue would be with #1825 commit debb72b0e9cc9ae0cbd151fb809d3f2fda0b4785 'Add feature gate for "rust-intrinsic"'.

Can't we just use plain `unsigned` for `gcc/rust/checks/errors/rust-feature.h`: `Feature::m_issue` and everything that follows from this, and `"%u"` in format strings?  Otherwise, figure out the format string for `uint64_t` in a portable way (`"%" PRIu64`, I think -- but I'm not sure the GCC diagnostics system actually does support that?), or use `unsigned HOST_WIDE_INT` with `"%wu"` format string.  (All untested.)

**Comment by TuringKi** [comment]
> Aha, so #1929 commit 9c46a853be4b5a9c2e1b965fa0dcd44beed71924 'Add feature gate definition for `extern_types`' just exposed this, but the underlying issue would be with #1825 commit debb72b0e9cc9ae0cbd151fb809d3f2fda0b4785 'Add feature gate for "rust-intrinsic"'.
> 
> Can't we just use plain `unsigned` for `gcc/rust/checks/errors/rust-feature.h`: `Feature::m_issue` and everything that follows from this, and `"%u"` in format strings?  Otherwise, figure out the format string for `uint64_t` in a portable way (`"%" PRIu64`, I think -- but I'm not sure the GCC diagnostics system actually does support that?), or use `unsigned HOST_WIDE_INT` with `"%wu"` format string.  (All untested.)
> 

Surely the ci has no reason to complain when we replace `uint64_t` with `uint32_t` :)

But i wonder why 32bit targeting can not handle this situation? 
Since in the codgen level, It's always valid to break a 8 bytes involved instruction into two 4 bytes instructions (with high and low parts).

**Comment by tschwinge** [comment]
The issue (per my understanding) is the following: `uint64_t` is an 8-bytes type.  Your `%ld` format string specifies a `singed long int`, which requires 8-bytes data 64-bit for x86_64 (so "mostly" does match `uint64_t`), but it's a 4-bytes data for 32-bit x86.  If you in the latter case then provide 8-bytes data via `uint64_t` you've got a mismatch, which here results in the SIGSEGV/ICE.

Simply, the format strings and arguments' data types have to match.  :-)


> Surely the ci has no reason to complain when we replace `uint64_t` with `uint32_t` :)

But then use a format string that's correct for `uint32_t`, which `%ld` again isn't generally.

**Comment by TuringKi** [comment]
I am not sure: is changing `lu`  -> `llu` ok?

**Comment by tschwinge** [comment]
No.  In a format string, `%llu` means to expect `long long unsigned` data, and `long long` means 8 bytes *or more*, but provided is `uint64_t`, which means exactly 8 bytes, so that still doesn't match in all system configurations (if `long long` is more than 8 bytes).

Really, why not just `unsigned` and `%u`?
