### ISSUE TITLE
Remove old typecheck dump

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#2020]
This was a bad idea and was used very early on as a debugging tool but its eventually going to be replaced by a decent HIR dump and our logging continues to improve.

Delete https://github.com/Rust-GCC/gccrs/blob/master/gcc/rust/typecheck/rust-tycheck-dump.h

see: https://github.com/Rust-GCC/gccrs/blob/7d38d01886da81d2c38673887dc8802efd0d5432/gcc/rust/rust-session-manager.cc#L972

**Comment by CohenArthur** [comment]
Nice to have you here @adityakode :) Yes, you're right, you'll need to delete that file and modify the file pointed out by Philip which calls into the dump. Feel free to ask for help here or on Zulip if you need!

**Comment by adityakode** [comment]
hi, @CohenArthur  @philberty  I am new to this. 
I deleted the file in my fork but didn't understand the "modifying the file" part, and what to modify with what.
Can you please help me out?

**Comment by CohenArthur** [comment]
@adityakode If you delete the file and try to compile the project again, you'll get errors due to other files still #including rust-tycheck-dump.h. You need to modify those files as well so that the project compiles and passes the testsuite :)

**Comment by TieWay59** [comment]
1. first delete [`rust-tycheck-dump.h`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/rust/typecheck/rust-tycheck-dump.h). This file contains class `TypeResolverDump` and a condition macro `RUST_TYCHECK_DUMP`
2. `TypeResolverDump` is only used in function `Session::dump_type_resolution`

    https://github.com/Rust-GCC/gccrs/blob/c021eef8aa73cc0a3a4e992018cab414a17db4c8/gcc/rust/rust-session-manager.cc#L981-L995

3. `Session::dump_type_resolution` is used by pieces： 
   
    https://github.com/Rust-GCC/gccrs/blob/c021eef8aa73cc0a3a4e992018cab414a17db4c8/gcc/rust/rust-session-manager.cc#L631-L636

   https://github.com/Rust-GCC/gccrs/blob/c021eef8aa73cc0a3a4e992018cab414a17db4c8/gcc/rust/rust-session-manager.h#L376

4. The `if` branch in the `CompileOptions::TYPE_RESOLUTION_DUMP` variable pertains to the `Session::dump_type_resolution` function. Should it be removed,  @CohenArthur ? 

    https://github.com/Rust-GCC/gccrs/blob/c021eef8aa73cc0a3a4e992018cab414a17db4c8/gcc/rust/rust-session-manager.h#L204-L206

    https://github.com/Rust-GCC/gccrs/blob/c021eef8aa73cc0a3a4e992018cab414a17db4c8/gcc/rust/rust-session-manager.h#L263-L266
