### ISSUE TITLE
Delete as_string AST expanded dump

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#2024]
see https://github.com/Rust-GCC/gccrs/blob/7d38d01886da81d2c38673887dc8802efd0d5432/gcc/rust/rust-session-manager.cc#L924

**Comment by TieWay59** [comment]
Hi @philberty, could you provide more details about this issue? Are you suggesting that we delete both the function and every point where it is called? Additionally, I did some research on the repository and found similar work done on https://github.com/Rust-GCC/gccrs/commit/2078d8dd839007c5b4a51639069541269ee2b290.
