### ISSUE TITLE
Bad cast as bool

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#2026]
I tried this code: https://github.com/rust-lang/rust/blob/aa3ca1994904f2e056679fce1f185db8c7ed2703/src/test/ui/cast-as-bool.rs

```rust
fn main() {
    let u = 5 as bool;
  
}
```

I expected to see this happen: 
```
  //~^ ERROR cannot cast as `bool`
```

Instead, this happened: compiled without error

### Meta

- What version of Rust GCC were you using, git sha if possible. be27571c110d99fe55324a9c2b6622787b08fb52

**Comment by emanuele-em** [comment]
Hi! I can fix this bug

**Comment by philberty** [comment]
go for it @emanuele-em feel free to raise a PR you should be able to fix the switch statement in rust-casts.cc
