### ISSUE TITLE
Bad cast as a char

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#2027]
I tried this code: https://github.com/rust-lang/rust/blob/aa3ca1994904f2e056679fce1f185db8c7ed2703/src/test/ui/cast_char.rs

```rust
fn main() {
    const XYZ: char = 0x1F888 as char;
    //~^ ERROR only u8 can be cast into char
    const XY: char = 129160 as char;
    //~^ ERROR only u8 can be cast into char
    const ZYX: char = '\u{01F888}';

}
```

I expected to see this happen: Bad cast into char error

Instead, this happened: compile without error

### Meta

- What version of Rust GCC were you using, git sha if possible. be27571c110d99fe55324a9c2b6622787b08fb52

**Comment by emanuele-em** [comment]
Hi! Please assign this to me, I can handle it! @philberty
