### ISSUE TITLE
Improve error message in operator expression

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#2030]
Tried this test case: https://github.com/rust-lang/rust/blob/aa3ca1994904f2e056679fce1f185db8c7ed2703/src/test/ui/issue-10401.rs

```
fn main() {
    let mut a = "a";
    a += { "b" };
    //~^ ERROR: binary assignment operation `+=` cannot be applied
}
```

We return: https://godbolt.org/z/P9zGT19rs

```
<source>:3:5: error: cannot apply this operator to types & str and & str
    3 |     a += { "b" };
      |     ^
```

**Comment by anuragcs** [comment]
fn main() {
    let mut a = String::from("a");
    a += "b";
}
concatenation (+=) was added from version 1.6 so if you run your program with version 1.6 it will run just fine.

**Comment by CohenArthur** [comment]
@anuragcs `String` and `&str` are different types, so one does have an implementation for the [`AddAssign`](https://doc.rust-lang.org/std/ops/trait.AddAssign.html) trait which allows the `+=` operation, but not `&str`. So the error is still present in modern Rust:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=1c8a3c23539dcee1297e1a12edbdad42

**Comment by anuragcs** [comment]
fn foo() {
    let mut a = String::from("a");
    a += "b";
}

fn bar() {
    let mut a = String::from("a");
    a += "b";
}

**Comment by CohenArthur** [comment]
Yes, the error should not happen when we are seeing a value of type `String`, only a value of type `&str`. So the code you wrote is valid and compiles, but the original code in the issue is invalid and should throw an error - and we want to improve that error message.
