### ISSUE TITLE
Trait fns cannot be const

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#2040]
I tried this code: https://github.com/rust-lang/rust/blob/aa3ca1994904f2e056679fce1f185db8c7ed2703/src/test/ui/const-fn-mismatch.rs

https://godbolt.org/z/ncjKrY4Pf

```rust
trait Foo {
    fn f() -> u32;
}

impl Foo for u32 {
    const fn f() -> u32 { 22 }
    //~^ ERROR trait fns cannot be declared const
}

fn main() { }
```

I expected to see this happen: ERROR trait fns cannot be declared const

Instead, this happened: compiled without error

### Meta

- What version of Rust GCC were you using, git sha if possible. be27571c110d99fe55324a9c2b6622787b08fb52

**Comment by ArberSephirotheca** [comment]
Hi, can I work on this issue?

**Comment by vincenzopalazzo** [comment]
I will work on this this weekend 😸

**Comment by nobel-sh** [comment]
Hey, Is this issue WIP or can I work on this ? I have locally patched this.

**Comment by CohenArthur** [comment]
I think @vincenzopalazzo got busy with other work, so if you have a fix please feel free to open a PR @nobel-sh :)
