### ISSUE TITLE
Remove bad error message

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#2064]
This error diagnostic serves no purpose any more since we have improved the code base over time.

https://github.com/Rust-GCC/gccrs/blob/3eb5dcb67c40a2d26fe05442d1d64dcb3b9d1d09/gcc/rust/typecheck/rust-hir-type-check-expr.cc#L48

**Comment by CohenArthur** [comment]
@TieWay59 I think just removing this line would fix the issue. If you look at the file, it says above that line the following:
```rust
      // FIXME
      // this is an internal error message for debugging and should be removed
      // at some point
```

**Comment by CohenArthur** [comment]
and yeah, I think the commit referencing this issue was an accident :)
