### ISSUE TITLE
Attribute rustc_on_unimplemented

### ISSUE THREAD

**Issue by powerboat9** [Rust-GCC/gccrs#2087]
I tried this code:

```rust
#![feature(rustc_attrs)]

#[rustc_on_unimplemented(
    message = "the size for values of type `{Self}` cannot be known at compilation time",
    label = "doesn't have a size known at compile-time"
)]
trait Foo {}

fn foo<F: Foo>(f: F) {}

fn bar() {
    foo::<i32>()
}
```

I expected to see an error like:
```
error[E0277]: the size for values of type `i32` cannot be known at compilation time
  --> <source>:12:11
   |
12 |     foo::<i32>()
   |           ^^^ doesn't have a size known at compile-time
   |
   = help: the trait `Foo` is not implemented for `i32`
note: required by a bound in `foo`
  --> <source>:9:11
   |
9  | fn foo<F: Foo>(f: F) {}
   |           ^^^ required by this bound in `foo`
```

Instead, this happened:
```
<source>:3:3: error: unknown attribute
    3 | #[rustc_on_unimplemented(
      |   ^~~~~~~~~~~~~~~~~~~~~~
```

### Meta

I tested it on `godbolt.com` GCCRS master, April 3 2023. I can run it locally and obtain a commit hash if necessary.

**Comment by bjorn3** [comment]
This attribute can be implemented as no-op until it is actually used in diagnostics.

**Comment by TieWay59** [comment]
> @CohenArthur  handling the attribute by ignoring it

May I ask where to start? I mean I'm new to this code base, but I think it's a good example for me to read into it. I'd appreciate it if you can spare time to guide me for a little while!

**Comment by CohenArthur** [comment]
@TieWay59 that issue is actually not present anymore in the compiler, and the attribute is ignored for now as we'd like. So I'll close this :)
