### ISSUE TITLE
Can't invoke a 'where F: FnOnce' closure

### ISSUE THREAD

**Issue by bugaevc** [Rust-GCC/gccrs#2106]
I tried this code:

```rust
pub enum Option<T> {
    Some(T),
    None,
}

pub use Option::{Some, None};

#[lang = "fn_once"]
pub trait FnOnce<Args> {
    #[lang = "fn_once_output"]
    type Output;

    extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
}

impl<T> Option<T> {
    pub fn map<R, F>(self, f: F) -> Option<R> where F: FnOnce(T) -> R {
        match self {
            Some(value) => Some(f(value)),
            None => None,
        }
    }
}
```

I expected to see this happen: for this to compile just fine

Instead, this happened:

```
crash2.rs:19:33: error: Failed to resolve expression of function call
   19 |             Some(value) => Some(f(value)),
      |                                 ^
crash2.rs:19:33: error: failed to type resolve expression
crash2.rs:19:33: error: failed to resolve argument type
crash2.rs:18:9: error: expected ‘<tyty::error>’ got ‘Option<T?>’
   18 |         match self {
      |         ^~~~~
   19 |             Some(value) => Some(f(value)),
      |                            ~~~~
   20 |             None => None,
      |                     ~~~~
```

This works differently if the `FnOnce` bound is specified inline and not with `FnOnce`, see https://github.com/Rust-GCC/gccrs/issues/2105. Maybe `where` bounds don't make it into `get_specified_bounds ()`?

https://github.com/Rust-GCC/gccrs/blob/92b137048583c2c22c585097119dba6a5fe06228/gcc/rust/typecheck/rust-hir-type-check-expr.cc#L1766

### Meta

- What version of Rust GCC were you using, git sha if possible. 92b137048583c2c22c585097119dba6a5fe06228

**Comment by powerboat9** [comment]
Reduced down to
```rust
struct Foo(u32);

pub trait Bar {
    fn bar(self);
}

impl Foo {
    pub fn map<F>(f: F) where F: Bar {
        f.bar();
    }
}
```

**Comment by philberty** [comment]
I've been working quite alot behind the scenes here on branches of stuff thats not merged and this issues is now in my path so i am going to take this issue
