### ISSUE TITLE
TestSuite Fail compilation tests are passing when they shouldn't

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#212]
Fail compilation tests are designed to compile some code and test for valid failures such as bad type found and pass only when the compiler fails, if a crash is found it should also fail

I think the test suite is looking for assembly output which is empty but it should fail with the non zero exit code. Any help would be greatly appreciated here.

**Comment by tschwinge** [comment]
@philberty, would you appreciate if I worked through the GCC/Rust testsuite, to change some _local idioms_ into _standard GCC upstream idioms_ -- which I suppose would include addressing the issue raised here?

**Comment by philberty** [comment]
Yes @tschwinge that would be brilliant, I copied from the gdc and go test suites to bootstrap the dejagnu stuff but I don't have much experience with dejagnu so any help would be really appreciated.

I am working on hacking in a basic println and assert_eq macro support so we can write runnable automated tests which would be nice to have soon.

**Comment by YizhePKU** [comment]
I think we can close this issue now.

**Comment by philberty** [comment]
thanks
