### ISSUE TITLE
Handle `#[path]` attributes on modules

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#2127]
This is necessary to properly macro expand the `{u}int_*!` macros defined in libcore 1.49

**Comment by powerboat9** [comment]
I can't replicate this, are you sure it's broken?

**Comment by CohenArthur** [comment]
mh, you're right, maybe I did something wrong. I can't remember exactly what was going on, maybe it was more macro-specific than I thought
