### ISSUE TITLE
Parse ```self``` as ```$_:ident```

### ISSUE THREAD

**Issue by powerboat9** [Rust-GCC/gccrs#2192]
I tried this code:

```rust
macro_rules! foo { ($_:ident) => {} }

pub fn foo() {
    foo!(self);
}
```

I expected to see this happen: no error

Instead, this happened:

```
test.rs:4:5: error: Failed to match any rule within macro
    1 | macro_rules! foo { ($_:ident) => {} }
      | ~~~~~~~~~~~
......
    4 |     foo!(self);
      |     ^~~
```

### Meta

git: ```bb1e40da864addfc2d8dfc310928b7a4e7b13185```

**Comment by matthewjasper** [comment]
`$...:ident` matches all kewords https://doc.rust-lang.org/nightly/reference/macros-by-example.html#metavariables
