### ISSUE TITLE
Describe libgrust/libproc_macro vs. compiler interactions vs. normal runtime library

### ISSUE THREAD

**Issue by tschwinge** [Rust-GCC/gccrs#2193]
I'd greatly benefit from a coherent description of how libgrust/libproc_macro interact with the compiler vs. parts that are a normal host vs. target runtime library (like others in GCC).  Also, any specifics regarding cross compilers.  Accompanied by some paradigmatic Rust code snippets for how to use that.  That shall eventually go into the GCC internals manual, but free-form text is fine for now (text file in the sources repository, or GitHub wiki page?).  That'll help me and later GCC upstream understand what we're doing there.

Some of that has been already been discussed, like in <https://gcc-rust.zulipchat.com/#narrow/stream/266897-general/topic/Start.20of.20libproc.20investigation/near/326852007> and following messages, but needs to be edited and extended.

**Comment by CohenArthur** [comment]
Where should that description reside for now? Within the source somewhere or here in this issue?

**Comment by tschwinge** [comment]
No strong preference, but something that can be collaboratively edited and versioned makes most sense, I think?

> text file in the sources repository, or GitHub wiki page?

**Comment by P-E-P** [comment]
@tschwinge Some details are available [here in the wiki](https://github.com/Rust-GCC/gccrs/wiki/Procedural-macros). Hopefully things are clearly explained. Let me know if you struggle with any part or feel something is missing.
