### ISSUE TITLE
Handle ```$type``` macro parameter

### ISSUE THREAD

**Issue by powerboat9** [Rust-GCC/gccrs#2194]
I tried this code:

```rust
macro_rules! foo {($type:ident) => {
    let $type = 12;
}} 

pub fn foo() {
    foo!(_a);
}
```

I expected to see this happen: no error

Instead, this happened:

```
test.rs:2:10: error: unexpected token in macro transcribe: expected ‘(’ or identifier after ‘$’, got ‘type’
    2 |     let $type = 12;
      |          ^~~~
```

### Meta

git: ```bb1e40da864addfc2d8dfc310928b7a4e7b13185```

**Comment by matthewjasper** [comment]
All keywords except `crate` are allowed for macro parameters: https://doc.rust-lang.org/nightly/reference/macros-by-example.html#macros-by-example
