### ISSUE TITLE
Allow macro repetitions at different levels

### ISSUE THREAD

**Issue by matthewjasper** [Rust-GCC/gccrs#2207]
I tried this code (minimized from libcore):

```rust
macro_rules! different_repetitions {
    ($a:expr, $($b:expr),*) => { $($a + $b;)*; }
}

fn main() {
    different_repetitions!(1, 2, 3, 4);
}
```

I expected to see this happen: Compiles successfully

Instead, this happened: Error:

```text
 error: different amount of matches used in merged repetitions: expected 1, got 3
   29 |     ($a:expr, $($b:expr),*) => { $($a + $b;)*; }
      |                                          ^
```
### Meta

- What version of Rust GCC were you using, git sha if possible.
875cd5ee9c6f037c7f5ace00b75631a1c45970a5

**Comment by CohenArthur** [comment]
@matthewjasper thanks :) do you have the original macro from libcore where you noticed this?

**Comment by CohenArthur** [comment]
For reference this is what `rustc` expands this macro invocation to:

```rust
macro_rules! different_repetitions {
    ($ a : expr, $ ($ b : expr), *) => { $ ($ a + $ b ;) * ; }
}

fn main() { 1 + 2; 1 + 3; 1 + 4; ; }
```

from running `rustc` 1.49 with `-Z unpretty=expanded` on the test case

**Comment by matthewjasper** [comment]
There's a few macros that do this in core. This is one of them: https://github.com/rust-lang/rust/blob/1.49.0/library/core/src/convert/num.rs#L188
