### ISSUE TITLE
Unknown macro with nested macro use modules

### ISSUE THREAD

**Issue by matthewjasper** [Rust-GCC/gccrs#2209]
I tried this code (minimized from core, macro there is called `int_impl`):

```rust
#[macro_use]
mod num {
    #[macro_use]
    mod macros {
        macro_rules! a {
            () => ()
        }

    }

    a!();
}

fn main() -> i32 { 0 }
```

I expected to see this happen: Compiles

Instead, this happened: Error

```text
tmp/num/mod.rs:4:1: error: unknown macro: [a]
    4 | a!();
      | ^
```

### Meta

- What version of Rust GCC were you using, git sha if possible.
875cd5ee9c6f037c7f5ace00b75631a1c45970a5

**Comment by CohenArthur** [comment]
Ah, the issue comes from the order of operations in `accumulate_escaped_macros` - basically visiting the invocation before we visit the "declaration" which was brought in scope by `#[macro_use]`.
