### ISSUE TITLE
Macros error on match count mismatch too eagerly

### ISSUE THREAD

**Issue by matthewjasper** [Rust-GCC/gccrs#2229]
I tried this code (minimized from core, https://github.com/rust-lang/rust/blob/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ptr/mod.rs#L1468):

```rust
macro_rules! fnptr_impls_args {
    ($($Arg: ident),+) => {};
    () => {};
}

fnptr_impls_args! {}
fnptr_impls_args! { A }
```

I expected to see this happen: no error

Instead, this happened: 

```text
<source>:86:21: error: invalid amount of matches for macro invocation. Expected between 1 and +inf, got 0
   86 |     ($($Arg: ident),+) => {};
      |
```

### Meta

- What version of Rust GCC were you using, git sha if possible.
gccrs (Compiler-Explorer-Build-gcc-c7b7e297ea4b688ef9fb51a8aee2a8b2af39ac1c-binutils-2.40) 13.0.1 20230417 (experimental)

**Comment by CohenArthur** [comment]
Ah, I see the issue - we shouldn't be matching the first arm but the second one which has no tokens. This wouldn't be a problem if both macro match arms were switched around. This might be a bug in us emitting errors too eagerly but matching the macro properly - I'll have a look.
