### ISSUE TITLE
Macro-expanded macro definitions are not resolved

### ISSUE THREAD

**Issue by matthewjasper** [Rust-GCC/gccrs#2233]
I tried this code:

```rust
macro_rules! one {
    () => {
        macro_rules! two {
            () => {
                
            }
        }
    }
}

one!();
two!();
```

I expected to see this happen: compiles

Instead, this happened:

```text
<source>:12:1: error: unknown macro: [two]
   12 | two!();
      | ^~~
```

### Meta

- What version of Rust GCC were you using, git sha if possible.
gccrs (Compiler-Explorer-Build-gcc-c7b7e297ea4b688ef9fb51a8aee2a8b2af39ac1c-binutils-2.40) 13.0.1 20230417 (experimental)

**Comment by CohenArthur** [comment]
https://github.com/rust-lang/rfcs/pull/1560#issuecomment-217683514

```rust
mod a {
    macro_rules! m { () => {
        macro_rules! m { () => {
            fn f() {}
        } }
    } }
}
mod b {
    use a::*;
    c::m! {} // If we expand this first, it would resolve to `a::m!` and then
             // `b::m!` would expand to `fn f() {}`, ensuring correctness.
}
mod c {
    use a::*;
    b::m! {} // If we expand this first, it would resolve to `a::m!` and then
             // `c::m!` would expand to `fn f() {}`, ensuring correctness.
}
```

One way to go about it is to run the Early name resolver and expander in a fixed point, and store errors in a container instead of emitting them immediately. Then, once the fixed point is reached, emit the errors if there are any
