### ISSUE TITLE
Cannot parse statement after curly bracket macro invocation

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#2239]
I tried this code:

```rust
macro_rules! unroll {
    {} => {}
}

pub fn foo() {
    let mut _a = 14;
    unroll! {}
    let mut _b = 13;
}
```

minimized from `verify_512_helper` in `libcore 1.49` (`library/stdarch/crates/core_arch/src/x86/avx512vpclmulqdq.rs`)

I expected to see this happen: no error
Instead, this happened: 

```rust
minimized.rs:8:5: error: expecting ‘}’ but ‘let’ found
    8 |     let mut _b = 13;
      |     ^~~
minimized.rs:8:5: error: error may be from having an expression (as opposed to statement) in the body of the function but not last
```

### Meta

- What version of Rust GCC were you using, git sha if possible.

058682f736b

**Comment by matthewjasper** [comment]
#2206 left a bunch of cases with macros not correctly implemented. I'll try to get a follow up for those cases soon.

**Comment by CohenArthur** [comment]
@matthewjasper yes, that could be a proper fix but it would require a *lot* of changes in our AST. We haven't made those changes yet and are instead working around our AST issues (https://github.com/Rust-GCC/gccrs/pull/2156 could have been fixed by having blocks only contain statements, for example) in various ways. I don't think the AST changes are really worth it, and I suspect that this issue can get fixed quite easily without doing those changes
