### ISSUE TITLE
`rust-macro-invoc-lexer.cc` is missing license header

### ISSUE THREAD

**Issue by P-E-P** [Rust-GCC/gccrs#2250]
The [file](https://github.com/Rust-GCC/gccrs/blob/master/gcc/rust/expand/rust-macro-invoc-lexer.cc) is missing a license header.

I believe the author @CohenArthur should add it to prevent any legal issue ?

**Comment by philberty** [comment]
https://github.com/Rust-GCC/gccrs/blob/master/gcc/rust/expand/rust-macro-substitute-ctx.cc is missing too
