### ISSUE TITLE
Special case lang item's path when performing name resolution

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#2263]
Raise an issue about the whole path to the lang item stuff because there is overlap with what I am doing there too

_Originally posted by @philberty in https://github.com/Rust-GCC/gccrs/pull/2256#discussion_r1213319341_
            
            
This is also present in other species. We need to be able to link back to a lang item's definition.

**Comment by philberty** [comment]
Assigning to both of us as i have code relating to the HIR here but not happy to raise a PR yet

**Comment by CohenArthur** [comment]
Closed by #3290
