### ISSUE TITLE
Macro Expansion Producing Expression with Semicolon

### ISSUE THREAD

**Issue by powerboat9** [Rust-GCC/gccrs#2273]
I tried this code:

```rust
macro_rules! mac {
    () => {return 1;}
}

pub fn foo() -> i32 {
    mac!()
}
```

I expected to see this happen:
```
warning: trailing semicolon in macro used in expression position
 --> src/lib.rs:2:20
  |
2 |     () => {return 1;}
  |                    ^
...
6 |     mac!()
  |     ------ in this macro invocation
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, [see issue #79813 <https://github.com/rust-lang/rust/issues/79813>](https://github.com/rust-lang/rust/issues/79813)
  = note: macro invocations at the end of a block are treated as expressions
  = note: to ignore the value produced by the macro, add a semicolon after the invocation of `mac`
  = note: `#[warn(semicolon_in_expressions_from_macros)]` on by default
  = note: this warning originates in the macro `mac` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Instead, this happened:
```
test.rs:2:20: error: tokens here and after are unparsed
    2 |     () => {return 1;}
      |                    ^
```

### Meta

- git sha: ```1b322540fa0fce561cf86e371dd7f304f1343511```

**Comment by CohenArthur** [comment]
What's interesting is that we do already have the proper expansion behavior described in https://github.com/rust-lang/rust/issues/79813 haha, especially in https://github.com/rust-lang/rust/issues/79813#issuecomment-893023453

We should fix this, add a note referencing the issue, and watch for the Rust version at which point this becomes a hard error (which from what I'm understanding will be the first version offering Rust Edition 2024?)

**Comment by powerboat9** [comment]
https://github.com/rust-lang/rust/commit/5d26145dee8c58cf3b973a8337d6b771f5f66cd8

**Comment by CohenArthur** [comment]
We need to eventually look at handling things like `#[warn(semicolon_in_expressions_from_macros)]` too. This issue could be a good testing ground for adding that feature
