### ISSUE TITLE
Move ast collector template implementation to header file. 

### ISSUE THREAD

**Issue by P-E-P** [Rust-GCC/gccrs#2278]
Some templated implementation are left in [`gcc/rust/ast/rust-ast-collector.cc`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/rust/ast/rust-ast-collector.cc#L53). Those should be moved to their header file in order to avoid future link problems.

**Comment by TieWay59** [comment]
I have no clue what's going on because when I tried to move the functions, the compiler asked for no extra qualification. Should I remove `TokenCollector::` after this?

```log
../../gccrs/gcc/rust/ast/rust-ast-collector.h:49:8: error: extra qualification ‘Rust::AST::TokenCollector::’ on member ‘visit_items_joined_by_separator’ [-fpermissive]
   49 |   void TokenCollector::visit_items_joined_by_separator (T &collection,
      |        ^~~~~~~~~~~~~~
../../gccrs/gcc/rust/ast/rust-ast-collector.h:70:8: error: extra qualification ‘Rust::AST::TokenCollector::’ on member ‘visit_as_line’ [-fpermissive]
   70 |   void TokenCollector::visit_as_line (T &item, std::vector<TokenPtr> trailing)
      |        ^~~~~~~~~~~~~~
```

**Comment by P-E-P** [comment]
> Hello @P-E-P, let me make sure of the details. Do you mean to move these five templated implementations to their header file `rust-ast-collector.h`? I have searched through the file and I saw only five of them.

Yes, we had some problem in the past with templating in cc file at link time, that's why we want to move them to the headers in order to avoid those kind of problems in the future. Usually I would do some templating file included in the header (`.hxx`) but I would like to avoid big differences with the rest of the codebase.

**Comment by P-E-P** [comment]
> I have no clue what's going on because when I tried to move the functions, the compiler asked for no extra qualification. Should I remove `TokenCollector::` after this?
> 
> ```
> ../../gccrs/gcc/rust/ast/rust-ast-collector.h:49:8: error: extra qualification ‘Rust::AST::TokenCollector::’ on member ‘visit_items_joined_by_separator’ [-fpermissive]
>    49 |   void TokenCollector::visit_items_joined_by_separator (T &collection,
>       |        ^~~~~~~~~~~~~~
> ../../gccrs/gcc/rust/ast/rust-ast-collector.h:70:8: error: extra qualification ‘Rust::AST::TokenCollector::’ on member ‘visit_as_line’ [-fpermissive]
>    70 |   void TokenCollector::visit_as_line (T &item, std::vector<TokenPtr> trailing)
>       |        ^~~~~~~~~~~~~~
> ```
> 

That's because your functions are already in `TokenCollector` [class scope](https://en.cppreference.com/w/cpp/language/scope), no need to specify it again.

> UPD: After I remove the qualification, the moved templates can't be matched correctly. I don't know why.
> 
> ```
> ../../gccrs/gcc/rust/ast/rust-ast-collector.cc:2589:35: error: no matching function for call to ‘Rust::AST::TokenCollector::visit_items_joined_by_separator(std::vector<std::unique_ptr<Rust::AST::Pattern> >&, Rust::TokenId)’
>  2589 |   visit_items_joined_by_separator (pattern.get_alts (), PIPE);
>       |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
I miss some informations here, usually the compiler includes the different match attempts it has tried.

**Comment by TieWay59** [comment]
Thank you @P-E-P, I have taken a while to understand the  [class scope](https://en.cppreference.com/w/cpp/language/scope) of this file, here is what works for me:

```cpp
// in rust-ast-collector.h
namespace Rust {
namespace AST {

class TokenCollector : public ASTVisitor 
{
} // end of TokenCollector

// I move the ast collector template implementation here without changing any details.
// They are outside of the TokenCollector` scope so I kept the qualification.

// TokenCollector::visit
// TokenCollector::visit_items_joined_by_separator
// TokenCollector::visit_as_line
// TokenCollector::visit_items_as_lines
// TokenCollector::visit_items_as_block

}
}
```
This change has passed compilation and check-rust. What do you think? Does this pattern meet the goal? I would appreciate your advice.

If everything looks good, I will proceed with creating a pull request for my changes.

**Comment by P-E-P** [comment]
> Thank you @P-E-P, I have taken a while to understand the [class scope](https://en.cppreference.com/w/cpp/language/scope) of this file, here is what works for me:
> 
> ```c++
> // in rust-ast-collector.h
> namespace Rust {
> namespace AST {
> 
> class TokenCollector : public ASTVisitor 
> {
> } // end of TokenCollector
> 
> // I move the ast collector template implementation here without changing any details.
> // They are outside of the TokenCollector` scope so I kept the qualification.
> 
> // TokenCollector::visit
> // TokenCollector::visit_items_joined_by_separator
> // TokenCollector::visit_as_line
> // TokenCollector::visit_items_as_lines
> // TokenCollector::visit_items_as_block
> 
> }
> }
> ```
> 
> This change has passed compilation and check-rust. What do you think? Does this pattern meet the goal? I would appreciate your advice.
Not exactly, whilst it do work, it is really non standard practice to do so. You seemed you had gone in the right direction with your update, the "new" error you got seemed unrelated to your previous scope problem, I would have prefered this version (with the error fix though! ).

This error:
```
../../gccrs/gcc/rust/ast/rust-ast-collector.cc:2589:35: error: no matching function for call to ‘Rust::AST::TokenCollector::visit_items_joined_by_separator(std::vector<std::unique_ptr<Rust::AST::Pattern> >&, Rust::TokenId)’
 2589 |   visit_items_joined_by_separator (pattern.get_alts (), PIPE);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
reveals the compiler (not the linker) does not know about one version of the function, either because no function exists or because some steps during the monomorphization failed. Would you have a link to the branch containing that code so I could take a look at it ?

> If everything looks good, I will proceed with creating a pull request for my changes.
Why don't you use the already opened one ? Closing and reopening PRs creates "noise", if someone searches for your problem or your fix in the future he will be overwhelmed by all those PRs, furthermore it helps keeping all comments and thoughts about one subject in one same place.

**Comment by P-E-P** [comment]
Also, @TieWay59 why don't you use the code in this PR ? https://github.com/Rust-GCC/gccrs/pull/2286/files what is wrong with it ?

**Comment by TieWay59** [comment]
@P-E-P
> Why don't you use the already opened one ?

I thought that would cause a lot waste of CI time, and I believe I‘m in the right direction.

> why don't you use the code in this PR ?

I apologize for not noticing that PR earlier. I mistakenly only saw the closed one. It was my mistake, and I'm truly sorry. I had some ideas, but upon further reflection, I realized they do not align with standard practices. Thank you for enlightening me and sharing your knowledge. I will leave this issue as it is since it is still a work in progress.  : )

**Comment by P-E-P** [comment]
> I thought that would cause a lot waste of CI time, and I believe I‘m in the right direction.
Don't bother with CI time, as an open source project we do have almost infinite CI credits.

> I apologize for not noticing that PR earlier. I mistakenly only saw the closed one. It was my mistake, and I'm truly sorry. I had some ideas, but upon further reflection, I realized they do not align with standard practices. Thank you for enlightening me and sharing your knowledge. I will leave this issue as it is since it is still a work in progress. : )

No need to apologize, you did absolutely nothing wrong. Also my turn to apologize, I though that was your PR, both your profile pictures are kinda yellow-ish and I assumed that was your PR, hence why I was confused, I was wondering why you didn't simply reuse your code, now it makes sense.

I'm a bit saddened by the fact you invested all this time and efforts into an issue that has (almost) already a fix. This whole situation would have been clearer if we had assigned this issue correctly in the first place.
