### ISSUE TITLE
Remove operators.h

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#228]
This should break down into 2 seperate changes.

1: Where we get rid of the HIR enums for HIR::ArithmeticOrLogicalExpr::ExprType, AST::LazyBooleanExpr::ExprType and HIR::NegationExpr::NegationType and reuse the AST version of the enum as there is no conversion required so having duplicate enums is just messy here.
2. remove operators.h and adjust rust-gcc.cc to reuse the AST mappings to covert to the GCC Tree operators.

**Comment by YizhePKU** [comment]
I feel like duplicated enums are just part of a bigger problem. The `ast/` directory and `hir/` directory almost mirrors each other, e.g. `ast/rust-expr.h` and `hir/tree/rust-hir-expr.h`. A lot of code is spent converting AST types to their corresponding HIR types. Is there a better way to do this?

By the way, I'm confused that there's a `HIR:WhileLoopExpr` when [the guide](https://rustc-dev-guide.rust-lang.org/lowering.html) says that `while` loops are converted to `loop` when lowering.

**Comment by SimplyTheOther** [comment]
> 
> 
> The `ast/` directory and `hir/` directory almost mirrors each other, e.g. `ast/rust-expr.h` and `hir/tree/rust-hir-expr.h`. 

I imagine this will change in the future as the HIR becomes more similar to rustc's HIR and less similar to the AST, such as by lowering the different types of loops to one type, as you mentioned. Similarly, I think `if let` expressions might be lowered to `match` expressions as well, or something like that.

**Comment by YizhePKU** [comment]
An alternative would be to keep `operator.h` and remove all the other enums. This has several advantages:

1. It can be shared by AST and HIR, which removes duplication without tying HIR to AST's representation
2. It's centralized and easy to extend later

Plus, it's how the Go developers chose to represent their operators. Surely they know what they're doing:)

Of course the contents of `operator.h` needs to be modified, probably by extracting values from all the other enums. Also It'll be nice to put it inside a namespace.

**Comment by philberty** [comment]
Yeah it was bootstrapped from the AST over time this will be more and more like rustc HIR. The goal here is to have an immutable IR where they have their own NodeMappings for AST NodeId, HidID, LocalDefId and DefID, CrateNum etc.

Currently, there is an open ticket #69 where we need to remove the macro trees so, over time the IR will be simplified from the AST limiting more and more what the static analysis needs to care about. Even compound assignment expressions are lowered into an assignment with variable reference and expression to avoid that.

**Comment by philberty** [comment]
> An alternative would be to keep `operator.h` and remove all the other enums. This has several advantages:
> 
>     1. It can be shared by AST and HIR, which removes duplication without tying HIR to AST's representation
> 
>     2. It's centralized and easy to extend later
> 
> 
> Plus, it's how the Go developers chose to represent their operators. Surely they know what they're doing:)
> 
> Of course the contents of `operator.h` needs to be modified, probably by extracting values from all the other enums. Also It'll be nice to put it inside a namespace.

No, I don't think we can do that the operators.h has a go license header on it, I used it as a way to bootstrap the front-end in the short term. Ian created this abstraction over the GCC Generic trees which made the go front-end independent of GCC its a long term goal of mine for this compiler to make it independent of GCC.

I think the best way to fix this is to get rid of the HIR duplicated enums for

- ArithmeticOrLogicalExpr
- ComparisonExpr
- LazyBooleanExpr
- NegationExpr

So for the first commit, you should simply change the code to get rid of the HIR versions of these. Then HIR code just reuses AST namespace versions.

The 2nd commit is more complicated, the rust-backend.h and rust-gcc.cc there will need to be some work to reuse these AST namespace enums: 

See https://github.com/Rust-GCC/gccrs/blob/27df0c9f959ef7ec537d6b2b7725443a6b2bd94f/gcc/rust/backend/rust-compile-expr.h#L342

every binary expression is is handled in one function which has some shared logic in there ideally we should make the existing binary_expression function private and take enum tree_code for the operator. Then we have 4 new functions:

Bexpression *
Gcc_backend::arithmetic_binary_expression (AST::ArithmeticOrLogicalExpr op, Bexpression *left,
				Bexpression *right, Location location)

Bexpression *
Gcc_backend::comparison_binary_expression (AST::ComparisonExpr op, Bexpression *left,
				Bexpression *right, Location location)

Bexpression *
Gcc_backend::boolean_binary_expression (AST::LazyBooleanExpr op, Bexpression *left,
				Bexpression *right, Location location)

And we change the existing unary_expression:

Bexpression *
Gcc_backend::unary_expression (AST::NegationExpr op, Bexpression *expr,
			       Location location)

**Comment by YizhePKU** [comment]
I'm afraid I'm not exactly convinced.

First of all, I don't think license is a problem. We can rewrite `operator.h` from scratch(and we probably will). Moreover, BSD license allows modification as long as we keep the license header intact.

---

Then let's compare the two proposals. 

* Proposal A: Keep the 4 enums in AST and remove the rest.
* Proposal B: Keep the 1 enum in `operator.h` and remove the rest.

So the real questions are:
* Do we put them in the AST namespace or in the global namespace?
* Do we put them in a single enum or split them into 4?

My answers are:
* We put them in the global namespace because they're accessed from AST and HIR alike. No reason to prefer one over another.
* We put them in a single enum because it simplifies things. Splitting values into 4 enums comes with the technical difficulty that, since we can't refer to the operator type as one, we have to write 4 copies of everything that uses operator, as you have suggested.

**Comment by philberty** [comment]
To me, it is important that we follow the rust reference on this https://doc.rust-lang.org/reference/expressions/operator-expr.html it keeps the operators for each of the specific types of operator expression separated.

It simplifies what cases we need to care about when we parse an arithmetic operation or if we are looking at a lazy boolean operation for example. More granularity is a good thing for compilers. It might seem like more code but when it comes to static analysis having a global enum for everything is harder to manage as each of the operator expression have a much bigger switch statement to handle then.

In the end, we will always end up with a minimum 2 enums for this, GCC generics tree_code and AST enum.

**Comment by SimplyTheOther** [comment]
>

>     * We put them in the global namespace because they're accessed from AST and HIR alike. No reason to prefer one over another.

>

I agree with this, although we may want to consider using `enum class` if we do so to prevent any namespace collisions between enums. Conceptually the operator kind does not belong more or less to the AST or the HIR, so a shared space would be best. 

> 
>
>     * We put them in a single enum because it simplifies things. Splitting values into 4 enums comes with the technical difficulty that, since we can't refer to the operator type as one, we have to write 4 copies of everything that uses operator, as you have suggested.
>
>

I don't agree with this. I think the four different operators are conceptually distinct:

- ArithmeticOrLogicalExpr takes two numbers and outputs a number
- ComparisonExpr takes two numbers (or other types, I suppose) and outputs a boolean
- LazyBooleanExpr takes two booleans and outputs a boolean, but has the unique property of lazily evaluating them
- NegationExpr takes one argument and outputs an argument

As such, I think that they are best implemented by treating them differently. In my opinion, the compiler data structures should be created to enforce to the maximum possible extent the syntactical and semantic rules of the language, and treating all four of those different types of operators as a single OperatorExpr would not do that. There's also the issue that compiler routines such as type inference would be made more complex if the operators were all merged into one.

**Comment by YizhePKU** [comment]
All right, so the consensus seems to be that we keep the 4 operator types distinct, but move them into the global namespace. I'll work on it.

About namespace: `enum class` is added in C++11, so we can't use that. However we can get similar result [by putting an enum inside an empty struct](https://stackoverflow.com/a/14988178).

**Comment by philberty** [comment]
> All right, so the consensus seems to be that we keep the 4 operator types distinct, but move them into the global namespace. I'll work on it.
> 
> About namespacing the enum: `enum class` is added in C++11, so we can't use that. However we can get similar result [by putting an enum inside an empty struct](https://stackoverflow.com/a/14988178).

Awesome.

We can use c++11 but it's up to you I don't really have any opinion on how you implement the enum. Thanks

**Comment by SimplyTheOther** [comment]
> 
> About namespacing the enum: `enum class` is added in C++11, so we can't use that. However we can get similar result [by putting an enum inside an empty struct](https://stackoverflow.com/a/14988178).

The [next major release of GCC (GCC 11) will be written (at least partially) in C++11](https://gcc.gnu.org/pipermail/gcc/2019-December/231063.html), so we can use C++11 features since GCC won't make a major change like adding a new frontend before a major release. Also, the current Rust-GCC codebase makes extensive use of C++11 features like `unique_ptr` and move semantics.

**Comment by YizhePKU** [comment]
I noticed that for lazy boolean operators, we use tree_type of the rhs operand.

```
// rust-gcc.cc
// Gcc_backend::binary_expression

bool use_left_type = op != OPERATOR_OROR && op != OPERATOR_ANDAND;
tree type_tree
  = use_left_type ? TREE_TYPE (left_tree) : TREE_TYPE (right_tree);
```

However, the [Rust reference](https://doc.rust-lang.org/reference/expressions/operator-expr.html#lazy-boolean-operators) says that lazy boolean operators can only be applied to boolean types. So we can simply assign it `boolean_type_node` right?
