### ISSUE TITLE
Add comparator to new AST identifier

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#2354]
To take advantage of the new Identifier class we should add a comparator to the identifer so it can be used in std::set and std::map.

```c++
bool operator< (const Identifier& rhs) const {
  return identifier.compare (rhs.identifier);
}
```

https://github.com/Rust-GCC/gccrs/blob/251348f3c8bc218360877a3bb9f16d9d5c7a685f/gcc/rust/ast/rust-ast.h#L35

**Comment by powerboat9** [comment]
Could instances of ```Identifier``` be ordered by their ```node_id```?

**Comment by philberty** [comment]
Good point maybe we have comparators one for just string because you want to look for duplicate names. One for node Id . The general case we will care about is likely duplicate names.

**Comment by powerboat9** [comment]
Why would we need a ```set<Identifier>``` or a ```map<Identifier, T>``` anyways? Wouldn't we only want to store the ```string``` or ```NodeId``` depending on circumstance?

**Comment by CohenArthur** [comment]
I could see some instance where a `set<Identifier>` would be useful, for proc macro name resolution for example. So I think it's fine to add the behavior. We can always remove it in the future if we find it too bloated.

**Comment by philberty** [comment]
This is no longer required with the latest changes
