### ISSUE TITLE
Unnecessary (?) ```TREE_SIDE_EFFECTS``` and ```TREE_READONLY``` usage

### ISSUE THREAD

**Issue by powerboat9** [Rust-GCC/gccrs#2357]
https://github.com/Rust-GCC/gccrs/blob/cfc51d46fcdb70bde84f030557c96866f3b18e23/gcc/rust/rust-gcc.cc#L1491-L1493

**Comment by philberty** [comment]
Worth double checking this, we had issues with other intrinsics getting optimized away when we compile with all the torture options.

**Comment by CohenArthur** [comment]
These two lines were needed when I added them at least, not sure if that has changed since. The abort calls were being optimized away otherwise.

**Comment by CohenArthur** [comment]
I think fixing this issue will be pretty simple - we can just remove those two lines and run the testsuite, which should fail if those lines where necessary. I've marked the issue as `good-first-pr`
