### ISSUE TITLE
Unnecessary "empty token vector" ```FIXME```

### ISSUE THREAD

**Issue by powerboat9** [Rust-GCC/gccrs#2358]
https://github.com/Rust-GCC/gccrs/blob/cfc51d46fcdb70bde84f030557c96866f3b18e23/gcc/rust/expand/rust-macro-builtins.cc#L580-L581

There are a few more ```FIXME``` comments similar to the above in the same file

**Comment by rizan21** [comment]
Hey @CohenArthur, can I clean this up?

**Comment by powerboat9** [comment]
I'm alright with it, but @CohenArthur might have more details à la Chesterton's Fence

**Comment by rizan21** [comment]
Sure, I'll wait for his response

**Comment by CohenArthur** [comment]
@rizan21 sure, go ahead! I've assigned the issue to you :)

**Comment by rizan21** [comment]
Hey, @CohenArthur, Ive started a PR #2644, Please review

**Comment by officialhemant511** [comment]
return AST::Fragment(node, std::move(str_tok));

By removing the curly braces around node and std::move(str_tok), the arguments will be passed properly to the AST::Fragment constructor

**Comment by CohenArthur** [comment]
Closed by #2644
