### ISSUE TITLE
Resolve type path error

### ISSUE THREAD

**Issue by MahadMuhammad** [Rust-GCC/gccrs#2375]
### I tried this code:
- You can view the same on [compiler-explorer](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DEArgoKkl9ZATwDKjdAGFUtEywYgATKUcAZPAZMADl3ACNMYgkAZlIAB1QFQjsGFzcPb3jE5IEAoNCWCKiuWKtMGxShAiZiAjT3Tx8yioEqmoI8kPDImMtq2vqMpv6OwK7CnpKASktUE2Jkdg4AUi9osDBlgFYAITFaVAB3CBMGM0x0Ke2AEWWNAEEqBgBqFiZAiCnn5YB2Hbv7gRiO8CM8ACrAwjfP4A55w55PBGoVAQVYANisVC%2BAFpltFsM8hJhaFRnocEJFMITiVQQIS8AAvC54/4PX63NkPRHmJi2ZAAfX4qDxTjBIAhIO%2BXh232iADEhIzmfiIGE6eiwV9fqz7uyAQDEegAJ7MFh4AVhGoQJjqrxo40vCWELUwh7w548vmC5HWq5sn4c3UBjgzWicLa8TwcLSkVCcABKZlBCjmCypq2iPFIBE0IZmAGtvD8AHTRO3RSTRaIADhK1Z%2BW0kW30nEkkdzsc4vAUIA02dzMzgsBgiBQqBYcTokXIlDQE6nUWAyGQxAU2IUzDiCgQqAsWAAbubMAA1PCYQ4AeTijE4WZotAIkR7qo7YUCNSNt94b%2BYxCNF7CbRyhzbheDnNhBAvBhaE/aNeCwMITGAJx9h7UDSCwN4jHEOCMLwYhgLwfdMDQmNMFUcoTEfL9yEEYkO1oPAwmBP8XCwDsgTwFgvxmKgDGABRT3PK8b3Q/hBBEMR2CkGRBEUFR1Fw3QuH0QxjCTfQmJ7SAZlQOJbAENDeFQYjiGIPAsG0qBTXYC4cgYUh9zEEwli8DQvB4KYZmaAzPAgRxBk8FT/DGAoij0BIkl8wKIuyXzOjCyZLGJQjWhGGKVJ8yoRgS7pij6doMoK2pcomYpvNTRYJFDcN21wuMOGeVRqzRbE0UkZ4AHEnCceMhGeCBut6/q3nMSIvggXBCBIKVMymXgQK0LzSELLY%2BzDDg21IbjJAATmLastjRDyuDRaI0Q0Q7drRUgoxjBru17fs4MHEcICQOYCDiKiZwgOdJ3oYhglYJZTHMZBni4Ys0WrYsyPwIhzPQPRxOEURxBk1H5LUDtlNIQ5gTiHiWw4CNbo7BqLyo77QVQUlmta9qup6vqBqG1nRsfYgJpcedAdmrh5uepaas23huLW4spGiH5q2rc7ol2qQNGkO7jK7SwnsWvMVpACs4a4FXqz2rwfiVxXdpJ6I6vujXtde%2BAh1Hf6F1%2Bl3AZAYgpF2vsDyPITL2vKM7zoLnnzVXCfw/Gio7/ACgJsGjwMYAgoJgjsEKQlDaFoNCs0wtScJjfACIqYjSN4cjKOo9DAkfDaY0Y5iPzYpYY047jQN4/jBLPQPRLvWRJIx6QsaUHGlMyAwjE9jSm6s3T9JSIzY1MpGSPgbyUpaPyAtcBo9BC/I8tiqKUiKyL7NK8LMu33y2gGfeMlv6x75y0KT8y9Kn6C4rRmPsq1VZjzCqoLEmZM1adkamDAgEMoZ7ThgNKaiMBZC3tjMCkTAsBRE%2BLrQ261WzixAGtcm9UNY9j7PbUgTt3ogE%2BjTN244AaRGBmwTgDM2odXZv1QaLMRpMDGtzSuCMSAWRRkPdG0lR6yGxopGMugfAEyYETLu4Cbbqw4FTL6VFnh02eDAuBxYEEaAGrzZhxBZpeDQQODBmAsE9FwYWfBJMtoSz7JAh6mtKE2N1jWaGZ0uA/FOj7NEu1jbSA2tbUhtsOALR8RtLw6ioFxJejMUySR7CSCAA%3D%3D)
- Code tested from [E0038](https://doc.rust-lang.org/error_codes/E0038.html)

```rust
#![allow(unused)]
fn main() {
trait Trait {
    fn foo(&self) -> Self where Self: Sized;
}

fn static_foo<T:Trait + ?Sized>(b: &T) {
}

fn dynamic_bar(a: &dyn Trait) {
    static_foo(a)
}
}
```

### I expected to see this happen: 
- Compiled Successfully, like rustc-1.49:

### Instead, this happened: *explanation*
```rust
➜  gccrs-build gcc/crab1 -frust-incomplete-and-experimental-compiler-do-not-use ../mahad-testsuite/E0038.rs                                        
../mahad-testsuite/E0038.rs:4:39: error: failed to resolve TypePath: Sized in this scope
    4 |     fn foo(&self) -> Self where Self: Sized;
      |                                       ^~~~~
../mahad-testsuite/E0038.rs:7:26: error: failed to resolve TypePath: Sized in this scope
    7 | fn static_foo<T:Trait + ?Sized>(b: &T) {
      |                          ^~~~~

Analyzing compilation unit

Time variable                                   usr           sys          wall           GGC
 TOTAL                              :   0.00          0.00          0.00          146k
Extra diagnostic checks enabled; compiler may run slowly.
Configure with --enable-checking=release to disable checks.
```
### Meta

- What version of Rust GCC were you using, git sha 5406b633a1f5e6e3ae8da02589adf4ea003dec12.

**Comment by MahadMuhammad** [comment]
<details><summary> Same error </summary>
<p>

- Same error from [`E0072`](https://doc.rust-lang.org/error_codes/E0072.html):
   - On [`godbolt`](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DEArgoKkl9ZATwDKjdAGFUtEywYgATKUcAZPAZMADl3ACNMYhAATlIAB1QFQjsGFzcPb3jE5IEAoNCWCKjYq0wbFKECJmICNPdPH1LygUrqgjyQ8MiYyyqauozGvvbAzsLu6IBKS1QTYmR2DgB6JYBqBAICOIUQFfRUZAA6U3MAWgMjQ5JgJcjiEgB9NCwFJewNDQB2L0ONlloAKQaACCAK8AGYwGAAQBWABCYloqAA7hATAwzJh0JNYQARIHAqgMVYsJiBCCTVYAz5wgnmUw2VYBczBDCYKk0gmrbnrTBMdAgVYmAAcpC5PKqdEFAHk4rYBADwU5mQRWVhFdhSKsVqs7iRBQxUKtAvhiGV5cSEJF2QojXgWAkFEkwvRVkRxTzPV7vT7tWsfWgHSYCOyCFa3QBPOKYMAcBSrJIAL0wBOp%2BJBaY401onBhvE8HC0pFQnAASmYCAnZvN2WDwTxSARNFnpgBrbwANkOkg0wuiXC8XGFwu%2Bwo7opzHEk%2Bebxc4vB2GkbzemcFgMEQKFQDrokXIlEDcV3UWAyGQxAUpwUzG2CFQFiwADc8AsAGp4TDI2WMTgNmi0EML0oMJZzCQJqgjX9eDA5hiAjaUwm0c0oNIQM2EEaUGFoSDC14LAwhMYAnERHZuDwzBSSMcRcNIU1zTwR9MFIotMFUMpg0WBtAhDSci1oPAwmICCXCwWcCGIe0oOmKgDGABR30/b8Cz/WQRDEdgpBkQRFBUdQaN0Lh9EMYwK30ASdkgaZUDlFJSN4VBGOICSXngCBmDYEAsRyBhSEfMQTEWLwNEHFtLEwawLQcBhnFceo9H8UYCiKPRHW8gZPEM1KLQ6JLukMpoLVafpYoyfLwvolphhyroony4Z0r0cw2mq8ZaumW05gWCRs1zGcaJLDhVlUMdTg7SRVgAcScJxSyEVYICmma5tJcxIkpCBcEIEgqQhLhJl4JtcMmNsQBhJdJ2nUgWBASRokOYUYQ7QcuA7cEO17GFog7UgCyLAaFxAJdDq0VcNwgJBZi2YN9wgQ9j2CVhFhOAhkFWLhDnHQ4WPwIhnL0fhBDU8RNIJ%2BQlDUWcDNIZEhLiKT9F6n7ZwG6VgziYNVlQKghpGsbJum2b5sWwWVsA9aXB3ehiB2%2Bt9uXI6eqnXhrrOw4pHBT5hze8F%2Bx7aRfvs%2BdLEB%2BWQZO8EYUOcFno%2BftPkkesXoZjhwT6v6jeBrNSDXKAwaQOGpZhgPumIKRoiXJ8X0wBSv2jZTeH/QCdggECaJgiCUPTuCEKQmwULQxgCEw7DZ3wwjiNoWhSIbLBKOAaiizo8pGOY3hWPYkMUO48LZ34wThLZMSJOusjpNk%2BSP1jn8yK04RRGJ6RSZ0in9MyC4TPMMywgsilixsgQ7OLRznKY%2BB2vK5pPAgRwGsMhL8hqlLsgtW%2BsiSbLEsfsqIoqeqSoysKP9KrNU/q1Rqf90gAKajUFqyU9ozE6hpRWeYmb9U4KsZGqN0a3SxvNTauMZZ7QOiuaYVp%2BTdF3u2LgHxnaXRVkuA2c4OAAyBiub2fsQCQ3ZhYCgsNtxHilgjDyHBhodlGuNYWc0FoC2WkwVaxA5ZeVxngAUhlSZEw0ovWQy89JFl0D4GmTA6aj2digxhLM2Ycy5hgisWDux3Q0PNCWAjIgyy8HLT2x1SBkKwFEShEgaEXWVqdBhzMjaLlNqFds4JhSHC8B2aI0Qxx9hiT2TSk5XaoPdswyJXjJxeDdobHJnjpiOSSPYSQQA%3D%3D%3D)
```rust
// https://doc.rust-lang.org/error_codes/E0072.html
#![allow(unused)]
fn main() {
struct ListNode {
    head: u8,
    tail: Option<ListNode>, // error: no indirection here so impossible to
                            //        compute the type's size
}
}
```

</p>
</details>

**Comment by philberty** [comment]
This is missing the sized trait definition in gccrs we don't compile libcore yet so the test case is missing:

```
#[lang = "sized"]
pub trait Sized {}
```

when this is added we still get an issue:

```
test.rs:13:16: error: expected ‘& <tyty::error>’ got ‘& dyn [Trait<Self>]’
   10 | fn static_foo<T: Trait + ?Sized>(b: &T) {}
      |                                  ~
......
   13 |     static_foo(a)
      |                ^
      ```
