### ISSUE TITLE
Fatal Error: used more than once - [E0062]

### ISSUE THREAD

**Issue by MahadMuhammad** [Rust-GCC/gccrs#2381]
# Fatal Error - `used more than once`
-  Fixing this error will improve gccrs to emit error codes similiar to rustc.
- You can view the same on [compiler-explorer](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DEArgoKkl9ZATwDKjdAGFUtEywYgATKUcAZPAZMADl3ACNMYgkNUgAHVAVCOwYXNw9vOISkgQCg0JYIqK4Yq0wbZKECJmICVPdPH1LygUrqglyQ8MjoyyqauvTGvvbAzoLu4oBKS1QTYmR2DnNTGwBqADFUVFWAUgB2ACEdjQBBVfPV9VW8AGYfY5P9gBEHh6oGVZYmQIhJ3cOHhdVvQCJddjcnhstv8jqcgfCEZcQKsYoDEeirjFVgB6bGrSLEEjImiYWjoXYANg0qh2VNWCliZTwJPJLBImFWBAQhlWAgWaPR52eOxusMeeyeHGmtE4AFZeJ4OFpSKhOAAlMyghSzeYcnZeG48UgETRS6YAa28AA4AHR7ClWjReDQATgpLqtstl0hlHEkCtNKs4vAUIBiJqVUtIcFgMEQKFQLFidEi5EoaCTKaiwGQyGICgAtApmLEFAhUBYsAA3PALABqeEwAHcAPKMxVGmi0AiRUMQMKBsKBaoAT04RqHzGII5bYW0ZQjRozbEELYYtDHkdIWDCJmATjEtFD3F4WC%2BRnEW/wxAXeCrmGPyswqjKJh7494gR7vuVtDwYWIUcXCwQMCGIPAWA/aYqAMYAFAbZs20YD8ZEEEQxHYKRUPkJQ1EDXQuH0QxjE1fR/1DSBplQWJbAEY9eFQe9iHArAKKgZg2BATB8FohhSCrMQTEWZ0vB4SZpiaXiHAYZxXHqCRZV8GSOnyQo9HiRJeIGTwuEUjTsgYFSuiKSxSVvFphm0hTTOsXjWhqIzxhM8w2is3TejaRy1K4CSdQWCRpTlAMt1VDhLitCkCwpSRVgAcScJw1SEVYIHixLkq%2BcxIj%2BCBcEIEhdgNHzeAjLRxNIS1ZRiX1/VISDJBdG1PQpUSuApG4qU9N1SEVZVQpDMNjVNaYY3jWYCFiN80wgDNk3oYhglYRZTHMZBVi4G0HRtJ8eJIPB0D0fg0NEcQsKOnCVHULcCNIJtANiKD9CCnrA1Cls30m0FUCocLIuiuKEqSlK0qBzKe2IHKXEzebCsNSYSuGwK/V4SCqptKQbj2K0rQ6m4XSkDRpF6hjg0sQbSrNCrvEaq02tlLhMYpKQKT2SRJCtJ6OBuYK%2BtJimRrjUaICQWas2m0X5pAYgpBdGJq1rTAENbdsUK7cG%2BwHLdJ1HFDtenWd5xsFDl0YAg1w3QMdz3A9aCPFCz2Iy9lWvW970fXhn1fd8T3IQRSUDP8AKAjBFmVMCIMemCmDgpWkI7XhzvQ07pHOxRLvwjIDCMKXSMDtiqJo5J6JVJiWIfeAJLM5pPAgRw3KU9AvImTJNOSev9N4pvnKruzLLk9JCMkiphi7vQXP6fudI8hzRlUiZfLmfyfM5%2BUXpCzhVhWgg1o2hrtpSvKiGIWHiqGyNyoQTAmCwKJfip4pqs4WrUZiYmgw4Abw2G6NBaQcbPvFomOakRFqcQ4KoCKUUYog2SqlQGGUmBZQhh7XaLFDqyCTphFOsg054WuhkO6TAHoniRqvN%2Bb0Ppvl5D9LeO8bR7w0ClKGwDj76juPDM%2BZVpiX2vt0O%2BloH6c2fiAKqa9eYfzJl/c%2BFoQCSF3rpSQFJZReAdCzPYDNObczESTCR/MkZeB5johG0j%2BK9mSLIoAA%3D)

---
## I tried this code from [E0062](https://doc.rust-lang.org/error_codes/E0062.html):

```rust
struct Foo {
    x: i32,
}

fn main() {
    let x = Foo {
                x: 0,
                x: 0, // error: field `x` specified more than once
            };
}
```
---
## I expected to see this happen: 
- Give error like rustc 
```rust
error[E0062]: field `x` specified more than once
 --> <source>:8:17
  |
7 |                 x: 0,
  |                 ---- first use of `x`
8 |                 x: 0, // error: field `x` specified more than once
  |                 ^ used more than once

error: aborting due to previous error

For more information about this error, try `rustc --explain E0062`.
Compiler returned: 1
```
---
### Instead, this happened: 
- It gives fatal error
```rust
<source>:8:17: fatal error: used more than once
    8 |                 x: 0, // error: field `x` specified more than once
      |                 ^
compilation terminated.
Compiler returned: 1
```
---
### Meta

- What version of Rust GCC were you using, git sha 5406b633a1f5e6e3ae8da02589adf4ea003dec12.
- Godbolt version : `gccrs (Compiler-Explorer-Build-gcc-2f91d511200bf85558c9013b09a458c06edd1e02-binutils-2.40) 13.0.1 20230417 (experimental)`
---

**Comment by robertgoss** [comment]
Would it be ok for me to pick this up?
