### ISSUE TITLE
No fields in initializer - Internal compiler error

### ISSUE THREAD

**Issue by MahadMuhammad** [Rust-GCC/gccrs#2389]
## No fields in initializer - Internal compiler error - [`E0063`](https://doc.rust-lang.org/error_codes/E0063.html)
- Fixing this issue, help https://github.com/Rust-GCC/gccrs/pull/2387 to emit more user friendly error code and error emission similiar to rustc.
- You can view the same on [`compiler-explorer`](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DEArgoKkl9ZATwDKjdAGFUtEywYgATKUcAZPAZMADl3ACNMYhAATlIAB1QFQjsGFzcPb3jE5IEAoNCWCKjYq0wbFKECJmICNPdPH1LygUrqgjyQ8MiYyyqauozGvvbAzsLu6IBKS1QTYmR2DgB6JYBqBAICOIUQFfRUZAA6U3MAWgMjQ5JgJcjiEgB9NCwFJewNDQA2AGZDjZZaABSDQAQXMphsqwAYqhUKtAQB2ABCwJBq3Rq3Uqzw3x8qIxqwAniBsbjSKjEQARCmgqgMVYsJiBCCTeHI/EY%2BgETHw76U6GwtlItnU77ClarO4kEnBOFQvCYWjoCkIykcaa0TgAVl4ng4WlIqE4ACUzNyFLN5ph4V5vjxSARNOrpgBrbySQ4/aJagAcXw0Xh9Pq80Vimo4kl1TsNnF4Ow0Dqd0zgsBgiBQqBYcTokXIlDQWZzUWAyGQxAUpwUzG2CFQFiwADc8AsAGoKgDuAHk4oxOPaaLQCJEdhAwtGwoFqsTuLwJ8xiITO2FtGVHTPSAW2IJOwxaNODVgwiZgE4xLQduusIyjOJ9bx8MRV3gG5gLwbMKoyiYh33eIEh%2BGBq0HgYTEFOLhYNGBDEHgLC/tMVAGMAChtpgXY9nq/ayCIYjsFIMiCIoKjqHepC6Fw%2BiGMYZr6CBOyQNMqBxLYAgXrwqAvsQMEvPAEDMGwICYPgLEMKQDZiCYixeAGPCTNMTQiQ4DDOK49R6P4owFEUegJEkIkDJ4FG6TkDAdFp3QUQpFTDAZehWS0wxmV0USWTZqkZK5bROeMLnyZaCwSBq2pRqRRocJiPqfKcnySKsADiThOMaQirBACVJSljLmJErIQLghAkDadqTLwa5aHJpBulqCbhpGpBwZI0SHD6WqfF4XBcD8nwaC10SfKQeoGmFcYgAmZXqqQKbprMWzfnmEAFtm9DEMErCLCcBDIKsXCej6hzvsJJB4Ogej8IIOHiPhZ3yEoajRuRpDtmBcTwfowUDdGYWdt%2BcTfqsqBUBFUUxfFiXJal6Xg1lQ7ELlLiFstRVcCViZ3hVtW8HB1WHFI3wIkG3xelIGjSIN7GxpYo2o%2BVrogN8vzRJIjVapIXCBpI3zRJFb0cN8IVDRT43JmmU0QEgi1FvNEvLSAxBSNECaNs2mCoehvbrgOMMjmOpFzlOv6kHrC5LiuNgG5ujAEDue7Roex6nrQ54G1eVG3geeCPuUL5vrwH5fj%2B67/oq0bAaB4EYIsBrQbBr2IUwyGq926tYedoiXdI11EXdpG6D4FzUeYtFhPRLKGsxKRsYanHca%2B8DyYqT72BAji2RRGn5M5OnZPp7mGVkekpN52mWQ3zQMK0/S93Zo8iRPIwdz5dluekffmF5mmd8jMxzAFW/hjqH2hZwqwbVtO2NftqX5UQxBIyjQvTAgmBMFgUSl26XAfDzdVYwmZMxhwEaY0kyTRFkgGav0LAUAWpmJakRVoCQ4KoSK0VYqQxSmlMGmUmDZVhr7Q63FTrYTTnhDOsgs4kQNLnR6z1Xr735uTDg31ZrcgBifM0Z9DgXw0KleGcDb6AltF4e%2BSZH7P1fpQWmn8aqcB/iAaqh8BaAMpsAtGtNWZcK4CzT4WovCfEigiBEXBvg8z5ooxhpVRE8y8AwgBli1FiWHCkEAkggA%3D%3D)

---
### I tried the modified code from [`E0063`](https://doc.rust-lang.org/error_codes/E0063.html): 
- No field in initializer
```rust
// https://doc.rust-lang.org/error_codes/E0063.html
struct Foo {
    x: i32,
    y: i32,
}

fn main() {
    let x = Foo { }; // error: No Field
}
```

---

### I expected to see this happen: 
- Emit error message, similiar to rustc .i.e.,
   - emit the name of `initializer` & `field`
- Error message emitted by rustc:
```rust
missing fields `x`, `y` in initializer of `Foo`
``` 

---

### Instead, this happened:
- Internal Compile Error.
- This is the output of gccrs:

```rust
➜  gccrs-build gcc/crab1 /home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/missing_constructor_fields.rs
crab1: internal compiler error: in visit, at rust/backend/rust-compile-expr.cc:405
0x7bd9e5 Rust::Compile::CompileExpr::visit(Rust::HIR::StructExprStruct&)
	../../gccrs/gcc/rust/backend/rust-compile-expr.cc:405
0xc63414 Rust::Compile::CompileExpr::Compile(Rust::HIR::Expr*, Rust::Compile::Context*)
	../../gccrs/gcc/rust/backend/rust-compile-expr.cc:45
0xc62286 Rust::Compile::CompileStmt::visit(Rust::HIR::LetStmt&)
	../../gccrs/gcc/rust/backend/rust-compile-stmt.cc:63
0xc62421 Rust::Compile::CompileStmt::Compile(Rust::HIR::Stmt*, Rust::Compile::Context*)
	../../gccrs/gcc/rust/backend/rust-compile-stmt.cc:34
0xc8a79b Rust::Compile::HIRCompileBase::compile_function_body(tree_node*, Rust::HIR::BlockExpr&, Rust::TyTy::BaseType*)
	../../gccrs/gcc/rust/backend/rust-compile-base.cc:476
0xc8c84e Rust::Compile::HIRCompileBase::compile_function(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Rust::HIR::SelfParam&, std::vector<Rust::HIR::FunctionParam, std::allocator<Rust::HIR::FunctionParam> >&, Rust::HIR::FunctionQualifiers const&, Rust::HIR::Visibility&, std::vector<Rust::AST::Attribute, std::allocator<Rust::AST::Attribute> >&, Location, Rust::HIR::BlockExpr*, Rust::Resolver::CanonicalPath const*, Rust::TyTy::FnType*)
	../../gccrs/gcc/rust/backend/rust-compile-base.cc:643
0xc6176e Rust::Compile::CompileItem::visit(Rust::HIR::Function&)
	../../gccrs/gcc/rust/backend/rust-compile-item.cc:181
0xa73659 Rust::Compile::CompileItem::compile(Rust::HIR::Item*, Rust::Compile::Context*, Rust::TyTy::BaseType*, bool, Location)
	../../gccrs/gcc/rust/backend/rust-compile-item.h:38
0xa73659 Rust::Compile::CompileCrate::go()
	../../gccrs/gcc/rust/backend/rust-compile.cc:47
0xa736a8 Rust::Compile::CompileCrate::Compile(Rust::HIR::Crate&, Rust::Compile::Context*)
	../../gccrs/gcc/rust/backend/rust-compile.cc:40
0xa6ec6a Rust::Session::compile_crate(char const*)
	../../gccrs/gcc/rust/rust-session-manager.cc:653
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
```

--- 
### Meta

- What version of Rust GCC were you using, git sha 543780374c097734308d03e6f1f861213d48402d.
- gccrs (Compiler-Explorer-Build-gcc-2f91d511200bf85558c9013b09a458c06edd1e02-binutils-2.40) 13.0.1 20230417 (experimental)
---

**Comment by philberty** [comment]
I'm going to open this up for good-first-PR its a fairly nice one to sink your teeth into.

**Comment by robertgoss** [comment]
Hi I would like to pick this up if that is ok.
