### ISSUE TITLE
Invalid use of empty vector

### ISSUE THREAD

**Issue by dkm** [Rust-GCC/gccrs#2421]
Enabling libstdc++ assertions shows an invalid use of empty vector:

https://github.com/Rust-GCC/gccrs/blob/b75357f4a1835dcd288df67402340b4cb6b96c12/gcc/rust/expand/rust-macro-builtins.cc#L572

Only 2 tests blowup:
rust/compile/builtin_macro_include_str_location_info.rs
rust/compile/issue-1830_str.rs

on the same assertion:

```
1325   │ 0x7fc7b822b471 __GI_abort
1326   │     ./stdlib/abort.c:79
1327   │ 0x21120a3 std::vector<unsigned char, std::allocator<unsigned char> >::operator[](unsigned long)
1328   │     /usr/include/c++/12/bits/stl_vector.h:1123
1329   │ 0x210d685 Rust::MacroBuiltin::include_str_handler(unsigned int, Rust::AST::MacroInvocData&)
1330   │     ../../gcc/rust/expand/rust-macro-builtins.cc:572
```

This patch fixes the issue, but I'll let @philberty decide:

```diff
diff --git a/gcc/rust/expand/rust-macro-builtins.cc b/gcc/rust/expand/rust-macro-builtins.cc
index 0423e516997..d06056b0134 100644
--- a/gcc/rust/expand/rust-macro-builtins.cc
+++ b/gcc/rust/expand/rust-macro-builtins.cc
@@ -565,7 +565,7 @@ MacroBuiltin::include_str_handler (Location invoc_locus,
     }
 
   std::string str;
-  if (expect_single)
+  if (expect_single || bytes.empty ())
     rust_error_at (invoc_locus, "%s was not a valid utf-8 file",
                   target_filename.c_str ());
   else
```

**Comment by dkm** [comment]
Maybe that's more for @CohenArthur

**Comment by CohenArthur** [comment]
The patch looks good to me @dkm! Can you post a PR and I'll review it tomorrow? I'm leaving work right now haha

**Comment by powerboat9** [comment]
It looks like [```vector::data```](https://en.cppreference.com/w/cpp/container/vector/data) might be a good replacement for taking the address of the first element.

**Comment by philberty** [comment]
@dkm another good find thats a horrible hack I've used in another project to get a string but we should probably see if there's a better way to get the data pointer.

Is even using a std::string safer than using std::vector then building it all up

**Comment by philberty** [comment]
definetly that fix you mention should go in
