### ISSUE TITLE
Neither tuple struct nor a tuple variant was used as a pattern - Internal Compiler Error

### ISSUE THREAD

**Issue by MahadMuhammad** [Rust-GCC/gccrs#2430]
## Neither tuple struct nor a tuple variant was used as a pattern  - [`E0164`](https://doc.rust-lang.org/error_codes/E0164.html)

- Fixing this issue, help `gccrs` to emit error code [`E0164`](https://doc.rust-lang.org/error_codes/E0164.html) similiar to rustc.
- You can view the same on [`compiler-explorer`](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DEArgoKkl9ZATwDKjdAGFUtEywYgATKUcAZPAZMADl3ACNMYgkATlIAB1QFQjsGFzcPb3jE5IEAoNCWCKiuWKtMGxShAiZiAjT3Tx8yioEqmoI8kPDImMtq2vqMpv6OwK7CnpKASktUE2Jkdg4AemWAagQCAjiFEFX0VGQAOlNzAFoDIyOSYGXI4hIAfTQsBWXsDS4ANkkjzZZaABSDQAQUBXgAzGAwICAKwAITEtFQAHcICYGGZMOgpnCACLAkFUBhrFhMQIQKZrQEAdnhhMY7jWIOpdMJaw5a3hpHZnKcPNBtIJgtBeBYcVozNZ9NBnLWxLWQTRVNp9JpwrB6sJhIVYRq1FQqBAzJVbNlnLJBGQCHlhulvLlHJBIBASsp1IhBIh2DWlNIa1Wa3uJGhDsdjw9Xp9qqFYdjgq1CbxHBmtE4sN4ng4WlIRo4ACUzAQ1go5gtMNTITxSARNCmZgBrby/aI0iEaDSw1uwiFfAAcNK8sP0nEkmbruc4vF2GhrdZmcFgMEQKFQ4rokXIlDQ6/oUWAyGQxAUZwUzB2CFQFiwADc8IsAGp4TAogDycUYnGrNFoBEiuwgMIJzCQIagATy/XgQOYYgwNfMJtHKWtuF4Hc2EEV8GFoCDs14LAwhMYAnCRXYUNILAySMcRcPIvBiCQvAb0wUic0wVRyhMP9IPIQRMDTGjaDwMJiHAlwsAnAhiDFSCZioAxgAUJ8X3fT8yP4QQRDEdgpBkQRFBUdQaN0Lh9EMYwi30ITdkgGZUDiWwBFI3hUCY4gpNeeAIGYNgQGxHIGFIG8xBMJYvA0LweCmGZmgczwIEcQZPBM/wxgKIo9ASJJYsSjLslizo0smSw%2BIY1oRhykyYsqEYCu6Yo%2BnaCqGtqWqJmKaKy0WCRU3TccaLzNZVD7L4zh%2BNYAHEnCcfMhF9SbptmslzEiKkIFwQgSErCEuCmXhkK0KLSCbWFZ34sdSBYEBJGiI4%2B1hL4Iu%2BXsNDu6IvlILMczzacQFnfaU1IRcVzmbZOK3CAdziDdiGCVgllOK01i4I5%2ByOVj8CIdy9HU4RRHEHScf0tQJ2M0gUREuIZJHDgMw%2Bic81fTi4k4tZUCoQbhtGyQJqmma5t5xamGW4hVpcXdIi2na9vnHqOHOy6TqOKQIRpPs%2B17CFoikDRpE%2B5yp0sX651ww6my8GklckCL%2By8L4aUke3JDu6mIT6r6Df%2BhdlyBiAkEh6Hwf9vcQGIKRolnW970wJS3w/LNvzoP9j0oICaOg8DuPT2D4MQmxuLQxgCEw7CJ3wwjiNoWhSOrCizOonN8HoiomJY3g2I4riyMCP9%2BJzQThNEjAlhzSTpJQ2T5MU59Y9U79ZE0/HpEJpRiaMzJLnM8xLLCay/Ts2KnNzVz3OY%2BBopKlo4oS1wGj0FL8jq3KspSJrMv81r0sqi/YraAYb4yL%2B1gf41VSo/Sq5V/5JWaqMB%2BbVuqzHmF1Ha1NaZ60nBwNYCNkBIyONdNGvp1qY0lrtY2B0ZgIEwEwLAUQ/RNi4B2am8sQAnTpv1A2M5SEAx9kgEGzMLAUAhmuKGe5YY%2BQ4ENEaY15p8wgNIwWwsSF%2BUxngdA2N55420kvWQRNDI5l0D4cmTBKbjxQW7fWHBGag2LGzTBRZsHIzwRoX0YthES3BBCLwJDPbkModQygjYJAMLOrwBWs40HfUNn9GWR1vAQiOBCdskgISwhKMkrWA4XZmPQdLE2gNvbez9kIgOAig49FDjSBhkdHzTxUvHXgP4k4AVTjmLOOFqytJzkhfOa50JFywjhBumACJERItxWuVFh54TogxFuE527IE4ksas3c%2BITn7iJWCYlJk1ikpdExckmAKRjrU7iOMF6aN0vIFeuidAgAhKZIwIcLL913rZeyKRD4uXuCo0%2BNlipAJSA4BgzhIF32BR/Iqb9sqgpMlClIEL6pVTKo1GF/zSoMF/jA8Yn9oFNXMO0BF8DSyIO0rLVB9NOC2PMPYo4FT8FrQxptdxUtOGHQoVQnotDmxHFhLCJJ4d7rJJ%2BH2aIfZGEhOYWEilHAfpRNydwkAvCwYlKKSIuGnAsE4McW3RlWMTJnI0RILRelrkkzuWTCmVN%2BLkrYRYpmLMbGauRnSpxEAXHQy2hCLx0T2V%2BL9MEi6krWHuxlZE1lASvC/F5fyzsXwhVO1FZk4N5iclkOpl4LJETvGBX/ICyQQA)

---

### I tried this code from [`E0164`](https://doc.rust-lang.org/error_codes/E0164.html):

```rust
// https://doc.rust-lang.org/error_codes/E0164.html
#![allow(unused)]
fn main() {
enum A {
    B,
    C,
}

impl A {
    fn new() {}
}

fn bar(foo: A) {
    match foo {
        A::new() => (), // error!
        _ => {}
    }
}
}
```

--- 

### I expected to see this happen: 
- Give error like rustc i.e.,
```bash
➜  mahad-testsuite rustc E0164.rs 
error[E0164]: expected tuple struct or tuple variant, found associated function `A::new`
  --> E0164.rs:14:9
   |
14 |         A::new() => (), // error!
   |         ^^^^^^^^ `fn` calls are not allowed in patterns
   |
   = help: for more information, visit https://doc.rust-lang.org/book/ch18-00-patterns.html

error: aborting due to previous error

For more information about this error, try `rustc --explain E0164`.
```

---

### Instead, this happened: 
- gccrs gives internal compile error.
- Here is the backtrace of gccrs.
```bash
➜  mahad-testsuite ../gccrs-build/gcc/crab1 E0164.rs                                                                                   
crab1: internal compiler error: in get_items, at rust/ast/rust-pattern.h:1182
0x7b8896 Rust::AST::TupleStructPattern::get_items()
	../../gccrs/gcc/rust/ast/rust-pattern.h:1182
0x7b8896 Rust::AST::TupleStructPattern::get_items()
	../../gccrs/gcc/rust/ast/rust-pattern.h:1180
0x7b8896 Rust::Resolver::EarlyNameResolver::visit(Rust::AST::TupleStructPattern&)
	../../gccrs/gcc/rust/resolve/rust-early-name-resolver.cc:1108
0xb9d650 operator()
	../../gccrs/gcc/rust/resolve/rust-early-name-resolver.cc:561
0xb9d650 __invoke_impl<void, Rust::Resolver::EarlyNameResolver::visit(Rust::AST::MatchExpr&)::<lambda()>::<lambda()>&>
	/usr/include/c++/11/bits/invoke.h:61
0xb9d650 __invoke_r<void, Rust::Resolver::EarlyNameResolver::visit(Rust::AST::MatchExpr&)::<lambda()>::<lambda()>&>
	/usr/include/c++/11/bits/invoke.h:111
0xb9d650 _M_invoke
	/usr/include/c++/11/bits/std_function.h:290
0xb9c6e2 std::function<void ()>::operator()() const
	/usr/include/c++/11/bits/std_function.h:590
0xb9c6e2 Rust::Resolver::EarlyNameResolver::scoped(unsigned int, std::function<void ()>)
	../../gccrs/gcc/rust/resolve/rust-early-name-resolver.h:50
0xb9c6e2 operator()
	../../gccrs/gcc/rust/resolve/rust-early-name-resolver.cc:556
0xb9c6e2 __invoke_impl<void, Rust::Resolver::EarlyNameResolver::visit(Rust::AST::MatchExpr&)::<lambda()>&>
	/usr/include/c++/11/bits/invoke.h:61
0xb9c6e2 __invoke_r<void, Rust::Resolver::EarlyNameResolver::visit(Rust::AST::MatchExpr&)::<lambda()>&>
	/usr/include/c++/11/bits/invoke.h:111
0xb9c6e2 _M_invoke
	/usr/include/c++/11/bits/std_function.h:290
0xb9ce9a std::function<void ()>::operator()() const
	/usr/include/c++/11/bits/std_function.h:590
0xb9ce9a Rust::Resolver::EarlyNameResolver::scoped(unsigned int, std::function<void ()>)
	../../gccrs/gcc/rust/resolve/rust-early-name-resolver.h:50
0xb9ce9a Rust::Resolver::EarlyNameResolver::visit(Rust::AST::MatchExpr&)
	../../gccrs/gcc/rust/resolve/rust-early-name-resolver.cc:553
0xb9ca80 std::function<void ()>::operator()() const
	/usr/include/c++/11/bits/std_function.h:590
0xb9ca80 Rust::Resolver::EarlyNameResolver::scoped(unsigned int, std::function<void ()>)
	../../gccrs/gcc/rust/resolve/rust-early-name-resolver.h:50
0xb9ca80 Rust::Resolver::EarlyNameResolver::visit(Rust::AST::BlockExpr&)
	../../gccrs/gcc/rust/resolve/rust-early-name-resolver.cc:408
0xb9af61 operator()
	../../gccrs/gcc/rust/resolve/rust-early-name-resolver.cc:410
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
```

---

### Meta

- What version of Rust GCC were you using, git [`sha`](https://github.com/Rust-GCC/gccrs/tree/866512cbc09bc883ef844b2b6cb70a72335756a7) 866512cbc09bc883ef844b2b6cb70a72335756a7
- Compiler-Explorer version => gccrs (Compiler-Explorer-Build-gcc-a06cec181de6398231e0662c1ed83d905ad6d1d9-binutils-2.40) 13.0.1 20230417 (experimental)

---

**Comment by philberty** [comment]
There is an assertion in the get_items within the AST we should remove. @dkm has a fix for this in the HIR
