### ISSUE TITLE
Handle macro invocations expanding to new macro definitions

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#2516]
https://github.com/rust-lang/rfcs/pull/1560#issuecomment-217683514

```rust
mod a {
    macro_rules! m { () => {
        macro_rules! m { () => {
            fn f() {}
        } }
    } }
}
mod b {
    use a::*;
    c::m! {} // If we expand this first, it would resolve to `a::m!` and then
             // `b::m!` would expand to `fn f() {}`, ensuring correctness.
}
mod c {
    use a::*;
    b::m! {} // If we expand this first, it would resolve to `a::m!` and then
             // `c::m!` would expand to `fn f() {}`, ensuring correctness.
}
```

One way to go about it is to run the Early name resolver and expander in a fixed point, and store errors in a container instead of emitting them immediately. Then, once the fixed point is reached, emit the errors if there are any

**Comment by matthewjasper** [comment]
cc #2233

**Comment by CohenArthur** [comment]
uh, yeah, not sure why I didn't add this issue's testcase to your issue! thank you @matthewjasper I'll close this
