### ISSUE TITLE
Remove TyTy::UnitType

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#252]
> so rustc probably used a zero-element tuple as the unit type?

Indeed: https://github.com/rust-lang/rust/blob/f1c47c79fe8438ed241630f885797eebef3a6cab/compiler/rustc_middle/src/ty/sty.rs#L1676-L1681

_Originally posted by @bjorn3 in https://github.com/Rust-GCC/gccrs/issues/238#issuecomment-779841432_

**Comment by philberty** [comment]
marking this as a good first project though I think there might be some dragons here.

**Comment by dkm** [comment]
I'm trying to resolve this issue, hope to have something to push shortly :)

**Comment by philberty** [comment]
Good luck this will in the end fix #155 which i never finished. I think you might find some issues with GCC it does not have support for zero sized types. So there needs to be care in the Gimple code generation to not emit any expressions using it since it is simply void.

**Comment by dkm** [comment]
In fact, I tried the naive approach of removing it and see what breaks. And after patching all errors, it seems to work. At least, all tests are passing. I still have to really understand all the parts so I may have overlooked something, but haven't had any problems.

**Comment by philberty** [comment]
Nice work thanks for working on it. Since this is a bigger piece of code being changed I think this will be the right time to remind you about FSF copyright assignments btw. If its something in progress we can probably merge because it allows for past and future PRs.

**Comment by dkm** [comment]
The FSF documents are already in the process of being signed, but still on my side, so better wait for them to be transmitted to the FSF before merging. I hope it's only a matter of days now.

**Comment by philberty** [comment]
Yeah, as soon as you send them back I can merge. Really great work though :D I hope it was an enjoyable process at least. Doing that change i think you will have got a good feel for where things are going on in the code i will mark more issues for good first PR.

**Comment by dkm** [comment]
Yes, it was really enjoyable. In particular because the task was not too complex for someone still not used to the code base. Feel free to add more simple PR, I'll pick some gladly :D
