### ISSUE TITLE
Verify type checking of if-statement conditions

### ISSUE THREAD

**Issue by powerboat9** [Rust-GCC/gccrs#2598]
LGTM i wonder if it is infact a coercion/cast-site in rustc for this case lets go with unify for now

_Originally posted by @philberty in https://github.com/Rust-GCC/gccrs/pull/2596#pullrequestreview-1608388320_

**Comment by tamaroning** [comment]
it seems that if-conditions are unification cites. coercions do not happen here.
https://rust-lang.github.io/rfcs/0401-coercions.html#coercions
