### ISSUE TITLE
hir_id duplicated between different nodes

### ISSUE THREAD

**Issue by YizhePKU** [Rust-GCC/gccrs#265]
From `rust-ast-lower-expr.h:508`. Notice that the same `mapping` is used for both `operator_expr` and `translated`, which means they get the same hir_id. Is that OK?

```Rust
    auto crate_num = mappings->get_current_crate ();
    Analysis::NodeMapping mapping (crate_num, expr.get_node_id (),
				   mappings->get_next_hir_id (crate_num),
				   UNKNOWN_LOCAL_DEFID);
    HIR::Expr *operator_expr
      = new HIR::ArithmeticOrLogicalExpr (mapping, asignee_expr->clone_expr (),
					  std::unique_ptr<HIR::Expr> (value),
					  op, expr.get_locus ());
    translated
      = new HIR::AssignmentExpr (mapping,
				 std::unique_ptr<HIR::Expr> (asignee_expr),
				 std::unique_ptr<HIR::Expr> (operator_expr),
				 expr.get_locus ());
```

**Comment by philberty** [comment]
good find, I think we should probably give this a separate id for translated. They will both resolve to the same NodeId though.  We get away with this here because this is just turning += into an assignment to an arithmetic operation.

**Comment by philberty** [comment]
This was duplicated since we desugarded the HIR for compound assignment expressions into the expressions and an assignment. We have now reverted this which means we no longer have this duplication.

[#compount](https://github.com/Rust-GCC/gccrs/commit/a7fb60bb626f7b936bf117636db777a5f0df30c9)
