### ISSUE TITLE
Fail to parse async function

### ISSUE THREAD

**Issue by P-E-P** [Rust-GCC/gccrs#2650]
GCCRS fails to parse an async function

I tried this code:

```rust
pub async fn a() -> u32 {
    1
}
```

I expected to see this happen: Compile correctly

Instead, this happened: 
```
./test.rs:1:5: error: failed to parse item in crate
    1 | pub async fn a() -> u32 {
      |     ^~~~~
```

### Meta

[007166c](https://github.com/Rust-GCC/gccrs/commit/007166ca6ceecd429f7033336af25dd679424ca2)

**Comment by mvvsmk** [comment]
Hey , @P-E-P could you assign this to me, I'll start working on it. :)

**Comment by officialhemant511** [comment]
i think GCCRS is a tool that aims to provide compatibility with the C language and may not support all Rust language features, such as async/await. Therefore, if you're trying to use async/await in your code, GCCRS may not be the appropriate tool for that specific task.i think we work with c code here...

**Comment by P-E-P** [comment]
> i think GCCRS is a tool that aims to provide compatibility with the C language and may not support all Rust language features, such as async/await. Therefore, if you're trying to use async/await in your code, GCCRS may not be the appropriate tool for that specific task.i think we work with c code here...

We're trying to support rust version 1.49 for now. Async/await syntax were introduced in version 1.38 of the language, this means we should support those. Even if asynchronous code may not be the highest priority, this issue reduce the gap between rust and our parser. This is mandatory to be able to parse all rustc's test suite, we're only a few percentage away.

**Comment by P-E-P** [comment]
@mvvsmk have you made any progress so far ? I think we'll need this earlier than expected as I'm working on AST validation. If you feel you won't be able to work on this soon I could reassign the issue, don't put any pressure on yourself or anything.

Also if you need any help to solve this, tell me.

**Comment by mvvsmk** [comment]
Hey @P-E-P ,  I made the changes two weeks ago and forgot to make a PR. Apologies for the delay; it completely slipped my mind, been a bit busy last month. I have made the PR now. Could you code review my PR, if I missed something do let me know.
