### ISSUE TITLE
Tuple index not parsed correctly

### ISSUE THREAD

**Issue by P-E-P** [Rust-GCC/gccrs#2659]
GCCRS finds a float literal instead of a tuple index

I tried this code:

```rust
fn main () {
    (1, (2, 3)).1.1;
}
```

I expected to see this happen: Code compiles

Instead, this happened:

```
./test.rs:2:16: error: failed to parse path expr segment of method call expr
    2 |     (1, (2, 3)).1.1;
      |                ^
./test.rs:2:5: error: failed to parse statement or expression in block expression
    2 |     (1, (2, 3)).1.1;
      |     ^
./test.rs:2:17: error: unrecognised token ‘float literal’ for start of item
    2 |     (1, (2, 3)).1.1;
      |                 ^~~
./test.rs:2:17: error: failed to parse item in crate
```

### Meta

- c7728c8020334fecb47789163ba94326aab6208c

**Comment by powerboat9** [comment]
It looks like this produced a similar error with rustc before 1.46

**Comment by P-E-P** [comment]
> It looks like this produced a similar error with rustc before 1.46

This was fixed in https://github.com/rust-lang/rust/pull/71322. Thanks for telling me @powerboat9
Like the rust team before me I was wondering whether we should split it like with `<<` tokens or handle it in the lexer. You saved me a lot of time.
