### ISSUE TITLE
Cannot parse weird tupple index

### ISSUE THREAD

**Issue by P-E-P** [Rust-GCC/gccrs#2663]
Cannot parse correctly tuple index with whitespace.

I tried this code:

```rust
fn main() {
    let tuple = (((),),);

    let _ = tuple. 0.0;
    let _ = tuple.0. 0;
}
```

:warning: Don't let rustfmt reformat this snippet. Whitespaces are meant to stay!

I expected to see this happen: Compiles correctly.

Instead, this happened:

```
./test.rs:4:18: error: failed to parse path expr segment of method call expr
    4 |     let _ = tuple. 0.0;
      |                  ^
./test.rs:4:20: error: failed to parse expression in let statement
    4 |     let _ = tuple. 0.0;
      |                    ^~~
./test.rs:4:5: error: failed to parse statement or expression in block expression
    4 |     let _ = tuple. 0.0;
      |     ^~~
./test.rs:5:5: error: unrecognised token ‘let’ for start of item
    5 |     let _ = tuple.0. 0;
      |     ^~~
./test.rs:5:5: error: failed to parse item in crate
```

### Meta

- c7728c8020334fecb47789163ba94326aab6208c

**Comment by nirmal-j-patel** [comment]
It appears that this happens because the parser consider 0.0 as floating point number rather than two index operators. Do we need to parse indices differently (by disabling float checking, disallowing index beginning with 0, etc.)?
https://doc.rust-lang.org/reference/tokens.html#tuple-index

**Comment by P-E-P** [comment]
> It appears that this happens because the parser consider 0.0 as floating point number rather than two index operators. Do we need to parse indices differently (by disabling float checking, disallowing index beginning with 0, etc.)? https://doc.rust-lang.org/reference/tokens.html#tuple-index

We should look if #2694 fixes the issue then

**Comment by P-E-P** [comment]
#2694 Indeed fixes a part of this code, here is the updated error message:
```
./test.rs:5:22: error: expecting ‘;’ but ‘integer literal’ found
    5 |     let _ = tuple.0. 0;
      |                      ^
./test.rs:5:5: error: failed to parse statement or expression in block expression
    5 |     let _ = tuple.0. 0;
      |     ^~~
./test.rs:5:22: error: unrecognised token ‘integer literal’ for start of item
    5 |     let _ = tuple.0. 0;
```
