### ISSUE TITLE
Compilation warnings need squashed

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#267]
We have many set but not used compilation warnings at the moment, Ideally it would be nice to have a CI pipeline to track the number of warnings in our builds but i am unaware of any way to do this right now.

**Comment by bjorn3** [comment]
Maybe you could use a problem matcher like https://github.com/actions-rs/cargo/blob/74b5d547b1ea507302d8213fa31ca6ab1e81a319/.matchers/rust.json to make github actions add an annotation for each warning. Will be quite noisy on PR's at first though.
