### ISSUE TITLE
Add Changelog file to `libgrust/`

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#2690]

**Comment by tschwinge** [comment]
Upstream GCC commit a857ec6aada08d8c334c389c7b682198d749b6c9 "libgrust: Add ChangeLog file", and GCC/Rust commit 1b6ac2229b20b7c4171c6750affc1a675e6e4ecc "libgrust: Add ChangeLog file" via #2853 "libgrust: Add missed commits for Changelog creation".
