### ISSUE TITLE
Add missing reserved keyword

### ISSUE THREAD

**Issue by P-E-P** [Rust-GCC/gccrs#2735]
Multiple keywords are missing

- [x] ~~`$crate` (update the parser, currently treated as two tokens)~~ rustc threat this as two tokens
- [x] `_` (underscore)
- [x] `{{root}}`
- [x]  other missing keyword ? ...

- Change token key prefix from `TOK` to `KW` ?

**Comment by powerboat9** [comment]
What is a ```{root}``` keyword?

**Comment by P-E-P** [comment]
> What is a `{root}` keyword?

Not entirely sure for now, I met it [here](https://github.com/rust-lang/rust/blob/master/compiler/rustc_span/src/symbol.rs#L29), there is a typo on this keyword, I missed the second pair of braces.
