### ISSUE TITLE
Compilation Flags for compiler proper

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#274]
https://github.com/Rust-GCC/gccrs/blob/b8549556123da80e60922eaa928cfd284f831303/gcc/rust/Make-lang.in#L245

We have -Wno-overloaded-virtual which there is a PR #273 that fixes some of these issues. Should we remove this compiler flag and fix these warnings properly?

**Comment by YizhePKU** [comment]
I'm confused. If we fix those issues there won't be warnings any more. Why should we remove this compiler flag?

**Comment by dkm** [comment]
`-Wunused-parameter` enables the warning, `-Wno-` disables it. So removing these may add more warnings instead of removing some.

**Comment by dkm** [comment]
I've started fixing all these problem, will create a pr later tonight :D
