### ISSUE TITLE
WIN64 is a predefined constant by GCC on MinGW-w64

### ISSUE THREAD

**Issue by MehdiChinoune** [Rust-GCC/gccrs#2768]
Original bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109853

**Comment by CohenArthur** [comment]
thanks! I'll mark this as a good first issue since it's quite easy to fix and it's been there forever haha

**Comment by braw-lee** [comment]
Hi, I would like to work on this.
From what I understand I should replace all occurrences of WIN64 enum to something else , lets say WIN_64
Let me know if there's more to it @CohenArthur

**Comment by MehdiChinoune** [comment]
I have already created a patch https://github.com/msys2/MINGW-packages/blob/8341179b/mingw-w64-gcc/2001-fix-building-rust-on-mingw-w64.patch
but It applied to gcc-13

**Comment by braw-lee** [comment]
Does that mean we don't need to fix it here? @MehdiChinoune

**Comment by MehdiChinoune** [comment]
> Does that mean we don't need to fix it here? @MehdiChinoune 

No, I haven't said that, I just say that you could use my patch.
