### ISSUE TITLE
Type param not substituted for pattern typechecking

### ISSUE THREAD

**Issue by jdupak** [Rust-GCC/gccrs#2775]
```rust
struct Ref<'a, T> {
    x: &'a T,
}

pub fn test<'a, 'b, 'c>() {
    let (_, &&Ref::<(&'_ i32, i32)>{ x: &(a, b) }): (i32, &'_ &'b Ref<'b, (&'c i32, i32)>);
}
```

At gcc\rust\typecheck\rust-hir-type-check-pattern.cc:305 check fails, because inside `Ref` it will encounter T, not a tuple and bail.

**Comment by powerboat9** [comment]
Is ```ParamType::handle_substitutions``` supposed to return a ```ParamType``` (```this```) which points to the substituted type, or the substituted type itself?
