### ISSUE TITLE
Unify `AST::ExternalFunctionitem` with `AST::Function`

### ISSUE THREAD

**Issue by P-E-P** [Rust-GCC/gccrs#2820]
The interface for both types is almost the same as well as the attributes. Since #2755 function body can now be optional. This means an `ExternalFunctionItem` could technically be replaced with a function.

One grey area remains:
External function arguments cannot be pattern (unless it is a named variadic argument).

**Comment by 0xn4utilus** [comment]
Hello, Is anyone currently working on this issue? I want to work on this issue

**Comment by CohenArthur** [comment]
Closed in #2849
