### ISSUE TITLE
Split up `rust-macro-builtins.cc`

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#2855]
the current file is getting really long, and the function for `format_args_handler` is about to get a lot longer. we're close to breaking 1000 LoC and navigation is not the easiest. it would be nice to split that file into multiple compilation units organised by theme, like all inline-assembly-related macros, all include-related macros, etc.

**Comment by badumbatish** [comment]
hi, I'll try this one out

**Comment by CohenArthur** [comment]
Closed in #2874
