### ISSUE TITLE
Create `FormatArgs` AST node

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#2856]

**Comment by badumbatish** [comment]
Hi there, I'm interested in this issue. Can I get some guidance on this issue? Not sure if I should derive FormatArgs from SingleASTNode or Visitable in rust-ast.h and what kind of member method should I look to implement this ASTNode?

**Comment by CohenArthur** [comment]
sorry @badumbatish, I hadn't seen your message - I'm already working on this issue in https://github.com/Rust-GCC/gccrs/pull/2859

I'm gonna go ahead and assign myself to the stuff I'm working on to make it easier for new contributors. sorry about that

**Comment by badumbatish** [comment]
it's good to learn how to work on this stuff
