### ISSUE TITLE
`AST::LiteralExpr` should differentiate between strings and raw strings

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#2858]
Currently parsing `r#"gccrs"#` works, but it returns a `LiteralExpr` with `LiteralType` of `Literal::STRING`, but we have a `Literal::BYTE_STRING` variant. It would be useful to have a `Literal::RAW_STRING` variant too, and we do need it for `format_args!()`

**Comment by sinduku** [comment]
hi @CohenArthur saw that the last comment was made 2 weeks ago and no pr was made yet, can i try taking a crack at this

**Comment by P-E-P** [comment]
Fixed by https://github.com/Rust-GCC/gccrs/pull/3065
