### ISSUE TITLE
Allow visibility modifiers for extern types

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#2897]
Currently we do not lower/handle the visibility modifiers properly for `ExternalTypeItem` nodes.

**Comment by badumbatish** [comment]
Can i work on this issue with some help, I don't know where should I start?

**Comment by CohenArthur** [comment]
@badumbatish I'll try writing a starting guide here today but I'm very busy, please ping me on Zulip if you get to working on this and I still haven't written anything

**Comment by CohenArthur** [comment]
alright, so here's how I would go about solving this. first, we need to make sure that visibility modifiers are actually parsed for extern type nodes (`AST::ExternalTypeItem`) - you can do that by looking at our parser, in `rust-parse-impl.h`, and searching for `ExternalTypeItem`, as there will be only one function which will create and return these nodes.

if you're sure that visibility is parsed (e.g. if the parsing function is called with a visibility, or that we call `parse_visibility` in the parsing function), then you need to ensure that this visibility is being assigned to the `ExternalTypeItem`. Check the class definition, make sure a visibility member exists and is used, etc.

now finally, the next and last step is to make sure that the AST visibility is correctly lowered to an HIR visibility when we lower our `AST::ExternalTypeItem` into an `HIR::ExternalTypeItem`. you'll have to find the visitor responsible for performing that operation and make sure the visibility is lowered and transferred properly.

once that's done, in a later PR/issue we'll check that the visibility modifiers are actually working for external types and not just ignored - but that's for later and concerns another part of the compiler :)
