### ISSUE TITLE
how to generate compile_commands.json?

### ISSUE THREAD

**Issue by zhanghe9702** [Rust-GCC/gccrs#2910]
i noticed that in .gitigore has add compile_commands.json & .clangd ignore, but there is no description how to generate compile_commands in this repository, could some nice person add instructions about it ? thx!

**Comment by dkm** [comment]
There's no unique way to do that. The most common one is to use `bear` during the compiler build.
The bare command would be:
```
$ cd build
$ bear -- make
```
then you have the `compile_commands.json`. But this also includes all libs & tools. You may want to only do that for the compiler:

```
$ cd build
$ bear -- make all-gcc
```
And if you're lucky, you can even use `-j XX` to have a parallel build, but for many people (me included) it doesn't work and `bear` hangs during the link).

I'll close this "issue", as it's not really an issue. If you have question, you should come in our zulip. This topic has been discussed several times already, see https://gcc-rust.zulipchat.com/#narrow/stream/266906-new-members/topic/Starting.20out/near/412903500 for example :)
