### ISSUE TITLE
Error out nicely if cargo is not present on the host system

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#2927]
https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/Generic-Programs.html

**Comment by tschwinge** [comment]
This is  #2881 "Add checking that `cargo` exists when building gccrs", no?

**Comment by CohenArthur** [comment]
> This is #2881 "Add checking that `cargo` exists when building gccrs", no?

aaah thank you! I couldn't find it when I looked for it earlier
