### ISSUE TITLE
Docker image and container for Mac

### ISSUE THREAD

**Issue by badumbatish** [Rust-GCC/gccrs#2937]
I ran into some issues setting up gccrs for Mac so I resorted to building an ARM-based ubuntu image for Mac with a persistent storage setting via docker-compose. I'm wondering if this can be added to the README as another alternative for ppl that's running into set up issues for Mac? Another person in the zulip channel also found sucess running this.

The repository responsible for setting up the Docker container is at https://github.com/badumbatish/gccrs-workspace

**Comment by braw-lee** [comment]
yes, looks like the best alternative right now

**Comment by dkm** [comment]
This should not be needed, as suggested by the main dev of the darwin port of GCC. I'd prefer we document the Rosetta solution first. But adding alternatives is also fine

**Comment by CohenArthur** [comment]
Fixed in #2941
