### ISSUE TITLE
`#[cfg]` attribute is not handled correctly on struct field instantiations

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#2984]
Followup to #2983 

```rust
pub struct ReadDir {
    pub inner: i32,
    #[cfg(not(A))]
    pub end_of_stream: bool,
    #[cfg(A)]
    pub end_of_stream_but_different: bool,
}

fn main() {
    let _ = ReadDir {
        inner: 14,
        #[cfg(not(A))]
        end_of_stream: false,
        #[cfg(A)]
        end_of_stream_but_different: false,
    };
}
```

is the correct version of that code, but fails to parse in the instantiation expression. `rustc` does not report any errors.

**Comment by CohenArthur** [comment]
This is also an issue for the `ffi` module in `core` 1.49

**Comment by antoniospg** [comment]
Hi there! I was trying to look at this and the other related issue. 
I'm wondering if I can just strip stuff using `CfgStrip::maybe_strip_struct_fields` for the struct declaration in `CfgStrip::visit (AST::StructStruct &struct_item)` and maybe do something similar inside `CfgStrip::visit (AST::StructExprStructFields &expr)`.  Not sure if this solves the problem or is more complex than that, it works for the above example, at least.

**Comment by CohenArthur** [comment]
@antoniospg I think that's the correct way to go about it :) feel free to submit a PR/draft PR and ping me on it so I can have a look at your code, but that sounds correct to me! thanks for working on this!
