### ISSUE TITLE
Handle `#[prelude_import]` attribute

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#2985]

**Comment by liamnaddell** [comment]
There's a code comment here: https://github.com/Rust-GCC/gccrs/blob/177660eabde15c572ee431671e239a6dbd2c93e9/gcc/rust/rust-session-manager.cc#L863C6-L864C14 , that expresses the following:

```
  // FIXME: Once we do want to include the standard library, add the prelude
  // use item
  ```
  
  I'm guessing this is blocked until we *have* a standard library?

**Comment by CohenArthur** [comment]
@liamnaddell you're right, the code generation which adds the `use prelude::v1::*`-something import is blocked until we figure out a way to compile and distribute (another hard problem) the standard library. but we still need to be able to parse the `#[prelude_import]` attribute in order to compile `core`. I'll take care of this now
