### ISSUE TITLE
Remove unnecessary #include from rust-expr.h

### ISSUE THREAD

**Issue by badumbatish** [Rust-GCC/gccrs#3051]
The file gcc/rust/ast/rust-expr.h has some dummy include line that would be perfect for newcomers to come and participate in open source.

Please remove these two lines in the file as follow, build and compile the code base to make sure every test passes and open a PR.
```diff
#include "rust-path.h"
#include "rust-macro.h"
#include "rust-operators.h"
- #include "rust-system.h"
- #include <memory>
```

Please preview the original issue inn https://github.com/Rust-GCC/gccrs/pull/2982#discussion_r1636723711:

>              ah, the system include is still here. you should be able to remove it entirely

**Comment by liamnaddell** [comment]
Could I be assigned this? I made+tested the change on arm64, and can submit a PR.

**Comment by badumbatish** [comment]
Hi @liamnaddell ! Yes please open a PR i can help with the review if needed
