### ISSUE TITLE
Cleanup vector copies from Rust to C++ in BIR

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#3066]
Perform a simple copy/move from the `FFIVector` type to an `std::vector` instead of manually copying and deleting the old memory. This is low priority and should be addressed later.

**Comment by braw-lee** [comment]
currently we are copying data from `FFIVector<Pair<size_t, FFIVector<size_t> *>>` to `std::vector<std::pair<size_t, std::vector<size_t>>>`

not sure how we can "move" that

**Comment by CohenArthur** [comment]
This issue is related to this comment: https://github.com/Rust-GCC/gccrs/pull/3058#discussion_r1651013422

(might be invalid - I'll investigate it this week)
