### ISSUE TITLE
Unable to find associated `type` in `trait`

### ISSUE THREAD

**Issue by MahadMuhammad** [Rust-GCC/gccrs#3079]
- You can view the same on [`compiler-explorer`](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DEArgoKkl9ZATwDKjdAGFUtEywYSAzKUcAZPAZMADl3ACNMYhAADlIAB1QFQjsGFzcPb3jE5IEAoNCWCKjYq0wbFKECJmICNPdPLh9S8oFK6oI8kPDImMsqmrqMxr72zoKimIBKS1QTYmR2DgB6JYBqAFIAdgAhVfRgAFomdHxbATED1DizhgUNgCZ7g6pTcwPMU5T1rwARe40uNF1o8NpsfusNABBAjEJiEVYAFVB2whkNRqwxqyoDCxqFQAH0AO6EBD4gCOJjEeBoH3xcSYBAQEG%2BTm21VWTDuCO%2B2BAIDZAC9Jt9ditkXtDpFiCQHvdMKo4mVbEZVgA6ECq1ZhEwENXrACsTgNTkmmv4JgY6GB91l1oxW12/WAmF1ACoDu7XaCft7UX6wX6odjViw4QwIJNkVsfhxprROPreJ5uLxUJwAEpmXUKWbzTAPLw8UgETSx6YAawkAE5VV4AGySR6SKube51%2B6bKtcfScSRJ0ukNMcXgKEAaYul6ZwWAwRAoVAsOJ0SLkShoRfLqLAZDIYgKA4KZhxBQIVAWGi0AiRUcQMIDsKBaoAT04RYfzGIT4A8mFtErX7w65sIIX4MLQL4cFopBYNqwBOGItCjim0GYKGRjiJBvD4MQSp4AAbpgSFQfKZQ6osRaBFe8aYfoeBhLCn4uFgA4wngLAAaQBHEGEiSYD8qGGMAtCBKAmHTFQBjAAoABqeCYISX6KsmRb8IIIhiOwUgyIIigqOoNG6N2BhGCArwWMJYSjpA0xXDcSGplxxB4FgVlQMwbAgB8OQMJxYgmIs/z3DwkzTM0NwOJagwNL4lpjN0UTdgkSQ3FFehJd5cWFD03ZhRU/S1K49R6LlrT5ZlEw5flqWVaMgRdFlCWhbmCwSHGCb9jRQ6rKo0R1gcDarAA4k4TjpkIqwQMNo3jaG5iRJGEC4IQMrAoWky8CWYkViA%2BrjtRfakOxzaqtE%2BrtlwXB1vWGinVWdakMmUFDiOY4TmJpDTnOswEHEOqrhA65LvQxDBKwixmcgqxcKqdbRKqxGnCQzl6KpwiiOIWmo7pagDoZpCErCcQAW1HCJg9A5Dl%2BOq/bqqBUN1vX9ZIQ0jWNE1TWzs1XsQC0uBuwMFlw61vVoIU9hwB3sbtqpSF4mzRNE9ZeF2kgaNIj2ppwL3jptovbUFqqbJI%2BpcEb0StvqXj3PWmzi14HVPVrIuxh9s6fRASCA5u/1e8DplSFW44XtzN53jR77PhxEefj%2Bf42BxQGMAQoHgQOMEmHBCFIUWWBoUJixQdhuEEURvAkcgZEcZRmDUVBFkMU%2BTEFxtTnschXE8Uo/F58JJnvRJTBSbJ8mKYwHGo%2BpGPSFjSg4wZID3PogmmVmtGWfANnXCkSEHAcu4MpgBwEE%2BirfD874OVKzmERvlg17h9gQI41Uxeg5XZVkyUpC/6U3O/CV32sDcNoAxCpDEAQ/BgICOh1XGB/cw7QX4IJqP/VqMw5gtSFuLMmGtBycFWBDKGqpjoaAmktIgxBBbC11mWUgCBMDHB6BGUglYuAaD2r2XgUtxy4OepYV6NCpxuyQN9GmPsFxA0iKDDyHAep9QGhzcak1WYzU5NzYWXkKHI27BPdGmlp6yGxvpKCuhF4EyYETFMJMcEU04FTH6OpVh0wIVmSG0MSETT5pIyhq17jUMnNMehjCojMNYew8Wksdo8NscOfhOsAksIXnWQ2sNjaSDrFwfUit2z6jtg7TWsTBGu3gO7T2EjvYUABuUv2xBTaBz4HQEOlAw5QWjhBN8j4Y6/n/MhROIEwIQULpgWC8FaCIQ4rnQSGFC54BwuUEuA5y6V2QtXWuvB67PibixVuHEO68W7lMkSk4%2BCSRknJBSSlx6yEnvo7S8hZ7GJ0CAHwxljCrwsq5TedlOC733leI%2BJ9MBnwvoORy19PkQJaJ4J%2BkUwHRX8LA%2BKaVsgpThcir%2BuREUNWKvfKF0CkG4uAWVLFFURigPSNFZBMD8hIqwTmDBmlrH5LwRwFx5g3GGxrKQxaiMfHWyFhtBJQSsAhP1pIVU%2Bp9SSGVhoM6XgzqSGiFWWI%2B0uFRPJp1J2o54nvVKSAURf1Km%2BykWDTghD3FcrLry7RdybkSAMTpB5uNnn40JsTbBzLKbU0cc481nL4aeOqZEAsXh/FbToQwkVlASaRN2hqx2sTtXOzFpWK2MtHhSElTKjQ8q8nxoKYK8N1F7ieqdoI6YXEkj2EkEAA)

---

I tried this modified code from [`rust-lang/rust/blob/master/tests/ui/anon-params/anon-params-denied-2018.rs)`](https://github.com/rust-lang/rust/blob/master/tests/ui/anon-params/anon-params-denied-2018.rs)

### Code

```rust
// { dg-additional-options "-frust-edition=2018" }
trait T {

    fn foo_with_qualified_path(<Bar as T>::Baz); // { dg-error "expecting .:. but .\\). found" ""  { target *-*-* } }

}

fn main() {}
```

### I expected to see this happen: 
gccrs should emit these error codes:

- [x] [Error code E0576 - An associated item wasn't found in the given type](https://doc.rust-lang.org/error_codes/E0576.html#error-code-e0576)
- [ ] [Error code E0412- A used type name is not in scope](https://doc.rust-lang.org/error_codes/E0412.html#error-code-e0412)

- Error message emitted by rustc:
```rust
error[E0576]: cannot find associated type `Baz` in trait `T`
 --> <source>:4:44
  |
4 |     fn foo_with_qualified_path(<Bar as T>::Baz);
  |                                            ^^^ not found in `T`

error[E0412]: cannot find type `Bar` in this scope
 --> <source>:4:33
  |
4 |     fn foo_with_qualified_path(<Bar as T>::Baz);
  |                                 ^^^ not found in this scope

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0412, E0576.
For more information about an error, try `rustc --explain E0412`.
Compiler returned: 1
``` 

---

### Instead, this happened:

gccrs doesn't emit any error code.

```rust
<source>:4:47: error: expecting ':' but ')' found
    4 |     fn foo_with_qualified_path(<Bar as T>::Baz);
      |                                               ^
Compiler returned: 1
```

---

### Meta

- What version of Rust GCC were you using, git sha 61bf44479706ff92dd66c4ce5abc97c4c7465b29
- gccrs (Compiler-Explorer-Build-gcc-61bf44479706ff92dd66c4ce5abc97c4c7465b29-binutils-2.42) 14.0.1 20240309 (experimental)

---

**Comment by CohenArthur** [comment]
Closed in #3089
