### ISSUE TITLE
Document build using '--enable-checking=[...]'

### ISSUE THREAD

**Issue by tschwinge** [Rust-GCC/gccrs#309]
> > or you could build using `--enable-checking=all` to see if somewhere some internal check does assert?
> 
> I always forget about that option can you add that as an example to the README?

Sure !

_Originally posted by @dkm in https://github.com/Rust-GCC/gccrs/issues/308#issuecomment-808410158_

**Comment by tschwinge** [comment]
Generally that's a very good suggestion, but note that `--enable-checking=all` may be quite a compile-time hog -- which might be fine given the current small codes that we're compiling, but I wanted to note that anyway.

Personally, for may day-to-day development, I'm using `--enable-checking=yes,extra,rtl`.

**Comment by dkm** [comment]
Yes, you are right, enabling `all` can lead to surprisingly long compile time :)
```
  --enable-checking[=LIST]
                          enable expensive run-time checks. With LIST, enable
                          only specific categories of checks. Categories are:
                          yes,no,all,none,release. Flags are:
                          assert,df,extra,fold,gc,gcac,gimple,misc,
                          rtlflag,rtl,runtime,tree,valgrind,types
```
I'm also only using `rtl` checks for my usual gcc work, so I'm still learning how to handle the frontend part.

I guess `gimple` `tree` and `types` should be more appropriate for gccrs. What do you think?
