### ISSUE TITLE
Improve compressed point bit manipulation

### ISSUE THREAD

**Issue by P-E-P** [Rust-GCC/gccrs#3111]
To be fair I would have not written it like this. We lack any documentation/intent hint with such expression. In such case I would:
- Use many constexpr or define to describe the intent of the operation (What does the 1 correspond to ? What about the mask ?) We should give a name to every hard coded constant.
- I would also (probably) change `((1 << 15) - 1)` to `0x7fff`, I think it better hints about the binary representation ? To be fair I'd like to hear from you about this.

_Originally posted by @P-E-P in https://github.com/Rust-GCC/gccrs/pull/3100#discussion_r1697998526_

**Comment by braw-lee** [comment]
assign me

**Comment by P-E-P** [comment]
> assign me

Done, thank you!
