### ISSUE TITLE
Add `-D_GLIBCXX_ASSERTIONS` CI

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#3137]
Let's fix https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116225 and add a CI to make sure this no longer happens. We should make use of every little safety feature the C++ std offers us lol

**Comment by badumbatish** [comment]
i'll do it

**Comment by badumbatish** [comment]
hi @CohenArthur this should be fixed in #3138 :)

**Comment by CohenArthur** [comment]
@badumbatish you're right, thanks! don't hesitate to add something like "Fixes #3138" or "Closes #3138" to your PR's main message so that these issues get closed automatically when we merge the PR

**Comment by badumbatish** [comment]
hehe sorry this was my bad ~~

**Comment by CohenArthur** [comment]
> hehe sorry this was my bad ~~

no worries it's not a problem :D
