### ISSUE TITLE
unexpected results from bitwise complement operator `!`

### ISSUE THREAD

**Issue by nobel-sh** [Rust-GCC/gccrs#3229]
The `!` operator produces unexpected results.

```rust
fn main(){
   let a: i32 = 5;
   let b = !a; // expected -6 gccrs gives 0.
}
```
Godbolt: https://godbolt.org/z/cKPPz1bYc

**Comment by nobel-sh** [comment]
I'm not entirely sure, but it seems that the operator is interpreting the least significant bit of the number as a boolean value and complementing it.

**Comment by philberty** [comment]
Interesting somthing silly happening with gimple this is the original tree we produce:
```
struct  example::main ()
{
  const i32 b = !a;
  const i32 a = 5;

    struct  RUSTTMP.0;
    const i32 a = 5;
    const i32 b = !a;
  return {};
}
```

then when gimplified it turns into:

```
__attribute__((cdecl))
struct  example::main ()
{
  struct  D.86;
  const i32 b;
  const i32 a;

  a = 5;
  _1 = (bool) a;
  _2 = ~_1;
  b = (const i32) _2;
  return D.86;
}



```
