### ISSUE TITLE
[WIP] Create liveness analysis for dead code detection.

### ISSUE THREAD

**Issue by thomasyonug** [Rust-GCC/gccrs#330]
This is a working issue for the 2021 GSoC. I'm little busy last two weeks, sorry about my late.

I had checked the method from rustc: [https://github.com/rust-lang/rust/blob/master/compiler/rustc_passes/src/dead.rs#L569](https://github.com/rust-lang/rust/blob/master/compiler/rustc_passes/src/dead.rs#L569)
That implementation separates two phases to detect unused code.
1. liveness analysis to get all reachable symbols.
2. code called from live codes are live， otherwise dead.

Implementation for our project.
1. first of all, we need a test for warning features. But it seems like currently our new test system doesn't supports warnings?
2. add an analysis dir which contains our Liveness class, and try to start after resolve.
3. once obtain liveness variables, we can simply scan all dead codes which not belongs to the live variable.
``` c++
  // type resolve
  Resolver::TypeResolution::Resolve (hir);
  if (options.dump_option_enabled (CompileOptions::TYPE_RESOLUTION_DUMP))
    {
      dump_type_resolution (hir);
    }

  // liveness analysis
  Analysis::LivenessAnalysis::liveness(hir);
  if (options.dump_option_enabled (CompileOptions::ANALYSIS_DUMP))
    {
      // I have no idea about what should be dumped. Maybe some bit-vectors?
    }

  if (saw_errors ())
    return;

  // scan deadcode
  Analysis::ScanDeadcode::scan();
  if (options.dump_option_enabled (CompileOptions::DEADCODE_DUMP))
    {
      // what should be dumped?
    }

  if (saw_errors ())
    return;

  // scan unused has to be done after type resolution since methods are resolved
  // at that point
  Resolver::ScanUnused::Scan ();

  if (saw_errors ())
    return;
```

Now, this is just an entry point design. I will continuously update any details on design liveness analysis and dead-code detection.
If anyone has any suggestions, plz just comment on this issue directly or @ me in zulip, thank you!

**Comment by dkm** [comment]
>     1. first of all, we need a test for warning features. But it seems like currently our new test system doesn't supports warnings?

The current setup will not tolerate any warnings in `compile` directory by default. If you want to test for specific warning you can use `dg-warning` as documented here :  https://gcc.gnu.org/onlinedocs/gccint/Directives.html

I guess that's what you are looking for ?

**Comment by thomasyonug** [comment]
Yes, dkm.This is very helpful, thanks.

**Comment by philberty** [comment]
Hi @thomasyonug for reference I was looking at this https://github.com/rust-lang/rust/blob/master/compiler/rustc_resolve/src/check_unused.rs is this what your looking at as well?

**Comment by thomasyonug** [comment]
No, check_unused.rs is similar to tree shake implementation. I think the dead code detection is our goal, so this one [https://github.com/rust-lang/rust/blob/master/compiler/rustc_passes/src/dead.rs#L569](https://github.com/rust-lang/rust/blob/master/compiler/rustc_passes/src/dead.rs#L569) may be a reference code.

**Comment by thomasyonug** [comment]
Hi @dkm , I found that compile arrays1.rs under ```compile``` directory will yield a warning 
```
../gccrs/gcc/testsuite/rust.test/compile/arrays1.rs:5:9: warning: unused name
    5 |     let a = xs[0];
      |         ^
../gccrs/gcc/testsuite/rust.test/compile/arrays1.rs:6:9: warning: unused name
    6 |     let b = xy[2];
      |         ^
```
I don't understand what you mean "The current setup will not tolerate any warnings in compile directory by default.". It seems like some test cases which will produce warnings still pass our test.

**Comment by dkm** [comment]
grrr. I guess there's still an issue with the pruning. The issue is that we want to ignore the debug output while still handling warning/error. I'll have a look, thanks!

**Comment by dkm** [comment]
```
gccrs/build/gcc/testsuite/rust/../../gccrs -B/.../gccrs/build/gcc/testsuite/rust/../../ /.../gccrs/gcc/testsuite/rust.test/compile/arrays1.rs   -fdiagnostics-plain-output     -O3 -g  -w -S -o arrays1.s
Preparing to parse files.
Attempting to parse file: .../gccrs/gcc/testsuite/rust.test/compile/arrays1.rs
beginning null denotation identifier handling
current peek token when starting path pratt parse: '['
current token (just about to return path to null denotation): '['
finished null denotation identifier path parsing - next is branching
beginning null denotation identifier handling
current peek token when starting path pratt parse: '['
current token (just about to return path to null denotation): '['
finished null denotation identifier path parsing - next is branching
SUCCESSFULLY PARSED CRATE
ran register_plugins (with no body)
SUCCESSFULLY REGISTERED PLUGINS
started injection
finished injection
SUCCESSFULLY FINISHED INJECTION
started expansion
finished expansion
SUCCESSFULLY FINISHED EXPANSION
```

I don't have the same warning. I'll have a better look later!

**Comment by dkm** [comment]
Ok, understood, these are warnings added for your dead code elim.

**Comment by thomasyonug** [comment]
Take your time plz. It's not a rush thing for me. I'll go next step first. Thanks again.

**Comment by thomasyonug** [comment]
HI @philberty , I had finished the very beginning work for this issue at pr #357 .
There are many todos we should discuss with:
1. naming problem
2. code redundancy
3. handle more cases

But consider the deadline of gsoc, I'll write an application with current work first, and then continue this issue whether I could get the job if you don't mind. :)
