### ISSUE TITLE
Should we use a git commit message format checker

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#334]
https://github.com/gsactions/commit-message-checker

Allows for PRs etc to scan commits to ensure they are of a specific format I am not 100% a fan of the format specified there but I like the idea to some extent. It would likely be irritating for WIP PRs. What do people think?

**Comment by tschwinge** [comment]
I'd play that by trust, manually.  Some kind of sensible Git commit message, sure, but I don't see much value in enforcing a specific format.

See also my comment <https://github.com/Rust-GCC/gccrs/pull/331#issuecomment-812519352>.

**Comment by NalaGinrut** [comment]
I agree with @tschwinge. Maybe we can give a good example to help people to write better commit logs. But it's unnecessary to be enforced. The natural language is different from programming language, so that the enforced format checker may cause some obstacles to the commiters.

**Comment by philberty** [comment]
I agree let's close this issue and rely on our contributor guidelines and existing git log.
