### ISSUE TITLE
The reference chain is unused

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#352]
https://github.com/Rust-GCC/gccrs/blob/da8f950b26fef3318eb6b05da1ca9d321486b54c/gcc/rust/typecheck/rust-tyty.h#L975

There are TODO's marking where the reference chain is not used. This needs to add this to the base constructor.

see PR #347

**Comment by CohenArthur** [comment]
@philberty I'd like to work on this if no one is already on it
