### ISSUE TITLE
Unexpected diagnostics with unused code pass (#330, #357)

### ISSUE THREAD

**Issue by tschwinge** [Rust-GCC/gccrs#363]
The _unused code pass_ (#330, #357, @thomasyonug) seems to produce (a good number of?) unexpected diagnostics for our current testsuite.  Please correct me if I've misunderstood this, but for `rust.test/compile/block_expr2.rs`, for example, it prints:

```
[...]/gcc/testsuite/rust.test/compile/block_expr2.rs:1:1: warning: function is never used: `[test]`
```

This doesn't seem correct as `test` is used in `let a = { test() };`.  Similar for other testcases; I haven't analyzed in detail.  Can we get this fixed easily, or should we otherwise temporarily disable these unexpected _function is never used_ diagnostics (possibly conditionally enabled by a default-off command-line flag)?

These diagnostics are "conflicting" with change that I'm working on: #362 "[testsuite] Scan for warning diagnostics, too".  ("Conflicting" in quotes as I might also match these with `dg-bogus`, XFAILed, but I'd like to avoid the overhead of adding all these directives.)

**Comment by thomasyonug** [comment]
As I mentioned in #357, it's very beginning work. 
I will have a better look to check if it's an easily fixed one in one day. If not, maybe we should disable it by default.
