### ISSUE TITLE
Mappings improvements

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#366]
https://github.com/Rust-GCC/gccrs/blob/edc4a9549145861a2e71c552f06e53c860e39d9a/gcc/rust/util/rust-hir-map.h#L117

For the compiler to be query-based we keep mappings to IDs for all AST nodes and Hir Mappings for all HIR trees. This means we can look up any node at any time.

Instead of having to do lookup_{expr, stmt....} etc to lookup a node we should have a generic:

```c++
bool lookup_hir_node (CrateNum crateNum, HirId id, HIRLookupVisitor& vis);
```

This should take a vistior and attempt to lookup item if that fails lookup impl item etc if no node was found return false to indicate an error in lookup.

The visitor should be something like:

```c++
class HIRLookupVisitor {
  void visit(HIR::Item&) = 0;
  void visit(HIR::InherentImplItem&) = 0;
  // fill the rest out with the available mappings we have    
};
```

This would be helpful for PR #365

**Comment by thomasyonug** [comment]
I see. Is vis like a callback to handle the following process of found hir node?

**Comment by thomasyonug** [comment]
Should we replace the original lookup_* api with new one? Or keep original one for existence codes?

**Comment by philberty** [comment]
I think for this issue it might be best to keep the original lookup_* api for a while I think it would be nice to make that a separate issue/PR to get rid of those.

**Comment by philberty** [comment]
> I see. Is vis like a callback to handle the following process of found hir node?

Yes I think @YizhePKU has a PR for inline visitors that might make this really cool https://github.com/Rust-GCC/gccrs/pull/318

Infact @YizhePKU do you think it is possible to have a PR to implement the inline visitors part on its own? And also do you have any opinions on this issue?

**Comment by YizhePKU** [comment]
Sure! We can implement inline visitors on its own. My currently implementation doesn't compile on GCC yet. After I fix that I'll open a PR.

The proposed improvement seems great. Maybe I'll add that returning a `bool` is not strictly necessary, since a visitor usually "returns" its result by modifying a local variable. Probably both are fine.

**Comment by CastilloDel** [comment]
I would be interested in working on this!

**Comment by CohenArthur** [comment]
@CastilloDel I'm assigning you then. Thanks!

**Comment by philberty** [comment]
I think we should close this issue as the code has changed quite a lot since 2021
