### ISSUE TITLE
Remove debug fprintf

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#370]
We use a lot of fprintf I posted a patch to add a logger to GCC based on Davids work in JIT over on #248:
The patch can be found on https://gcc.gnu.org/pipermail/gcc-patches/2021-March/566432.html

Is it time to remove the fprintf's to help with the test suite?

**Comment by philberty** [comment]
This may already be done, we have the flag -frust-debug

**Comment by tschwinge** [comment]
Right.  What remains is to move forward (or not) with the "common logger" patch.

And, somewhat related, I still have plans for better dump files for the several front end stages that GCC/Rust has.  The question is, whether we then still need this "logger" facility, or if dump files and/or manual debugger usage would be sufficient?

**Comment by philberty** [comment]
> Right. What remains is to move forward (or not) with the "common logger" patch.
> 
> And, somewhat related, I still have plans for better dump files for the several front end stages that GCC/Rust has. The question is, whether we then still need this "logger" facility, or if dump files and/or manual debugger usage would be sufficient?

The dump files for AST, HIR, typechecking are really important I think it is a barrier for entry that they are not complete and easier to read. The whole type system relies heavily on understanding the id's going on. 

I think the logger patch is not that important now that you were able to add the -frust-debug flag which is more than enough for me so far.

**Comment by mathstuf** [comment]
I don't see `fprintf` anymore at least. I think this is then complete?

**Comment by philberty** [comment]
lets dew it :100:
