### ISSUE TITLE
Trait Obligations building blocks

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#395]
From the recent discussion over the test case:

```rust
fn main() {
    let a = return;
    let b = a + 1;
    a = 123; // does not compile without this
}
```

It is now time to realise the currently Type system is not working for traits and beyond. I propose that we need to move to a 3 pass system for Type resolution:

1. Type Infer
2. Trait Solve
3. Type Check

Currently, the Type system is performing Type Inferencing and Type checking all at once but we can use this code as a way to bootstrap the type inferencing pass including the fallbacks of inference variables/never types.

In theory, the existing code should be fine but we need to remove the code that does type checking and we need to implement type coercion rules properly. https://doc.rust-lang.org/stable/reference/type-coercions.html

Then we can leave a stub trait solver pass to be filled out as part of the work into traits.

Finally we perform a full type check pass to ensure all types are compatible or emit relevant errors at the end.

**Comment by philberty** [comment]
In order to complete this we need to split type checking from type inferencing. This will require some code refactoring and cleanup.

**Comment by bjorn3** [comment]
I don't think rustc splits type checking and type inferencing. As I understand it, rustc tries first to get a concrete type for something and if that fails, it will give a `ty::Infer` (I will reference them as `?1`, `?2`, ... in the rest of this comment) and record any obligations (things that need to hold like `?1: PartialEq` or `<?1 as Deref>::Target = u8`) and once all types are inferenced as much as possible it will try to solve all unsolved obligations and subsititute the `ty::Infer` for the concrete inferenced types.

**Comment by philberty** [comment]
I think this might only be possible since the Rustc system is query based where It looks ahead and adds the obligation of Add trait and coercion to integer which lets the query system say yes 'a' is an integer.

My thinking has been that because type checking is done at the same time and GCCRS is still pass based, the above example will always fail with cannot add never-type and integer. This is because the coercion sites and obligations aren't implemented yet. 

It means in a pass based approach we see the cannot add never type with integer but create the obligation on 'a' that it needs an Add, then we hit the coercion site of "a = 123" (never-type and integer) which the https://doc.rust-lang.org/stable/reference/type-coercions.html#coercion-types says ! can be any T.  Fixes the types leaving a final pass to emit any errors for any remaining bad types.

Though maybe I need to think about this longer.

**Comment by bjorn3** [comment]
> I think this might only be possible since the Rustc system is query based where It looks ahead and adds the obligation of Add trait and coercion to integer which lets the query system say yes 'a' is an integer.

All typechecking/inferencing within a function happens inside a single invocation of the `typeck_tables` tables. What you suggest is I think similar to what rustc does except that it is less eager to replace `ty::Infer` with concrete types. I vaguely recall mrustc hitting type inference problems with doing this lazy version you suggest, but I am not quite sure if I recall it correctly.

**Comment by philberty** [comment]
I think i see what you mean by eager to replace. What if its like you say the never-type Add integer returns a new inference variable with the correct add obligation. Then the coercion site fixes it. I think your right.

I was overly worried about getting the correct error message but from some playing around in rust playground if you give a bad type to 'a' it just fails to satisy the correct obligations for the trait resolution.

**Comment by philberty** [comment]
I am chaning this issue into ticket about creating the initial building blocks for:

https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/sty/enum.ExistentialPredicate.html
https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/sty/struct.ExistentialTraitRef.html

I think with this ticket the goal test case should be to compile:

```rust
trait Foo {
    fn bar();
}

struct Baz<T>(T)
where
    T: Foo;

struct Test<T>(T);

impl<T> Foo for Test<T> {
    fn bar() {}
}

fn main() {
    let a;
    a = Test(123);

    let b;
    b = Baz(a);
}

```
