### ISSUE TITLE
Outer attributes fail to parse at the start of a file

### ISSUE THREAD

**Issue by bjorn3** [Rust-GCC/gccrs#419]
These could either be tool attributes:

```rust
#[rustfmt::ignore]
pub fn square(num: i32) -> i32 {
    num * num
}
```

Or proc macros:

```rust
#[tokio::main]
async fn main() {}
```

In both cases gccrs fails with:

```
<source>:1:2: error: expected '!' or '[' for inner attribute or shebang
    1 | #[tokio::main]
      |  ^
<source>:1:2: error: unrecognised token '[' for start of item
<source>:1:2: error: failed to parse item in crate
```

**Comment by bjorn3** [comment]
Oh, seems like attributes attached to functions in general fail to parse:

```rust
#[allow(dead_code)]
fn main() {}
```

```
<source>:1:2: error: expected '!' or '[' for inner attribute or shebang
    1 | #[allow(dead_code)]
      |  ^
<source>:1:2: error: unrecognised token '[' for start of item
<source>:1:2: error: failed to parse item in crate
```

**Comment by thomasyonug** [comment]
Does anyone work on this issue now? Because I want to add some "allow(dead_code)" tests.
I can try to look into the parser if no one is fixing this right now. File "rust-parse-impl.h" is really huge one. :)

**Comment by philberty** [comment]
Go for it @thomasyonug no attributes have been implemented in gccrs yet. It would be a great space for you to play around with. You might find creating other issues in relation to allow dead_code etc will be useful for your work.

**Comment by thomasyonug** [comment]
Thanks @philberty . Going ~
