### ISSUE TITLE
Lowering Attribute

### ISSUE THREAD

**Issue by thomasyonug** [Rust-GCC/gccrs#459]
There are some move and copy comparisons.

``` c++
AST::AttrVec outer_attribs;
...
new HIR::LoopExpr (mapping,
		std::unique_ptr<HIR::BlockExpr> (loop_block),
		expr.get_locus (), std::move (loop_label),
		std::move(outer_attribs));
```
Previous code moves a local vector into a new object. Btw we should get attributes from an AST node now. 
My question is that if I can just move the attribute from the AST node into a hir node? I'm kind of afraid that the AST node may be used after lowering-pass. 

I wish I could run an ownership checker for the moved attributes here, LOL.

**Comment by philberty** [comment]
Good find, for now, i believe we should rely on copying. I think all you should need to do is get rid of the std::move calls.

We might change how this is handled down the line if we wish to have mutable attributes but I think we should aim to keep these immutable in general at least for now.

**Comment by bjorn3** [comment]
I don't think mutable attributes will ever be necessary. Attributes are created during parsing and macro expansion and consumed during macro expansion and in later stages. At no point does an existing attribute get changed AFAIK.

**Comment by philberty** [comment]
Thanks that's good to know.

Another option @thomasyonug (but I think we should avoid it for now) is to change the HIR to take references to the attributes but it would be best to avoid it until you get more stuff working and it can always be a separate issue to cleanup later on.

**Comment by thomasyonug** [comment]
Got it, thanks @philberty @bjorn3  for ur answer.
