### ISSUE TITLE
GCC no longer requires copyright assignment

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#461]
GCC no longer requires copyright assignment: https://gcc.gnu.org/pipermail/gcc/2021-June/236182.html

What changes do we need to make to move forward? Lets figure it out here

**Comment by bjorn3** [comment]
> What changes do we need to make to move forward?

* [ ] Update CONTRIBUTING.md to list DCO as alternative to copyright assignment.
* [ ] Update README.md to remove the note about required copyright assignment.
* [ ] Maybe get a bot like @ksquirrel that checks for either `Signed-Off-By:` in the commit message, a DCO entry in `MAINTAINERS` or an entry in a list with known copyright assignments.

**Comment by tschwinge** [comment]
(It's of course fine to already collect/discuss these items, but) before implementing/changing anything, I suggest to first wait a while, for the dust to settle that seems to stir up upstream.  :-|

**Comment by philberty** [comment]
Is it time that we remove the copyright assignment from the checklist @bjorn3 has made. I have removed the risk from my status reports since https://github.com/Rust-GCC/Reporting/issues/3

**Comment by tschwinge** [comment]
ACK; actually, there hasn't been a lot of "dust to settle" upstream.  ;-)

How about I do another merge from upstream (it's been quite a while anyway), so that we get the DCO stuff in-tree?

**Comment by philberty** [comment]
Sounds like a plan, thanks @tschwinge
