### ISSUE TITLE
Add remark markdown automation

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#487]
It will be good practice down the line to have some mark-down documentation within the repo for specific areas within the compiler so we are not locked into things like github. Lets add remark lint automation for our PR's  we can use this as an example: https://github.com/rust-lang/rust-clippy/blob/master/.github/workflows/remark.yml

**Comment by tschwinge** [comment]
> I had a PR for remark automation but I have now lost this by accident.

But aren't the earlier changes still available in #449?

**Comment by mvvsmk** [comment]
Hey @philberty , I would like to work on this if you assign this issue to me. I am a new open-source developer, and this would be my first time writing remark-lint automation, so please correct me if I make any errors in the PR. Also, I found a remark automation file in the repo, which is like five months old. Would you like something like that? It is similar to the one you show in the example.
