### ISSUE TITLE
Struct definitions within a block parser error

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#519]
I tried this code:

```rust
fn main()
{
  // tuples
  let z = ();

  let o = (0,);
  let f = o.0;

  let t = (0,1);
  let s = t.1;

  let m = (0,1,2,3,4,5,6,7,8,9,10);
  let l = m.10;

  // tuple structs
  struct E();
  let e = E();

  struct O(i32);
  let so = O(0);
  let sf = so.0;

  struct T(i32,i32);
  let st = T(0,1);
  let fs = st.1;

  struct M(i32,i32,i32,i32,i32,i32,i32,i32,i32,i32,i32);
  let sm = M(0,1,2,3,4,5,6,7,8,9,10);
  let sl = sm.10;

  z
}
```

I expected to see this happen: 

This should compile without failure.

Instead, this happened:

```
<source>:16:12: error: unrecognised token ')' in type
   16 |   struct E();
      |            ^
```

### Meta

- What version of Rust GCC were you using, git sha if possible.  40b9e46abe4782348681a97c996af4c4a090d001

https://godbolt.org/z/M59M75dsc

**Comment by bjorn3** [comment]
AFAIK all items can be used within a block. Including modules for some reason (either an inline module or one with `#[path]`. just `mod foo;` is not allowed).

**Comment by philberty** [comment]
We missed this piece in the grammar that statements can be an item https://doc.rust-lang.org/reference/statements.html
