### ISSUE TITLE
DeadCode pass error handling

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#550]
The dead code pass is used to generate warnings for relevant code. It should not produce errors I think we could take a look at using rust_assert which should be more useful in diagnosing issues with the pass. Take for example:

https://github.com/Rust-GCC/gccrs/blob/210ae4f7b0fea9671482b8f01354fd5b9274f878/gcc/rust/lint/rust-lint-marklive.cc#L237

This function wraps lookup_node_to_hir which creates an interface to ignore errors that might provide bad errors such as:

https://github.com/Rust-GCC/gccrs/blob/210ae4f7b0fea9671482b8f01354fd5b9274f878/gcc/rust/lint/rust-lint-marklive.cc#L116

if node_id_to_hir_id fails the code will continue on to mark the node anyway regardless.

let's remove this function and call lookup_node_to_hir directly where required and we can use the error handling already provided and then use a rust_assert might be the simplest solution, since there should not be any issues with resolving nodes at this stage of the pipeline. If an error did occur it would signify something else going wrong.

**Comment by thomasyonug** [comment]
Yeah, I did not realize that continua thing. So can I just write 
```
  rust_assert (
    mappings->lookup_node_to_hir (expr.get_mappings ().get_crate_num (),
				  ref_node_id, &ref));
```

**Comment by thomasyonug** [comment]
I have one question here. Is the defense code of ``` tyctx->lookup_type ``` necessary here?
https://github.com/Rust-GCC/gccrs/blob/3670b0ef05041b8a1defb755804ef36e029d20db/gcc/rust/lint/rust-lint-marklive.cc#L157

**Comment by tschwinge** [comment]
Belated: yes, I generally support the reasoning/rationale in @philberty's initial issue comment.  In short, every compiler diagnostic (warning, error, etc.) should come with a motivating/documenting test case, and if it's not possible to trigger a specific diagnostic, it should be an `assert`.
