### ISSUE TITLE
cfg expansion

### ISSUE THREAD

**Issue by SimplyTheOther** [Rust-GCC/gccrs#563]
This issue is designed to act as documentation of the current `cfg` expansion system and to allow discussion regarding potential improvements to it.

The way `cfg` expansion currently works is via a recursive pass through the AST, starting from the crate. 

This is currently implemented as part of the `AttrVisitor` class (with calling code in the `MacroExpander` class), which implements a visitor for all AST nodes. As such, this entails having a "visit_x_node" method for each AST node, which then visits the child nodes. For example, a `Crate` calls this on its `Item`s, which could call it on their internal `Expr`s if they have any. 

For each node, `cfg` expansion will first expand any `cfg_attr` attributes recursively (if the node supports attributes). Then, if the node is considered "strippable", the method will check if any `cfg` attribute (not `cfg_attr` attribute) is false. If so, then the node is marked to be stripped.

The parent node to the node marked for strip will check all strippable nodes for this mark, and if they are marked to be stripped, it removes them. If the child nodes are not strippable in the context, parent nodes will only call the visitor method for the child nodes, and will not have any strip-checking functionality.

Notes:

- The reason why `cfg` expansion is treated as parted of macro expansion is because it allows the unification of handling for `cfg` attributes and `cfg` macros. 
    - Alternatively, if the macro expander became too large to be easily readable, both 'cfg' macro and 'cfg' attribute expansion could be moved to a separate 'CfgExpander' class. This is, I believe, how rustc implements it. The current code is designed to allow this by having a logical separation of 'cfg' and other macro code (e.g. by not interlacing 'cfg' expansion and macro expansion into the same pass).
    - Note that no macro expansion has actually been fully implemented yet, including `cfg` macro handling. There is a method, `expand_cfg_macro`, that reuses much of the `cfg` attribute code and should expand a `cfg` macro given a macro as input, but this is not currently called.
- `cfg_attr` attributes are used to conditionally add attributes to an node. 
- What nodes are considered "strippable" are mentioned in various places of the Rust Reference.
- The system of "mark for strip" and removal was created because it was the best idea I had at the time to allow a recursive removal of items in a straightforward and consistent way. There may be better ways that I haven't thought of to do so.
- Note that despite being called `AttrVisitor`, the class does not actually deal with any attributes other than `cfg` or `cfg_attr` attributes. I had originally intended for attributes to also be expanded in this pass, but I had not thought through the implications of this decision nor implemented any functionality that would require this. It may be better to have other attributes handled separately.

**Comment by bjorn3** [comment]
Note that in for example

```rust
#[derive(MyDerive)]
struct Foo {
    #[cfg(FALSE)]
    a: u8,
    #[cfg(not(FALSE)]
    a: u16
}
```

`MyDerive` will only see

```rust
struct Foo {
    a: u16
}
```

as the `#[cfg]` are eagerly expanded here. There are more special cases for `#[cfg]` I believe.

https://github.com/rust-lang/rust/blob/a08f25a7ef2800af5525762e981c24d96c14febe/compiler/rustc_expand/src/expand.rs#L426-L617

Full `#[cfg]` support will also require writing target specifications to specify the following things: https://github.com/rust-lang/rust/blob/a08f25a7ef2800af5525762e981c24d96c14febe/compiler/rustc_session/src/config.rs#L802-L878 in addition to the enabled `target_feature`s. Finally a new `-frust-print-cfg` flag will be necessary for cargo-gccrs to learn all enabled cfg's.

**Comment by SimplyTheOther** [comment]
> 
> 
> Note that in for example
> 
> ```rust
> #[derive(MyDerive)]
> struct Foo {
>     #[cfg(FALSE)]
>     a: u8,
>     #[cfg(not(FALSE)]
>     a: u16
> }
> ```
> 
> `MyDerive` will only see
> 
> ```rust
> struct Foo {
>     a: u16
> }
> ```
> 
> as the `#[cfg]` are eagerly expanded here. There are more special cases for `#[cfg]` I believe.
> 
> https://github.com/rust-lang/rust/blob/a08f25a7ef2800af5525762e981c24d96c14febe/compiler/rustc_expand/src/expand.rs#L426-L617

I was under the impression that all `cfg` attributes should be "eagerly expanded" (or rather processed before other attributes, in this context). 
However, [part of the link you added](https://github.com/rust-lang/rust/blob/a08f25a7ef2800af5525762e981c24d96c14febe/compiler/rustc_expand/src/expand.rs#L591-L595) seems to imply that this is incorrect:

> Non-derive macro invocations cannot see the results of cfg expansion - they will either be removed along with the item, or invoked before the cfg/cfg_attr attribute is expanded. Therefore, we don't need to configure the tokens. Derive macros *can* see the results of cfg-expansion - they are handled specially in `fully_expand_fragment`

This seems to imply to me that `cfg` expansion and macro expansion should be interlaced.

>
> 
> Full `#[cfg]` support will also require writing target specifications to specify the following things: https://github.com/rust-lang/rust/blob/a08f25a7ef2800af5525762e981c24d96c14febe/compiler/rustc_session/src/config.rs#L802-L878 in addition to the enabled `target_feature`s. 

The gccrs session manager should already provide [`target_pointer_width`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/rust/rust-session-manager.cc#L307-L308), [`target_endian`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/rust/rust-session-manager.cc#L309-L311) and [`target_family`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/rust/rust-session-manager.cc#L937-L940). Additionally, the Rust target hooks should provide `target_arch`, `target_os`, `target_env`, `target_abi`, `target_vendor`, and of course `target_feature` for each target combination.

The missing `cfg` values are `target_thread_local`, `target_has_atomic_load_store`, `target_has_atomic`, and `target_has_atomic_equal_alignment`. I attempted to add the atomic ones, but I was unsure as to how GCC represented their equivalents, and so did not end up writing anything other than a TODO note. rustc also seems to store (but not directly represent in `cfg`, if I'm not mistaken) the target binary layout.

Additionally, `cfg` does not currently add `panic`, `sanitize`, `debug_assertions`, or `proc_macro`, since the functionality for them in gccrs did not exist at the time, and I thought it would be confusing to have them in there.

>
>
> Finally a new `-frust-print-cfg` flag will be necessary for cargo-gccrs to learn all enabled cfg's.

There is [already a compile flag to dump `cfg`s](https://github.com/Rust-GCC/gccrs/blob/master/gcc/rust/rust-session-manager.cc#L904-L931), so this functionality could potentially be reused for that flag (with different formatting, presumably).

**Comment by bjorn3** [comment]
> rustc also seems to store (but not directly represent in cfg, if I'm not mistaken) the target binary layout.

That is solely used for type layout calculations.

**Comment by philberty** [comment]
This is already done as part of our macros milestone
