### ISSUE TITLE
Super traits

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#565]
https://doc.rust-lang.org/rust-by-example/trait/supertraits.html

**Comment by bjorn3** [comment]
Note that

```rust
trait Sub: Super {}
```

is pretty much equivalent to

```rust
trait Sub
    where Self: Super
{}
```

at the moment. Upcasting from `dyn Sub` to `dyn Super` isn't supported yet. `@crlf0710` has recently started implementing it though. Eg https://github.com/rust-lang/rust/pull/86461

**Comment by philberty** [comment]
Its interesting i thought of another way to implement it, but if I do like you shown here treat self as if it has a TypeBound of the super trait then it will help test some code I have to try and implement the TypeBounds
