### ISSUE TITLE
Add --cfg option

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#574]
`rustc` can benefit from the `--cfg` option in order to tweak the current compilation environment:

```sh
> rustc --help
...
--cfg SPEC      Configure the compilation environment
...
```

When compiling crates with cargo gccrs, I often encountered cargo giving rustc a cfg flag. This has already been discussed I believe, and I think having something along the lines of `-frust-cfg=...` would make sense and would be easy to use from a `rustc` context.

**Comment by mathstuf** [comment]
I see a PR merged for this, but nothing on the `master` branch here?

**Comment by bjorn3** [comment]
That PR was on the cargo-gccrs gccrs wrapper which will allow cargo to invoke gccrs. The PR only parses `--cfg`, but doesn't forward it to gccrs as it doesn't have a `-frust-cfg` option yet.
