### ISSUE TITLE
Unused code`rust-backend.c` mentioned twice in `gcc/rust/rust-object-export.c`.

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#580]
There is still `rust-backend.c` mentioned twice in `gcc/rust/rust-object-export.c`.

There is still `gcc/rust/rust-backend.h`, which still seems to be used; should its (relevant?) content move into `gcc/rust/rust-object-export.h`?

_Originally posted by @tschwinge in https://github.com/Rust-GCC/gccrs/issues/578#issuecomment-883536323_

**Comment by philberty** [comment]
The main interfaces from GCCGO we are reuseing are inside rust-gcc.cc and rust-backend.h which is the relevant prototypes for rust-gcc.cc. We ported over rust-object-export.cc which is currently unused as well.

**Comment by CohenArthur** [comment]
The file `rust-object-export.cc` still mentions `rust-backend.cc` at the top - which I think is the only thing left to fix this issue :)
