### ISSUE TITLE
The indentation of the code

### ISSUE THREAD

**Issue by NalaGinrut** [Rust-GCC/gccrs#6]
I'm going to try a bigger contribution, however, I realized that we don't have a unified indentation standard. It's better to have an auto-indentation configuration. Here I have a `clang-format`, anyone can use their preferred auto-indentation tool without bothering to do it manually. The modern IDE/editor can recognize it and auto-indent.

```
---
Language:        Cpp
# BasedOnStyle:  LLVM
AccessModifierOffset: -2
AlignAfterOpenBracket: Align
AlignConsecutiveAssignments: false
AlignConsecutiveDeclarations: false
AlignEscapedNewlinesLeft: true
AlignOperands:   true
AlignTrailingComments: true
AllowAllParametersOfDeclarationOnNextLine: true
AllowShortBlocksOnASingleLine: false
AllowShortCaseLabelsOnASingleLine: false
AllowShortFunctionsOnASingleLine: Empty
AllowShortIfStatementsOnASingleLine: false
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: false
AlwaysBreakTemplateDeclarations: false
BinPackArguments: true
BinPackParameters: true
BraceWrapping:
  AfterClass:      false
  AfterControlStatement: false
  AfterEnum:       false
  AfterFunction:   false
  AfterNamespace:  false
  AfterObjCDeclaration: false
  AfterStruct:     false
  AfterUnion:      false
  BeforeCatch:     false
  BeforeElse:      false
  IndentBraces:    false
BreakBeforeBinaryOperators: All
BreakBeforeBraces: Allman
BreakBeforeTernaryOperators: true
BreakConstructorInitializersBeforeComma: false
BreakAfterJavaFieldAnnotations: false
BreakStringLiterals: true
ColumnLimit:     120
CommentPragmas:  '^ IWYU pragma:'
ConstructorInitializerAllOnOneLineOrOnePerLine: false
ConstructorInitializerIndentWidth: 2
ContinuationIndentWidth: 2
Cpp11BracedListStyle: true
DerivePointerAlignment: false
DisableFormat:   false
ExperimentalAutoDetectBinPacking: false
ForEachMacros:   [ foreach, Q_FOREACH, BOOST_FOREACH ]
IncludeCategories:
  - Regex:           '^"(llvm|llvm-c|clang|clang-c)/'
    Priority:        2
  - Regex:           '^(<|"(gtest|isl|json)/)'
    Priority:        3
  - Regex:           '.*'
    Priority:        1
IncludeIsMainRegex: '$'
IndentCaseLabels: false
IndentWidth:     2
IndentWrappedFunctionNames: false
JavaScriptQuotes: Leave
JavaScriptWrapImports: true
KeepEmptyLinesAtTheStartOfBlocks: true
MacroBlockBegin: ''
MacroBlockEnd:   ''
MaxEmptyLinesToKeep: 1
NamespaceIndentation: All
ObjCBlockIndentWidth: 2
ObjCSpaceAfterProperty: false
ObjCSpaceBeforeProtocolList: true
PenaltyBreakBeforeFirstCallParameter: 19
PenaltyBreakComment: 300
PenaltyBreakFirstLessLess: 120
PenaltyBreakString: 1000
PenaltyExcessCharacter: 1000000
PenaltyReturnTypeOnItsOwnLine: 60
PointerAlignment: Right
ReflowComments:  true
SortIncludes:    true
SpaceAfterCStyleCast: false
SpaceAfterTemplateKeyword: true
SpaceBeforeAssignmentOperators: true
SpaceBeforeParens: Always
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 1
SpacesInAngles:  false
SpacesInContainerLiterals: true
SpacesInCStyleCastParentheses: false
SpacesInParentheses: false
SpacesInSquareBrackets: false
Standard:        Cpp11
TabWidth:        2
```

Comments?

**Comment by SimplyTheOther** [comment]
I have a clang-format that I use inside VS Code for personal readability preferences, but I'm happy for a different indentation style to be used for the final product. 

However, I think GCC might require a specific indentation style - the [GCC Coding Conventions](https://gcc.gnu.org/codingconventions.html) - though I'm not sure if they definitely apply to frontends or just "core" GCC code. I don't think any of the current frontend code is fully compliant to the GCC Coding Conventions at the moment, but the clang-format "gcc" style and an auto-format on every gccrs file could be performed before requesting a merge into the actual GCC codebase one gccrs is finished.

My clang-format for reference if anyone wants to see it (actually might need to be updated since I wrote it before giving up on making gccrs C++03 only):
```
# some lines are commented out because VS Code's clang-format didn't recognise them
Standard: Cpp03
BasedOnStyle: Mozilla
IndentWidth: 4
ColumnLimit: 102
BreakBeforeBraces: Attach
IndentCaseLabels: true
SpaceAfterTemplateKeyword: false
SpaceAfterCStyleCast: false
SpaceBeforeAssignmentOperators: true 
SpaceBeforeParens: ControlStatements
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 1
SpacesInAngles: false
SpacesInCStyleCastParentheses: false
SpacesInContainerLiterals: false
SpacesInParentheses: false
SpacesInSquareBrackets: false
AlwaysBreakAfterReturnType: None
AlwaysBreakAfterDefinitionReturnType: None
NamespaceIndentation: All
AlignAfterOpenBracket: DontAlign
AlignEscapedNewlines: Left
AllowShortFunctionsOnASingleLine: Empty
#AllowShortLambdasOnASingleLine: Empty
BreakBeforeBinaryOperators: All
BreakBeforeTernaryOperators: true
BreakConstructorInitializers: AfterColon
#BreakInheritanceList: AfterColon
ConstructorInitializerAllOnOneLineOrOnePerLine: false
Cpp11BracedListStyle: false
IndentPPDirectives: None
IndentWrappedFunctionNames: true
MaxEmptyLinesToKeep: 1
PointerAlignment: Left
ReflowComments: true
#SpaceBeforeCpp11BracedList: true
BinPackArguments: true
BinPackParameters: true
#AllowAllArgumentsOnNextLine: true
#AllowAllConstructorInitializersOnNextLine: true 
#AllowAllParametersOfDeclarationOnNextLine: true
```

**Comment by NalaGinrut** [comment]
I found there's a `clang-format` in gcc, https://github.com/gcc-mirror/gcc/blob/master/contrib/clang-format

And here's the information about it: https://gcc.gnu.org/legacy-ml/gcc-patches/2015-11/msg02285.html

I think it's better to abide to it.

**Comment by philberty** [comment]
Yeah lets try and stick to what the gcc/contrib one is i haven't been that concerned with it but lets try to make future patches ad hear:

https://github.com/jidicula/clang-format-action

Lets get a PR in to format our code. I want to avoid doing a merge of GCC upstream for a while it always takes longer than i think to get things compiling again so we could copy the file over into our rust folder and just worry about that folder for now.

**Comment by NalaGinrut** [comment]
Actually, we don't even have to maintain the whole gcc code, the front-end of gcc can exist outside gcc, and can be detected if you make a link to gcc/rust.

**Comment by philberty** [comment]
sounds good lets do that

**Comment by philberty** [comment]
reopening as this was wrongly closed with the commit referencing the issue

**Comment by philberty** [comment]
Is the code formatting working ok for us? @SimplyTheOther @NalaGinrut can you confirm if my emacs editor is respecting this correctly

**Comment by SimplyTheOther** [comment]
The whitespace to me doesn't seem to have any significant changes after the gcc/contrib clang-format is applied, so the formatting does appear to be working.

**Comment by NalaGinrut** [comment]
@philberty @SimplyTheOther I think it's OK to use after my test. BTW, if you are using auto-indent-after-save inside editor, don't forget to upgrade to clang-format 10, it's faster for a big code block, and many of our files are more than 10K now.

**Comment by philberty** [comment]
Thanks i think we can close this issue then
