### ISSUE TITLE
Modules without module files

### ISSUE THREAD

**Issue by flip1995** [Rust-GCC/gccrs#645]
When looking at this [rustc test case](https://github.com/rust-lang/rust/tree/master/src/test/ui/invalid-module-declaration) I learned that modules can exist and be used without a `mod.rs` file.

Consider this crate structure:

```
├── aux
│   └── foo
│       └── mod.rs
└── main.rs
```
_NOTE: There is no `aux/mod.rs` file!_

and this file content:

```rs
// aux/foo/mod.rs
pub fn f() -> i32 { 42 }
```

```rs
// main.rs
mod aux {
    pub mod foo;
}

fn main() {
    println!("{}", aux::foo::f());
}
```

When run this with `cargo run` this will compile and output `42` (as expected!? :upside_down_face:)

If you want to try it out, just checkout this repo: https://github.com/flip1995/mod_without_mod

cc @CohenArthur  since you're working on compiling multiple files.

**Comment by CohenArthur** [comment]
Wow, thanks a lot for finding that out. I'll look into rustc to see how this works. This is definitely an interesting test case I think

**Comment by mathstuf** [comment]
So I started looking into this. My hacks involved tracking module scopes in the `Lexer` (almost certainly not the right place) and `Module` itself. However, it is unknown how to strip enough components from the including path. Now that I've written this, I think I may have another idea…testing that out.

In any case, other interesting cases to consider:

```rust
mod dont_be_lazy {
    mod middle {
        mod inner; // naively searching by trying to incrementally add the scopes and search will find…
    }
}

mod inner; // …this module file
```

```rust
// Referred to via #![path = "some_other_directory/file.cxx"]
mod middle {
    mod inner; // Where is this looked up (need to check with `rustc`)?
}
```
