### ISSUE TITLE
Run failed: Build Docker image - master (28f527c)

### ISSUE THREAD

**Issue by tschwinge** [Rust-GCC/gccrs#691]
Pushed to master branch commit 28f527c9598339cf834a30b5ee1f14258b8ecbb2 "Merge commit '2961ac45b9e19523958757e607d11c5893d6368b' [#247]", and got <https://github.com/Rust-GCC/gccrs/actions/runs/1272865945> in return.

**Comment by philberty** [comment]
For some reason, it's not picking up our docker hub username and password secrets from the repo. Can't seem to find much info on this.

**Comment by philberty** [comment]
This is now fixed the secrets needed to be part of the organisation not the repo for it to pick up the docker username and pass

**Comment by philberty** [comment]
Good point @tschwinge I think there are options here to limit/change the jobs for forks of the repo.

**Comment by philberty** [comment]
I've added this ticket to my current plan just to keep it on my radar to see what we can do to improve the experience for forked repos.

**Comment by philberty** [comment]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository
Seem to be the relevant options but not sure what we should set.

**Comment by tschwinge** [comment]
Or this maybe: <https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository>?

**Comment by philberty** [comment]
that looks like the perfect solution!

**Comment by philberty** [comment]
Looks like https://github.com/Rust-GCC/gccrs/pull/1124 fixes this
