### ISSUE TITLE
Remove token trees in HIR

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#70]
Assuming that (unexpanded) attributes and macros don't exist in the HIR, tokens shouldn't be required either, I don't think. The AST `Token` is only used for storing the token data in macro invocations or attributes. Maybe a note of this could be made or something instead of actual deletion at this point, just in case it turns out that tokens are in fact needed.

_Originally posted by @SimplyTheOther in https://github.com/Rust-GCC/gccrs/pull/64#discussion_r545137266_

**Comment by bjorn3** [comment]
Inert attributes like `#[inline]` and `#[no_mangle]` are still present in HIR. They use a restricted syntax compared with proc macro attributes though: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/ast/struct.MetaItem.html
