### ISSUE TITLE
Get rid of lambda within AST::PathPattern

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#717]
https://github.com/Rust-GCC/gccrs/blob/99c28309d3553346d4f0337dbae49f4a8e48da01/gcc/rust/ast/rust-path.h#L307-L315

Lambda's like this need to be removed they make working with the IR's more complex for static analysis. To fix this issue you should be able to remove this lambda helper function and provide a method to return a reference to the values like

```c++
std::vector<PathExprSegment>& get_segments() { return segments; }
```

**Comment by mvvsmk** [comment]
Hey @CohenArthur, is this issue still active? If yes, I would like to work on it. Could you please assign it to me?

**Comment by CohenArthur** [comment]
@mvvsmk I think it should still be active! Otherwise, we should have closed it :D You can always check and report back, I'll assign you. Thanks a lot!!!!
