### ISSUE TITLE
Get rid of lambda within AST::QualifiedPathInType

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#719]
https://github.com/Rust-GCC/gccrs/blob/99c28309d3553346d4f0337dbae49f4a8e48da01/gcc/rust/ast/rust-path.h#L1033-L1040
Lambda's like this need to be removed they make working with the IR's more complex for static analysis. To fix this issue you should be able to remove this lambda helper function and provide a method to return a reference to the values like

```c++
std::vector<TypePathSegment>& get_segments() { return segments; }
```

**Comment by mvvsmk** [comment]
Hey, @CohenArthur , I think this issue was fixed in the PR #783 , as I can't find the quoted function in the most recent version of rust-path.h. If this was not completely fixed, do let me know I would like to work on it.

**Comment by CohenArthur** [comment]
@mvvsmk yup I think you're right! I'll close this. There are other lambdas still in the project if you want to work on those :D Let me know and I can open more issues or you can search for them in the code since I know you're comfortable with what these lambdas look like know

**Comment by mvvsmk** [comment]
@CohenArthur Sure, I'll take a look.
