### ISSUE TITLE
Get rid of lambda in TyTy::FnPtr iterate_params

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#734]
Just like the other lambda's, this is a bad way to do static analysis on the parameters.  https://github.com/Rust-GCC/gccrs/blob/3057d98a4e3fc777b06e51cd678723f5c5b4c898/gcc/rust/typecheck/rust-tyty.h#L1267

The problem here is that for function pointers there can be type indirection so we wrap up the parameters within TyVar's so it forces a lookup based on the context. To fix this issue:

- [ ] Remove iterate_params function
- [ ] Create new get_params function

This get params function should either:

1. Simply return the std::vector<TyVar>& params
2. Or we could create a new std::vector or TyTy::BaseType* and construct it with param[idx].get_tyty().

I am not sure which is the cleanest solution right now I think the 2nd one fits in best.

**Comment by mvvsmk** [comment]
Hey, @philberty, I would like to work on this issue. Could you assign it to me? I understood the first solution, but I'd like to try out the second one too.
