### ISSUE TITLE
Get rid of iterate_fields lambda in TyTy::TupleType

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#735]
Just like the other lambda's, this is a bad way to do static analysis on the parameters.  https://github.com/Rust-GCC/gccrs/blob/3057d98a4e3fc777b06e51cd678723f5c5b4c898/gcc/rust/typecheck/rust-tyty.h#L590

The problem here is that for function pointers there can be type indirection so we wrap up the parameters within TyVar's so it forces a lookup based on the context. To fix this issue:

- [ ] Remove iterate_fields function
- [ ] Create new get_fields function

This get params function should either:

1. Simply return the std::vector<TyVar>& fields
2. Or we could create a new std::vector or TyTy::BaseType* and construct it with field[idx].get_tyty().

I am not sure which is the cleanest solution right now I think the 2nd one fits in best.

**Comment by cls** [comment]
Hi, I'd be interested in doing this as a first PR, if it still needs doing?

**Comment by philberty** [comment]
Hi @cls yep this is still open! feel free to ask question and join our zulip server.
