### ISSUE TITLE
Get rid of lambda iterate_fields in TyTy::ADTType

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#736]
https://github.com/Rust-GCC/gccrs/blob/3057d98a4e3fc777b06e51cd678723f5c5b4c898/gcc/rust/typecheck/rust-tyty.h#L1073

This class already has a helper to access the fields this lambda iterator should be avoided and the direct reference accessors provide a cleaner interface for a loop instead.

**Comment by mvvsmk** [comment]
Hey @philberty I think this issue is closed, and was fixed in commit  : `6e69ab6d0853da706441bc26ed6379348d1d463a` 
[link to the commit](https://github.com/Rust-GCC/gccrs/commit/6e69ab6d0853da706441bc26ed6379348d1d463a)
