### ISSUE TITLE
Bad fatal_error

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#784]
This is not related to your PR but lets raise an issue about this fatal_error it should be an assertion

_Originally posted by @philberty in https://github.com/Rust-GCC/gccrs/pull/783#discussion_r739888312_

**Comment by CohenArthur** [comment]
Note that since then, the code has been moved to `rust-ast-lower-type.cc`. There are three calls to `rust_fatal_error` which should all be turned into assertions
