### ISSUE TITLE
Shadowing rules

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#82]
Shadowing of declarations need to be respected for core data structures such as:

let mut x;
x = 4;
let mut x;
x = true;

**Comment by bjorn3** [comment]
Did you mean to write `let mut x;` twice and `x = true`? In the example you provided there is no shadowing.

**Comment by philberty** [comment]
Thanks @bjorn3 i am trying to create a lot of tickets to and milestones to be used for my personal reporting at the moment sorry for the flurry of tickets.

**Comment by bjorn3** [comment]
No problem. Rust-analyzer is currently spamming me more with triage work than this repo :)
