### ISSUE TITLE
Option Type requires lang items

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#850]
I tried this code: https://godbolt.org/z/YdPTMGqEd

```rust
extern "C" {
    fn printf(s: *const i8, ...);
}

enum Option<T> {
    #[lang = "None"]
    None,
    #[lang = "Some"]
    Some(T),
}

fn divide(numerator: f64, denominator: f64) -> Option<f64> {
    if denominator == 0.0 {
        None
    } else {
        Some(numerator / denominator)
    }
}

fn main() {
    let result = divide(2.0, 3.0);

    match result {
        Some(x) => unsafe {
            let a = "Result: %i\n\0";
            let b = a as *const str;
            let c = b as *const i8;

            printf(c, x);
        },
        None => unsafe {
            let a = "Cannot divide by 0\n\0";
            let b = a as *const str;
            let c = b as *const i8;

            printf(c);
        },
    }
}

```

I expected to see this happen: compile without error

Instead, this happened:

```
<source>:10:9: error: failed to find name: None
   10 |         None
      |         ^
<source>:12:9: error: Cannot find path 'Some' in this scope
   12 |         Some(numerator / denominator)
      |         ^
<source>:20:9: error: Cannot find path 'Some' in this scope
   20 |         Some(x) => println!("Result: {}", x),
      |         ^
```

### Meta

- What version of Rust GCC were you using, git sha if possible. 69f6be3ee483c9895b4b5187a44b3e1c8be2ba63

**Comment by goar5670** [comment]
Hello, I want to work on this issue if it's not too difficult. I played with it for a bit and found out that it fails at the resolution step because of an incomplete canonical path but the problem is that we handle lang items later in ast lowering, so I'm currently stuck :) what do you suggest here?

**Comment by philberty** [comment]
This might be a tricky one the test case is missing the prelude use statement which injects the name of Some and None so you don't need a full canonical path so the patch should be relating to use statements.
