### ISSUE TITLE
must_use attribute support

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#856]
see: https://github.com/rust-lang/rust/blob/2b681ac06b1a6b7ea39525e59363ffee0d1a68e5/library/core/src/result.rs#L537-L543

This attribute is very important in rust to provide an error when the result is not used. This seems like a very good candidate to be implemented at the GCC IR level using TREE_USED to track it possibly with a custom ATTRIBUTE on the tree.

**Comment by bjorn3** [comment]
This attribute can be applied to both types and functions.
