### ISSUE TITLE
Missing location info on AST::MatchArm

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#863]
We are missing location info on the match arms: https://github.com/Rust-GCC/gccrs/blob/69f6be3ee483c9895b4b5187a44b3e1c8be2ba63/gcc/rust/ast/rust-expr.h#L4222

- [ ] Remove old unused code here https://github.com/Rust-GCC/gccrs/blob/69f6be3ee483c9895b4b5187a44b3e1c8be2ba63/gcc/rust/ast/rust-expr.h#L4304-L4331
- [ ] Remove old unused code here https://github.com/Rust-GCC/gccrs/blob/master/gcc/rust/ast/rust-expr.h#L4388-L4476
- [ ] Update parser to add location info for https://github.com/Rust-GCC/gccrs/blob/69f6be3ee483c9895b4b5187a44b3e1c8be2ba63/gcc/rust/ast/rust-expr.h#L4222 
- [ ] Update HIR::MatchArm with the constructor and copy constructors https://github.com/Rust-GCC/gccrs/blob/69f6be3ee483c9895b4b5187a44b3e1c8be2ba63/gcc/rust/hir/tree/rust-hir-expr.h#L3613-L3660
- [ ] remove old unused code https://github.com/Rust-GCC/gccrs/blob/69f6be3ee483c9895b4b5187a44b3e1c8be2ba63/gcc/rust/hir/tree/rust-hir-expr.h#L3725-L3813
- [ ] update location info for match arm in code generation https://github.com/Rust-GCC/gccrs/blob/69f6be3ee483c9895b4b5187a44b3e1c8be2ba63/gcc/rust/backend/rust-compile-expr.cc#L270

**Comment by mvvsmk** [comment]
Hey @philberty  could you please assign me this issue, I am almost done with it, and will create a PR soon just as my github workflow runs finish, I also added a a get locus member function too to retrive the locus of the match arm.

**Comment by philberty** [comment]
Awesome @mvvsmk go for it :D i have assigned it to you.
