### ISSUE TITLE
'-m32' FAIL: rust/execute/torture/match3.rs   -O0  output pattern test

### ISSUE THREAD

**Issue by tschwinge** [Rust-GCC/gccrs#871]
At #866 commit 6d0892636e9642e75a858c40c45acd1df79c63e1 "Add support for wildcard patterns within MatchExprs", the new `rust/execute/torture/match3.rs` FAILs its *output pattern test* for `-m32`:

```
PASS: rust/execute/torture/match3.rs   -O0  (test for excess errors)
Setting LD_LIBRARY_PATH to .:.:
Execution timeout is: 300
spawn [open ...]
Foo::A
wildcard
wildcard
Foo::D 20 0
PASS: rust/execute/torture/match3.rs   -O0  execution test
FAIL: rust/execute/torture/match3.rs   -O0  output pattern test
Output was:
Foo::A
wildcard
wildcard
Foo::D 20 0

Should match:
Foo::A
wildcard
wildcard
Foo::D 20 80
```

Same for other optimization levels.

Similar to #844 "'-m32' FAIL: rust/execute/torture/match1.rs -O0 output pattern test"?

**Comment by philberty** [comment]
This is fixed via #1453
