### ISSUE TITLE
Failed to checkout this branch .Minimal support for Zba,Zbb,Zbc,Zbs bitmanip instructions in gcc 12 commit= 149e217033f01410a9783c5cb2d020cf8334ae4c

### ISSUE THREAD

**Issue by richunorman-1** [Rust-GCC/gccrs#895]
I couldn't checkout the given branch for riscv-gcc12 it shows the following error.On 06 January 2022 I could checkout the same branch.It would be helpful if you could provide how gcc 12 here supports bitmanip instruction .
I checkout the branch with -b and got gcc12-make-error

![gcc12-make-error](https://user-images.githubusercontent.com/98153503/151346966-e2fc9590-9dbf-4cac-8ab5-ccd76293ec3b.png)
![gcc-12-branch-checkout-error](https://user-images.githubusercontent.com/98153503/151346978-b5030cfd-2e50-4f14-8496-183063f37229.png)

**Comment by dkm** [comment]
Same as  #896.

Also, when opening issues, screenshot are not the preferred option, they are hard to read and can't be searched or copy/pasted.

**Comment by richunorman-1** [comment]
Thank you for your response

**Comment by dkm** [comment]
Also, I believe you are not using `git checkout` correctly. The correct way would be `git checkout -b some_branch_name SHA1` (where SHA1 is the long hexadecimal number you are using). And usually, you don't checkout a SHA1, but a branch name or a tag, so you may want to double check what you are trying to do :)
And finally, you are showing a log where you are installing files in `/lib/....`. That would indicate that you are installing things system wide. That can be OK, but beware that installing critical parts like GCC like this can overwrite the ones installed by your distribution and may break your system. Try installing things in other directories (use `--prefix /home/youruser/tmp/gcc-install` for example).

**Comment by richunorman-1** [comment]
Now I couldn't checkout the given branch for riscv-gcc (gcc 12) it shows the following error.I could checkout the same branch previously **It would be helpful if you could provide how gcc 12 here supports bitmanip instruction .**
I tried to checkout with -b
![gcc-12-branch-checkout-error](https://user-images.githubusercontent.com/98153503/151513143-018251ce-638b-4e0c-bc4f-fbb75ea5b5dd.png)
![gcc12-make-error](https://user-images.githubusercontent.com/98153503/151513132-725543d1-b833-4097-b0f8-8456d0390ab4.png)

**Comment by dkm** [comment]
Sorry, but again, not the correct location to ask for help about gcc and riscv. Please send your question to the gcc-help@ mailing list :)

**Comment by richunorman-1** [comment]
I have posted the query in the riscv-gcc only. But that particular commit is available in Rust-gcc repository and all the queries are redirected.
