### ISSUE TITLE
Failed to make install 'riscv-newlib' with Minimal support of bitmanip instructions commit = 149e217033f01410a9783c5cb2d020cf8334ae4c (gcc 12)

### ISSUE THREAD

**Issue by richunorman-1** [Rust-GCC/gccrs#896]
I git clone this particular gcc branch once(on 6 January 2022) and Then tried to install other riscv repositories .I could not install newlib it show the following error. #GCC #riscv-gcc12
![gcc-12-newlib-error](https://user-images.githubusercontent.com/98153503/151348310-2bb6bbb6-d5b5-484d-89a1-75bb38b8aac5.png)
[error-on-newlib- gcc12.txt](https://github.com/Rust-GCC/gccrs/files/7949943/error-on-newlib-.gcc12.txt)

**Comment by dkm** [comment]
Hi @richunorman-1 . I think you are really looking for more general GCC help. This github project is really about developing a Rust frontend for gcc. Maybe you should try asking for help on the gcc-help mailing list : https://gcc.gnu.org/mailman/listinfo/gcc-help
You should not use this repository for anything else but rust dev.

Will close this issue, but don't hesitate to open a new one if you have a question on the rust frontend for GCC :)

**Comment by richunorman-1** [comment]
Thank you for your response
