### ISSUE TITLE
Rustc expects `B` to be between double quotes.

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#910]
Rustc expects `B` to be between double quotes.

_Originally posted by @bjorn3 in https://github.com/Rust-GCC/gccrs/pull/909#discussion_r799681447_

**Comment by tschwinge** [comment]
Confirmed:

```
$ rustc --cfg A=B gcc/testsuite/rust/compile/cfg5.rs && echo OK
error: invalid `--cfg` argument: `A=B` (expected `key` or `key="value"`)
```

```
$ rustc --cfg A=\"B\" gcc/testsuite/rust/compile/cfg5.rs && echo OK
OK
```

<https://doc.rust-lang.org/rustc/command-line-arguments.html#--cfg-configure-the-compilation-environment>
