### ISSUE TITLE
Look into comma expansion in repetition

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#968]
Helpful test case posted by @flip1995 :

```rust
macro_rules! add {
    ($e:expr, $($es:expr),*) => {
        $e + add!($($es),*)
    };
    ($e:expr) => {
        $e
    };
}

fn main() {
    println!("{}", add!(1, 2, 3));
}
```

**Comment by CohenArthur** [comment]
Some more info:
```rust
macro_rules! after_otc {
    ($($e:literal) some tok *) => {
        0 $(+ $e)*
    }
}
```
does not parse properly
```rust
macro_rules! after_otc {
    ($($e:literal) | *) => {
        0 $(+ $e)*
    }
}

macro_rules! after_otc_tok {
    ($($e:literal) tok *) => {
        0 $(+ $e)*
    }
}
```
are both fine. So I am assuming that one token is valid after the repetition pattern. I'm still looking inside the reference for the actual word on this

**Comment by bjorn3** [comment]
https://veykril.github.io/tlborm/decl-macros/macro_rules.html#repetitions calls it a separator token.

**Comment by CohenArthur** [comment]
Ah, fantastic thank you @bjorn3. I had missed it but it is in the reference:
```
MacroMatch :
      [Token](https://doc.rust-lang.org/reference/tokens.html)except $ and delimiters
   | MacroMatcher
   | $ [IDENTIFIER](https://doc.rust-lang.org/reference/identifiers.html) : MacroFragSpec
   | $ ( MacroMatch+ ) MacroRepSep? MacroRepOp
```
Fantastic

**Comment by CohenArthur** [comment]
We need multiple things for this issue to be resolved:
- [ ] Match separators properly in `match_n_matches()`
- [ ] Shift the user's input properly when a separator is present:
Instead of skipping just pattern.size() + 3 for the pattern + 2 parentheses + repetition operator, we need to also skip the repetition operator if present
