### ISSUE TITLE
Support `#[rustc_builtin_macro]` attribute

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#972]
As pointed out by @bjorn3, there is a special attribute used in the rust standard library regarding builtin macros. We should look for this attribute on an `AST::MacroRulesDefinition` and if present, take the associated builtin transcriber

**Comment by CohenArthur** [comment]
The way the attribute works is that the attribute is gated: Without the `rustc_attrs` feature enabled, an error will be emitted by the compiler: `internal implementation detail`. I think that a good implementation for now would be to register a macro without an associated transcriber upon seeing this attribute, and then when parsing a macro implementing it, replacing the empty transcriber by one with our associated function.

This is almost what we're already doing, but more thought out and clearer.

**Comment by bjorn3** [comment]
All attributes prefixed with `rustc_` are gated behind the `rustc_attrs` feature afaik, including non-existent ones.

**Comment by CohenArthur** [comment]
@liushuyu do you think we can close this one? Is there anything left you think you didn't handle in your PR?

**Comment by liushuyu** [comment]
> @liushuyu do you think we can close this one? Is there anything left you think you didn't handle in your PR?

I can't think of any from the top of my head. We currently do not handle `rustc_attrs` gating though, so that's probably one case that my PR did not handle.

**Comment by CohenArthur** [comment]
Yes, but since there's a bunch of attributes hidden behind that feature I think it's fine to treat it separately. We also don't handle feature gatting at all at the moment. Closing this for now then, but we can reopen it should anything prop up. Thanks!
