### ISSUE TITLE
Implement `env!()` builtin macro

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#977]
`env!()` is part of the list of builtin macros enumerated [here](#927)

Its description is as follows:
> Inspects an environment variable at compile time

The goal is to fetch environment variables passed to gccrs, and expand them into the user's compiled code.
```fish
arthur@platypus ~/G/gccrs (add-assert-macro)> cat test.rs
fn main() {
    let s = env!("CUSTOM");

    println!("{}", s);
}
arthur@platypus ~/G/gccrs (add-assert-macro)> rustc test.rs
error: environment variable `CUSTOM` not defined
 --> test.rs:2:13
  |
2 |     let s = env!("CUSTOM");
  |             ^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

arthur@platypus ~/G/gccrs (add-assert-macro) [1]> CUSTOM='hi!' rustc test.rs
arthur@platypus ~/G/gccrs (add-assert-macro)> ./test
hi!
```
The macro should not expand to a function call that fetches environment variables during the user's program's execution.
```sh
arthur@platypus ~/G/gccrs (add-assert-macro)> ./test
hi!
arthur@platypus ~/G/gccrs (add-assert-macro)> CUSTOM='something else!' ./test
hi!
```

The original macro contains two match arms, including one with a custom error message:
```rust
    macro_rules! env {
        ($name:expr $(,)?) => {{ /* compiler built-in */ }};
        ($name:expr, $error_msg:expr $(,)?) => {{ /* compiler built-in */ }};
    }
```

You should try and support the first form first, by simply fetching an environment variable and creating an associated string using the `make_string` function defined in [`gcc/rust/expand/rust-macro-builtins.cc`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/rust/expand/rust-macro-builtins.cc)

The second form could be implemented in a later PR for simplicity

**Comment by bjorn3** [comment]
Rustc has a dep file extension showong which env vars are read and if valid UTF-8 what value saod env vars had. This is used by cargo to rebuild if the env vars change.

**Comment by CohenArthur** [comment]
Oh that's really smart. I think this is still a little far for gccrs but we should keep it in mind. I'm guessing this is what [this line](https://github.com/rust-lang/rust/blob/03c8ffaacb040a8753ef8e1accea701bc9f5be85/compiler/rustc_builtin_macros/src/env.rs#L25) is for, then. We'll definitely need to look into it before compiling actual projects

**Comment by bjorn3** [comment]
Yes, and this is where it is emitted: https://github.com/rust-lang/rust/blob/45e2c2881d11324d610815bfff097e25c412199e/compiler/rustc_interface/src/passes.rs#L703-L706 And this is the PR originally implementing it: https://github.com/rust-lang/rust/pull/71858

**Comment by omachota** [comment]
Hi, I would like to work on this issue.

**Comment by CohenArthur** [comment]
Hi @omachota, and welcome! I've assigned you the issue. Feel free to ask any questions here
