### ISSUE TITLE
Remove rust-ast-containers.h

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#98]
This file is similar to the last one in that it should also be removed, for similar reasons. This was also a failed "first attempt" at an AST layout that should be unused in the current codebase.

_Originally posted by @SimplyTheOther in https://github.com/Rust-GCC/gccrs/pull/96#discussion_r547917740_

**Comment by dkm** [comment]
Hi ! I wanted to see if I could find any simple PR and gave a shot at this one. But it seems it's a bit too simple as the file is never used and there's nothing to fix after removing it. Is there something else to do or is it really this simple ? :D

**Comment by philberty** [comment]
> Hi ! I wanted to see if I could find any simple PR and gave a shot at this one. But it seems it's a bit too simple as the file is never used and there's nothing to fix after removing it. Is there something else to do or is it really this simple ? :D

That should be it if it works for you and make check-rust is ok.
